using System.Collections.Generic;

namespace L1MapViewer.Localization
{
    /// <summary>
    /// Traditional Chinese (zh-TW) string resources
    /// </summary>
    public static class Strings_zhTW
    {
        public static Dictionary<string, string> GetStrings() => new()
        {
            // === Menu Items ===
            { "Menu_File", "檔案" },
            { "Menu_File_OpenClient", "開啟天堂客戶端讀取地圖" },
            { "Menu_File_Export", "匯出地圖通行資料" },
            { "Menu_Import", "匯入" },
            { "Menu_Import_Material", "匯入素材..." },
            { "Menu_Import_Fs32ToNewMap", "匯入地圖包到新地圖..." },
            { "Menu_Database", "資料庫設定" },
            { "Menu_MapEditor", "地圖編輯器" },
            { "Menu_Help_Discord", "到 Discord 討論" },
            { "Menu_Language", "語言" },
            { "Menu_Export_ServerPassability", "輸出伺服器通行txt" },
            { "Menu_Export_L1JFormat", "L1J 格式" },
            { "Menu_Export_DIRFormat", "DIR 格式" },

            // === Tab Pages ===
            { "Tab_MapPreview", "地圖預覽" },
            { "Tab_S32Editor", "S32 編輯器" },
            { "Tab_MapList", "地圖列表" },
            { "Tab_S32Files", "S32 檔案" },
            { "Placeholder_SearchMap", "搜尋地圖 (ID 或名稱)..." },

            // === Buttons - Common ===
            { "Button_OK", "確定" },
            { "Button_Cancel", "取消" },
            { "Button_Save", "儲存" },
            { "Button_Close", "關閉" },
            { "Button_New", "新增" },
            { "Button_Edit", "編輯" },
            { "Button_Delete", "刪除" },
            { "Button_Replace", "替換" },
            { "Button_ClearL7", "清L7" },
            { "Button_Copy", "複製" },
            { "Button_Paste", "貼上" },
            { "Button_Undo", "復原" },
            { "Button_Redo", "重做" },
            { "Button_Search", "搜尋" },
            { "Button_Refresh", "重新整理" },
            { "Button_Browse", "瀏覽" },
            { "Button_Apply", "套用" },
            { "Button_Reset", "重設" },

            // === Buttons - MapForm ===
            { "Button_JumpToCoord", "跳轉" },
            { "Button_ReloadF5", "重新載入 (F5)" },
            { "Button_SaveS32", "保存 S32" },
            { "Button_AnalyzeAttr", "分析屬性" },
            { "Button_SelectAll", "全選" },
            { "Button_SelectNone", "全不選" },
            { "Button_CopySettings", "複製設定" },
            { "Button_CopyMapCoords", "複製座標" },
            { "Button_ImportFs32", "匯入地圖包" },
            { "Button_SetPassable", "允許通行" },
            { "Button_SetImpassable", "禁止通行" },
            { "Button_EditLayer5", "編輯半透明" },
            { "Button_RegionEdit", "區域編輯" },
            { "Button_ExportS32", "匯出 S32" },
            { "Button_NewS32", "新增 S32" },
            { "Button_ClearLayer7", "清除傳送點" },
            { "Button_ReplaceS32", "替換 S32" },
            { "Button_Details", "詳細" },
            { "Button_ClearCell", "清格" },
            { "Button_CheckL1", "查L1" },
            { "Button_ClearL2", "清L2" },
            { "Button_CheckL4", "查L4" },
            { "Button_CheckL5", "查L5" },
            { "Button_CheckL6", "查L6" },
            { "Button_CheckL7", "查L7" },
            { "Button_CheckL8", "查L8" },
            { "Button_More", "更多..." },
            { "Button_ShowAll", "全部" },

            // === Labels - Tile Panel ===
            { "Label_TileList", "Tile 列表" },
            { "Label_TileListCount", "Tile 列表 ({0})" },
            { "Label_RecentMaterials", "最近的素材" },
            { "Label_GroupThumbnails", "群組縮圖列表" },
            { "Label_GroupThumbnailsCount", "群組縮圖列表 ({0})" },
            { "Label_GroupThumbnailsLoading", "群組縮圖列表 (載入中 {0}/{1})" },
            { "Label_GroupThumbnailsTime", "群組縮圖列表 ({0}) [{1}ms]" },
            { "Label_NearbyGroups", "附近群組" },
            { "Label_NearbyGroupsCount", "附近群組 ({0})" },
            { "Label_NearbyGroupsLoading", "附近群組 ({0}, L5:{1}) 載入中..." },
            { "Label_NearbyGroupsTime", "附近群組 ({0}) [{1}ms]" },
            { "Label_SelectedAreaGroups", "選取區域群組" },
            { "Label_SelectedAreaGroupsCount", "選取區域群組 ({0})" },
            { "Placeholder_SearchTileId", "搜尋 TileId..." },
            { "Label_SearchResult", "搜尋結果" },

            // === Buttons - Form1 (Monster Tool) ===
            { "Button_Connect", "連線" },
            { "Button_AddToDatabase", "加入資料庫" },
            { "Button_ReloadMap", "重新載入當前地圖" },
            { "Button_ShowAllMonsters", "顯示所有怪物位置" },
            { "Button_AddSpawn", "新增" },
            { "Button_CopySpawn", "複製" },
            { "Button_DeleteSpawn", "刪除" },
            { "Button_TestConnection", "測試連線" },

            // === Labels - Common ===
            { "Label_Name", "名稱" },
            { "Label_ID", "ID" },
            { "Label_Count", "數量" },
            { "Label_Note", "備註" },

            // === Labels - MapForm ===
            { "Label_MapId", "地圖 ID" },
            { "Label_GameCoord", "遊戲座標" },
            { "Label_WorldCoord", "世界座標" },
            { "Label_Layer1Coord", "Layer1 座標" },
            { "Label_Zoom", "縮放" },
            { "Label_S32Files", "S32 檔案" },

            // === Labels - Form1 (Monster Tool) ===
            { "Label_ExpectedAdd", "預計新增" },
            { "Label_CenterX", "X心座標" },
            { "Label_CenterY", "Y心座標" },
            { "Label_Radius", "半径" },
            { "Label_RespawnMin", "重生時間(Min)" },
            { "Label_RespawnMax", "重生時間(Max)" },
            { "Label_SpawnInScreen", "畫面內是否生怪" },
            { "Label_TeleportDistance", "瞬移回原地(距離)" },
            { "Label_MonsterID", "怪物ID" },
            { "Label_MonsterNote", "怪物備註" },
            { "Label_MonsterCount", "怪物數量" },

            // === Labels - Database ===
            { "Label_SavedConnections", "已儲存的連線:" },
            { "Label_ConnectionName", "連線名稱:" },
            { "Label_ServerAddress", "伺服器位址:" },
            { "Label_Port", "埠號:" },
            { "Label_Database", "資料庫:" },
            { "Label_Username", "使用者名稱:" },
            { "Label_Password", "密碼:" },
            { "Group_ConnectionInfo", "連線資訊" },

            // === Layer Names ===
            { "Layer_1", "第1層 (地板)" },
            { "Layer_2", "第2層" },
            { "Layer_3", "第3層 (多色屬性)" },
            { "Layer_4", "第4層 (物件)" },
            { "Layer_5", "第5層 (光源)" },
            { "Layer_6", "第6層" },
            { "Layer_7", "第7層 (傳送點)" },
            { "Layer_8", "第8層" },
            { "Layer_Passable", "通行性 (紅藍)" },
            { "Layer_Grid", "顯示格線" },
            { "Layer_S32Border", "S32邊界" },
            { "Layer_CombatArea", "戰鬥區域" },
            { "Layer_Regions", "顯示區域" },

            // === Floating Layer Panel (Short Labels) ===
            { "Label_Layers", "圖層" },
            { "Layer_FloatL1", "L1 地板" },
            { "Layer_FloatL2", "L2" },
            { "Layer_FloatL4", "L4 物件" },
            { "Layer_FloatL5", "L5 透明" },
            { "Layer_FloatPassable", "通行" },
            { "Layer_FloatGrid", "格線" },
            { "Layer_FloatS32Border", "S32邊界" },
            { "Layer_FloatRegions", "戰鬥區域" },

            // === Hints ===
            { "Hint_MouseControls", "滑鼠中鍵拖移 | Ctrl+滾輪縮放 | 左鍵選取格子" },

            // === Tooltips ===
            { "Tooltip_Copy", "複製 (Ctrl+C)" },
            { "Tooltip_Paste", "貼上 (Ctrl+V)" },
            { "Tooltip_Delete", "刪除 (Delete)" },
            { "Tooltip_Undo", "復原 (Ctrl+Z)" },
            { "Tooltip_Redo", "重做 (Ctrl+Y)" },
            { "Tooltip_Save", "儲存 (Ctrl+S)" },
            { "Tooltip_ZoomIn", "放大" },
            { "Tooltip_ZoomOut", "縮小" },
            { "Tooltip_JumpToCoord", "跳轉至遊戲座標" },
            { "Tooltip_NewS32", "新增 S32 區塊" },
            { "Tooltip_ClearLayer7", "清除所有第七層（傳送點）資料" },
            { "Tooltip_ReplaceS32", "替換選取的 S32 區塊" },

            // === Message Box Titles ===
            { "Title_Error", "錯誤" },
            { "Title_Info", "提示" },
            { "Title_Warning", "警告" },
            { "Title_Confirm", "確認" },
            { "Title_Success", "成功" },
            { "Title_SelectMap", "選擇地圖" },
            { "Title_SelectFile", "選擇檔案" },
            { "Title_SaveFile", "儲存檔案" },
            { "Title_ImportMode", "選擇匯入模式" },
            { "Title_DangerConfirm", "危險操作確認" },

            // === Messages - Common ===
            { "Message_PleaseLoadMap", "請先載入地圖" },
            { "Message_PleaseSelectMap", "請先選擇地圖" },
            { "Message_PleaseSelectItem", "請先選擇項目" },
            { "Message_SaveSuccess", "儲存成功" },
            { "Message_SaveFailed", "儲存失敗: {0}" },
            { "Message_LoadFailed", "載入失敗: {0}" },
            { "Message_ExportSuccess", "匯出成功" },
            { "Message_ExportFailed", "匯出失敗: {0}" },
            { "Message_ImportSuccess", "匯入成功" },
            { "Message_ImportFailed", "匯入失敗: {0}" },
            { "Message_ConfirmDelete", "確定要刪除嗎？" },
            { "Message_OperationCancelled", "操作已取消" },
            { "Message_InvalidInput", "輸入無效" },
            { "Message_FileNotFound", "找不到檔案: {0}" },
            { "Message_NoDataToExport", "沒有資料可匯出" },

            // === Messages - Import Fs32 to New Map ===
            { "ImportNewMap_Title", "匯入地圖包到新地圖" },
            { "ImportNewMap_SelectFile", "選擇要匯入的 fs32 地圖包" },
            { "ImportNewMap_EnterMapId", "請輸入新地圖編號:" },
            { "ImportNewMap_InvalidMapId", "無效的地圖編號，請輸入數字" },
            { "ImportNewMap_MapExists", "地圖 {0} 已經存在，是否要使用既有的匯入流程？\n\n按「是」將開啟該地圖並匯入地圖包\n按「否」取消操作" },
            { "ImportNewMap_CreatingFolder", "正在建立地圖資料夾..." },
            { "ImportNewMap_FolderCreated", "已建立地圖資料夾: {0}" },
            { "ImportNewMap_Importing", "正在匯入地圖包..." },
            { "ImportNewMap_Success", "地圖包已成功匯入到新地圖 {0}" },
            { "ImportNewMap_Failed", "匯入失敗: {0}" },
            { "ImportNewMap_PleaseOpenClient", "請先開啟天堂客戶端" },

            // === Messages - Database ===
            { "Message_PleaseConnectDB", "請先連線到資料庫" },
            { "Message_ConnectionSuccess", "連線成功！" },
            { "Message_ConnectionFailed", "連線失敗: {0}" },
            { "Message_PleaseEnterConnName", "請輸入連線名稱" },
            { "Message_PleaseEnterServer", "請輸入伺服器位址" },
            { "Message_PleaseEnterDatabase", "請輸入資料庫名稱" },
            { "Message_ConnectionSaved", "連線已儲存" },
            { "Message_ConfirmDeleteConnection", "確定要刪除此連線？" },

            // === Messages - Monster Tool ===
            { "Message_PleaseEnterMonsterID", "請輸入怪物 ID" },
            { "Message_InvalidMonsterID", "無效的怪物 ID" },
            { "Message_MonsterAddedToQueue", "已加入待新增佇列" },
            { "Message_SpawnAdded", "重生點已新增" },
            { "Message_SpawnDeleted", "重生點已刪除" },
            { "Message_NoSpawnSelected", "請先選擇重生點" },

            // === Messages - MapForm ===
            { "Message_S32Saved", "S32 已儲存" },
            { "Message_S32SaveFailed", "S32 儲存失敗: {0}" },
            { "Message_CoordsInvalid", "座標格式無效" },
            { "Message_NoS32Selected", "請先選擇 S32 檔案" },
            { "Message_ClipboardEmpty", "剪貼簿是空的" },
            { "Message_CopiedToClipboard", "已複製到剪貼簿" },
            { "Message_ExportedTo", "已成功匯出至: {0}" },

            // === Messages - FS32 Import ===
            { "Message_Fs32Info", "fs32 地圖包資訊：" },
            { "Message_Fs32SourceMap", "來源地圖" },
            { "Message_Fs32BlockCount", "區塊數量" },
            { "Message_Fs32TileCount", "圖塊數量" },
            { "Message_Fs32ImportTo", "將匯入至當前地圖" },
            { "Message_Fs32SelectMode", "請選擇匯入模式：" },
            { "Message_Fs32PartialReplace", "【部份取代】只覆蓋相同座標的區塊（推薦）" },
            { "Message_Fs32FullReplace", "【全部取代】刪除既有區塊，完全使用匯入的地圖" },
            { "Message_Fs32PartialButton", "按「是」= 部份取代（預設）" },
            { "Message_Fs32FullButton", "按「否」= 全部取代" },
            { "Message_Fs32CancelButton", "按「取消」= 取消匯入" },
            { "Message_Fs32FullReplaceWarning", "⚠️ 警告：全部取代模式 ⚠️\n\n這將會刪除當前地圖的所有既有區塊！\n整張地圖可能會消失，只剩下匯入的區塊。\n\n此操作無法復原！\n\n確定要繼續嗎？" },
            { "Message_Fs32ImportComplete", "匯入完成！" },
            { "Message_Fs32ImportMode", "匯入模式" },
            { "Message_Fs32FullReplaceMode", "全部取代" },
            { "Message_Fs32PartialReplaceMode", "部份取代" },
            { "Message_Fs32DeletedBlocks", "已刪除既有區塊" },
            { "Message_Fs32ImportedBlocks", "成功匯入" },
            { "Message_Fs32ImportedTiles", "匯入圖塊" },
            { "Message_Fs32ReusedTiles", "重用圖塊" },
            { "Message_Fs32RemappedTiles", "重新編號" },
            { "Message_Fs32SkippedBlocks", "跳過 {0} 個區塊" },
            { "Message_Fs32InvalidFile", "無效的 fs32 檔案或不包含任何區塊" },
            { "Message_Fs32SelectFile", "選擇要匯入的 fs32 地圖包" },
            { "Message_Fs32Blocks", "個區塊" },
            { "Message_Fs32Tiles", "個" },

            // === Abnormal Check Dialog ===
            { "AbnormalCheck_Title", "異常檢查結果" },
            { "AbnormalCheck_FoundIssues", "發現以下異常：" },
            { "AbnormalCheck_ViewDetails", "是否要查看詳細資訊？" },
            { "AbnormalCheck_Layer5Issues", "• {0} 個 Layer5 項目異常" },
            { "AbnormalCheck_InvalidTileIds", "• {0} 個無效的 TileId ({1})" },
            { "AbnormalCheck_Layer8Extended", "• {0} 個 S32 使用 Layer8 擴展格式（共 {1} 個項目，可能導致閃退）" },
            { "AbnormalCheck_TileOverLimit", "• {0} 個 Tile 超過上限 (上限={1}, 最大={2})，將無法顯示或導致閃退" },
            { "AbnormalCheck_Tab_Layer5", "Layer5 異常 ({0})" },
            { "AbnormalCheck_Tab_InvalidTile", "無效 TileId ({0})" },
            { "AbnormalCheck_Tab_Layer8", "L8 擴展格式 ({0})" },
            { "AbnormalCheck_Tab_OverLimit", "Tile超上限 ({0})" },
            { "AbnormalCheck_Layer5Summary", "以下 {0} 個 Layer5 項目異常（GroupId不存在或周圍一格內無對應物件）：" },
            { "AbnormalCheck_TileSummary", "發現 {0} 個無效 TileId (L1:{1}, L2:{2}, L4:{3})。這些 Tile 檔案不存在或 IndexId 超出範圍：" },
            { "AbnormalCheck_Layer8Summary", "以下 {0} 個 S32 使用 Layer8 擴展格式（共 {1} 個項目）。擴展格式可能導致遊戲閃退：" },
            { "AbnormalCheck_OverLimitSummary", "Tile.idx 中有 {0} 個 Tile ID 超過 list.til 上限 ({1})。\n最大 Tile ID: {2}。這些 Tile 將無法顯示或導致閃退：" },
            { "AbnormalCheck_DeselectAll", "取消全選" },
            { "AbnormalCheck_ClearSelected", "清除勾選" },
            { "AbnormalCheck_ClearAll", "清除全部" },
            { "AbnormalCheck_SelectL1Only", "只選L1" },
            { "AbnormalCheck_SelectL2Only", "只選L2" },
            { "AbnormalCheck_SelectL4Only", "只選L4" },
            { "AbnormalCheck_ResetSelectedFormat", "重設勾選為一般格式" },
            { "AbnormalCheck_ResetAllFormat", "全部重設為一般格式" },
            { "AbnormalCheck_PleaseSelectItems", "請先勾選要清除的項目" },
            { "AbnormalCheck_Notice", "提示" },
            { "AbnormalCheck_ConfirmClearSelected", "確定要清除勾選的 {0} 個項目嗎？" },
            { "AbnormalCheck_ConfirmDelete", "確認刪除" },
            { "AbnormalCheck_ClearedLayer5", "已清除 {0} 個異常的 Layer5 項目" },
            { "AbnormalCheck_ClearComplete", "清除完成" },
            { "AbnormalCheck_ConfirmClearAll", "確定要清除所有 {0} 個異常項目嗎？" },
            { "AbnormalCheck_ConfirmDeleteAll", "確認刪除全部" },
            { "AbnormalCheck_ConfirmClearTiles", "確定要清除勾選的 {0} 個無效 Tile 嗎？\n\n• Layer1: 將 TileId 設為 0\n• Layer2: 移除該項目\n• Layer4: 移除該物件" },
            { "AbnormalCheck_ConfirmClearAllTiles", "確定要清除所有 {0} 個無效 Tile 嗎？\n\n• Layer1: 將 TileId 設為 0\n• Layer2: 移除該項目\n• Layer4: 移除該物件" },
            { "AbnormalCheck_ClearedTiles", "已清除 {0} 個無效 Tile" },
            { "AbnormalCheck_PleaseSelectReset", "請先勾選要重設的項目" },
            { "AbnormalCheck_ConfirmResetSelected", "確定要將勾選的 {0} 個 S32 重設為一般格式嗎？\n\n這會清除這些 S32 所有 Layer8 項目的 ExtendedData。" },
            { "AbnormalCheck_ConfirmReset", "確認重設" },
            { "AbnormalCheck_ResetComplete", "已重設 {0} 個 S32 為一般格式，清除了 {1} 個項目的 ExtendedData。\n\n請記得儲存 S32 檔案。" },
            { "AbnormalCheck_ResetDone", "重設完成" },
            { "AbnormalCheck_ConfirmResetAll", "確定要將所有 {0} 個 S32 重設為一般格式嗎？\n\n這會清除所有 Layer8 項目的 ExtendedData。" },
            { "AbnormalCheck_ConfirmResetAll_Title", "確認重設全部" },
            { "AbnormalCheck_Layer8ItemCount", "[{0}] Layer8 項目數: {1}" },

            // === Status Bar ===
            { "Status_Ready", "就緒" },
            { "Status_Loading", "載入中" },
            { "Status_Collecting", "收集中" },
            { "Status_Saving", "儲存中..." },
            { "Status_Exporting", "匯出中..." },
            { "Status_Importing", "匯入中..." },
            { "Status_DeletingBlocks", "正在刪除既有區塊..." },
            { "Status_ImportingBlocks", "正在匯入區塊..." },
            { "Status_LoadingFs32", "正在載入 fs32..." },
            { "Status_ReloadingMap", "正在重新載入地圖..." },
            { "Status_ImportedBlocks", "已匯入 {0} 個區塊" },
            { "Status_Coordinates", "座標: X={0}, Y={1}" },
            { "Status_MapLoaded", "地圖已載入: {0}" },

            // === Form Titles ===
            { "Form_MapEditor_Title", "地圖編輯器" },
            { "Form_MonsterTool_Title", "怪物設定工具" },
            { "Form_DatabaseConnection_Title", "資料庫連線管理" },
            { "Form_MonsterSearch_Title", "搜尋怪物" },
            { "Form_ExportOptions_Title", "匯出選項" },
            { "Form_CopySettings_Title", "複製設定" },
            { "Form_MaterialBrowser_Title", "素材庫瀏覽器" },

            // === Export Options ===
            { "Export_Mode_SelectedArea", "選取區域" },
            { "Export_Mode_FullMap", "整張地圖" },
            { "Export_SelectLayers", "選擇要匯出的圖層" },
            { "Export_MaterialName", "素材名稱" },

            // === Copy Settings Dialog ===
            { "CopySettings_Layer1_Desc", "Layer 1 (地板)" },
            { "CopySettings_Layer2_Desc", "Layer 2 (裝飾)" },
            { "CopySettings_Layer3_Desc", "Layer 3 (屬性)" },
            { "CopySettings_Layer4_Desc", "Layer 4 (物件)" },
            { "CopySettings_Layer5_Desc", "Layer 5 (光源)" },
            { "CopySettings_Layer6to8_Desc", "Layer 6-8 (其他)" },

            // === Material Browser ===
            { "Material_Search", "搜尋素材" },
            { "Material_ChangePath", "變更路徑" },
            { "Material_UseThis", "使用此素材" },
            { "Material_OpenFolder", "開啟所在資料夾" },
            { "Material_Preview", "預覽" },
            { "Material_NoPreview", "無法預覽" },

            // === File Filters ===
            { "Filter_AllFiles", "所有檔案" },
            { "Filter_S32Files", "S32 檔案" },
            { "Filter_Fs32Files", "FS32 地圖包" },
            { "Filter_ImageFiles", "圖片檔案" },
            { "Filter_JsonFiles", "JSON 檔案" },

            // === Additional Dialog Strings ===
            { "Message_SelectAtLeastOneLayer", "請至少選擇一個圖層" },
            { "CopySettings_SelectLayers", "選擇要複製/刪除的圖層：" },

            // === Export Options Dialog ===
            { "Export_SaveAsMaterial", "儲存為素材" },
            { "Export_Mode", "匯出模式" },
            { "Export_WholeMap", "整張地圖" },
            { "Export_SelectedBlocks", "選取的區塊" },
            { "Export_SelectedRegion", "選取的區域 (精確範圍)" },
            { "Export_IncludeLayers", "包含圖層" },
            { "Export_Layer1", "Layer1 地板" },
            { "Export_Layer2", "Layer2 裝飾" },
            { "Export_Layer3", "Layer3 屬性" },
            { "Export_Layer4", "Layer4 物件" },
            { "Export_IncludeTiles", "包含 Tile 資料" },
            { "Export_IncludeLayer5Events", "包含 Layer5 事件 (隨 Layer4 物件)" },
            { "Export_Export", "匯出" },

            // === Material Browser Additional ===
            { "Material_OpenFile", "開啟檔案..." },
            { "Material_Use", "使用" },
            { "Material_Library", "素材庫" },
            { "Material_Items", "個素材" },

            // === Misc ===
            { "Misc_Yes", "是" },
            { "Misc_No", "否" },
            { "Misc_Unit_Blocks", "個區塊" },
            { "Misc_Unit_Tiles", "個圖塊" },
            { "Misc_Unit_Pixels", "像素" },
            { "Misc_Unknown", "未知" },
            { "Misc_None", "無" },
        };
    }
}
