using System.Collections.Generic;

namespace L1MapViewer.Localization
{
    /// <summary>
    /// Korean (ko-KR) string resources
    /// </summary>
    public static class Strings_koKR
    {
        public static Dictionary<string, string> GetStrings() => new()
        {
            // === Menu Items ===
            { "Menu_File", "파일" },
            { "Menu_File_OpenClient", "리니지 클라이언트를 열어 맵 읽기" },
            { "Menu_File_Export", "맵 통행 데이터 내보내기" },
            { "Menu_Import", "가져오기" },
            { "Menu_Import_Material", "소재 가져오기..." },
            { "Menu_Import_Fs32ToNewMap", "맵 패키지를 새 맵으로 가져오기..." },
            { "Menu_Database", "데이터베이스 설정" },
            { "Menu_MapEditor", "맵 에디터" },
            { "Menu_Help_Discord", "Discord에서 토론하기" },
            { "Menu_Help_About", "정보" },
            { "Menu_Language", "언어" },
            { "Menu_Export_ServerPassability", "서버 통행 데이터 내보내기" },
            { "Menu_Export_L1JFormat", "L1J 형식" },
            { "Menu_Export_DIRFormat", "DIR 형식" },

            // === Tab Pages ===
            { "Tab_MapPreview", "맵 미리보기" },
            { "Tab_S32Editor", "S32 에디터" },
            { "Tab_MapList", "맵 목록" },
            { "Tab_S32Files", "S32 파일" },
            { "Placeholder_SearchMap", "맵 검색 (ID 또는 이름)..." },

            // === Buttons - Common ===
            { "Button_OK", "확인" },
            { "Button_Cancel", "취소" },
            { "Button_Save", "저장" },
            { "Button_Close", "닫기" },
            { "Button_New", "새로 만들기" },
            { "Button_Edit", "편집" },
            { "Button_Delete", "삭제" },
            { "Button_Replace", "교체" },
            { "Button_ClearL7", "L7 지우기" },
            { "Button_Copy", "복사" },
            { "Button_Paste", "붙여넣기" },
            { "Button_Undo", "실행 취소" },
            { "Button_Redo", "다시 실행" },
            { "Button_Search", "검색" },
            { "Button_Refresh", "새로고침" },
            { "Button_Browse", "찾아보기" },
            { "Button_Apply", "적용" },
            { "Button_Reset", "초기화" },

            // === Buttons - MapForm ===
            { "Button_JumpToCoord", "이동" },
            { "Button_ReloadF5", "새로고침 (F5)" },
            { "Button_SaveS32", "S32 저장" },
            { "Button_AnalyzeAttr", "속성 분석" },
            { "Button_SelectAll", "모두 선택" },
            { "Button_SelectNone", "선택 해제" },
            { "Button_CopySettings", "설정 복사" },
            { "Button_CopyMapCoords", "좌표 복사" },
            { "Button_ImportFs32", "맵 팩 가져오기" },
            { "Button_EditPassable", "통행 편집" },
            { "Button_EditLayer5", "투명도 편집" },
            { "Button_RegionEdit", "영역 편집" },
            { "Button_ExportS32", "S32 내보내기" },
            { "Button_NewS32", "새 S32" },
            { "Button_ClearLayer7", "텔레포트 지우기" },
            { "Button_ReplaceS32", "S32 교체" },
            { "Button_Details", "상세" },
            { "Button_ClearCell", "셀 지우기" },
            { "Button_CheckL1", "L1 확인" },
            { "Button_CheckL2", "L2 확인" },
            { "Button_CheckL3", "L3 확인" },
            { "Button_CheckL4", "L4 확인" },
            { "Button_CheckL5", "L5 확인" },
            { "Button_CheckL6", "L6 확인" },
            { "Button_CheckL7", "L7 확인" },
            { "Button_CheckL8", "L8 확인" },
            { "Button_More", "더보기..." },
            { "Button_ShowAll", "전체" },

            // === Labels - Tile Panel ===
            { "Label_TileList", "타일 목록" },
            { "Label_TileListCount", "타일 목록 ({0})" },
            { "Label_RecentMaterials", "최근 소재" },
            { "Label_GroupThumbnails", "그룹 썸네일" },
            { "Label_GroupThumbnailsCount", "그룹 썸네일 ({0})" },
            { "Label_GroupThumbnailsLoading", "그룹 썸네일 (로딩 중 {0}/{1})" },
            { "Label_GroupThumbnailsTime", "그룹 썸네일 ({0}) [{1}ms]" },
            { "Label_NearbyGroups", "주변 그룹" },
            { "Label_NearbyGroupsCount", "주변 그룹 ({0})" },
            { "Label_NearbyGroupsLoading", "주변 그룹 ({0}, L5:{1}) 로딩 중..." },
            { "Label_NearbyGroupsTime", "주변 그룹 ({0}) [{1}ms]" },
            { "Label_SelectedAreaGroups", "선택 영역 그룹" },
            { "Label_SelectedAreaGroupsCount", "선택 영역 그룹 ({0})" },
            { "Label_SelectedAreaAllGroups", "영역-전체" },
            { "Placeholder_SearchTileId", "TileId 검색..." },
            { "Label_SearchResult", "검색 결과" },

            // === Buttons - Form1 (Monster Tool) ===
            { "Button_Connect", "연결" },
            { "Button_AddToDatabase", "데이터베이스에 추가" },
            { "Button_ReloadMap", "현재 맵 새로고침" },
            { "Button_ShowAllMonsters", "모든 몬스터 위치 표시" },
            { "Button_AddSpawn", "추가" },
            { "Button_CopySpawn", "복사" },
            { "Button_DeleteSpawn", "삭제" },
            { "Button_TestConnection", "연결 테스트" },

            // === Labels - Common ===
            { "Label_Name", "이름" },
            { "Label_ID", "ID" },
            { "Label_Count", "수량" },
            { "Label_Note", "메모" },

            // === Labels - MapForm ===
            { "Label_MapId", "맵 ID" },
            { "Label_GameCoord", "게임 좌표" },
            { "Label_WorldCoord", "월드 좌표" },
            { "Label_Layer1Coord", "Layer1 좌표" },
            { "Label_Zoom", "확대/축소" },
            { "Label_S32Files", "S32 파일" },

            // === Labels - Form1 (Monster Tool) ===
            { "Label_ExpectedAdd", "추가 예정" },
            { "Label_CenterX", "중심 X" },
            { "Label_CenterY", "중심 Y" },
            { "Label_Radius", "반경" },
            { "Label_RespawnMin", "리스폰 시간 (최소)" },
            { "Label_RespawnMax", "리스폰 시간 (최대)" },
            { "Label_SpawnInScreen", "화면 내 스폰" },
            { "Label_TeleportDistance", "텔레포트 거리" },
            { "Label_MonsterID", "몬스터 ID" },
            { "Label_MonsterNote", "몬스터 메모" },
            { "Label_MonsterCount", "몬스터 수" },

            // === Labels - Database ===
            { "Label_SavedConnections", "저장된 연결:" },
            { "Label_ConnectionName", "연결 이름:" },
            { "Label_ServerAddress", "서버 주소:" },
            { "Label_Port", "포트:" },
            { "Label_Database", "데이터베이스:" },
            { "Label_Username", "사용자 이름:" },
            { "Label_Password", "비밀번호:" },
            { "Group_ConnectionInfo", "연결 정보" },

            // === Layer Names ===
            { "Layer_1", "레이어 1 (바닥)" },
            { "Layer_2", "레이어 2" },
            { "Layer_3", "레이어 3 (속성)" },
            { "Layer_4", "레이어 4 (오브젝트)" },
            { "Layer_5", "레이어 5 (조명)" },
            { "Layer_6", "레이어 6" },
            { "Layer_7", "레이어 7 (텔레포트)" },
            { "Layer_8", "레이어 8" },
            { "Layer_Passable", "통행성 (빨강/파랑)" },
            { "Layer_Grid", "그리드 표시" },
            { "Layer_S32Border", "S32 경계" },
            { "Layer_CombatArea", "전투 영역" },
            { "Layer_Regions", "영역 표시" },

            // === Floating Layer Panel (Short Labels) ===
            { "Label_Layers", "레이어" },
            { "Layer_FloatL1", "L1 바닥" },
            { "Layer_FloatL2", "L2" },
            { "Layer_FloatL4", "L4 오브젝트" },
            { "Layer_FloatL5", "L5 투명" },
            { "Layer_FloatPassable", "통행" },
            { "Layer_FloatGrid", "그리드" },
            { "Layer_FloatS32Border", "S32 경계" },
            { "Layer_FloatSafeZones", "안전 지역" },
            { "Layer_FloatCombatZones", "전투 지역" },

            // === Hints ===
            { "Hint_MouseControls", "마우스 가운데 버튼으로 드래그 | Ctrl+휠로 확대/축소 | 좌클릭으로 선택" },

            // === Tooltips ===
            { "Tooltip_Copy", "복사 (Ctrl+C)" },
            { "Tooltip_Paste", "붙여넣기 (Ctrl+V)" },
            { "Tooltip_Delete", "삭제 (Delete)" },
            { "Tooltip_Undo", "실행 취소 (Ctrl+Z)" },
            { "Tooltip_Redo", "다시 실행 (Ctrl+Y)" },
            { "Tooltip_Save", "저장 (Ctrl+S)" },
            { "Tooltip_ZoomIn", "확대" },
            { "Tooltip_ZoomOut", "축소" },
            { "Tooltip_JumpToCoord", "게임 좌표로 이동" },
            { "Tooltip_NewS32", "새 S32 블록 추가" },
            { "Tooltip_ClearLayer7", "모든 레이어 7 (텔레포트) 데이터 지우기" },
            { "Tooltip_ReplaceS32", "선택한 S32 블록 교체" },

            // === Message Box Titles ===
            { "Title_Error", "오류" },
            { "Title_Info", "정보" },
            { "Title_Warning", "경고" },
            { "Title_Confirm", "확인" },
            { "Title_Success", "성공" },
            { "Title_SelectMap", "맵 선택" },
            { "Title_SelectFile", "파일 선택" },
            { "Title_SaveFile", "파일 저장" },
            { "Title_ImportMode", "가져오기 모드 선택" },
            { "Title_DangerConfirm", "위험 작업 확인" },

            // === Messages - Common ===
            { "Message_PleaseLoadMap", "먼저 맵을 불러오세요" },
            { "Message_PleaseSelectMap", "먼저 맵을 선택하세요" },
            { "Message_PleaseSelectItem", "먼저 항목을 선택하세요" },
            { "Message_SaveSuccess", "저장 완료" },
            { "Message_SaveFailed", "저장 실패: {0}" },
            { "Message_LoadFailed", "불러오기 실패: {0}" },
            { "Message_ExportSuccess", "내보내기 완료" },
            { "Message_ExportFailed", "내보내기 실패: {0}" },
            { "Message_ImportSuccess", "가져오기 완료" },
            { "Message_ImportFailed", "가져오기 실패: {0}" },
            { "Message_ConfirmDelete", "정말 삭제하시겠습니까?" },
            { "Message_OperationCancelled", "작업이 취소되었습니다" },
            { "Message_InvalidInput", "잘못된 입력" },
            { "Message_FileNotFound", "파일을 찾을 수 없음: {0}" },
            { "Message_NoDataToExport", "내보낼 데이터가 없습니다" },

            // === Messages - Import Fs32 to New Map ===
            { "ImportNewMap_Title", "맵 패키지를 새 맵으로 가져오기" },
            { "ImportNewMap_SelectFile", "가져올 fs32 맵 패키지 선택" },
            { "ImportNewMap_EnterMapId", "새 맵 번호 입력:" },
            { "ImportNewMap_InvalidMapId", "잘못된 맵 번호입니다. 숫자를 입력하세요" },
            { "ImportNewMap_MapExists", "맵 {0}이(가) 이미 존재합니다. 기존 가져오기 흐름을 사용하시겠습니까?\n\n\"예\"를 클릭하면 해당 맵을 열고 패키지를 가져옵니다\n\"아니오\"를 클릭하면 취소합니다" },
            { "ImportNewMap_CreatingFolder", "맵 폴더 생성 중..." },
            { "ImportNewMap_FolderCreated", "맵 폴더 생성됨: {0}" },
            { "ImportNewMap_Importing", "맵 패키지 가져오는 중..." },
            { "ImportNewMap_Success", "맵 패키지가 새 맵 {0}에 성공적으로 가져와졌습니다" },
            { "ImportNewMap_Failed", "가져오기 실패: {0}" },
            { "ImportNewMap_PleaseOpenClient", "먼저 리니지 클라이언트를 열어주세요" },

            // === Messages - Database ===
            { "Message_PleaseConnectDB", "먼저 데이터베이스에 연결하세요" },
            { "Message_ConnectionSuccess", "연결 성공!" },
            { "Message_ConnectionFailed", "연결 실패: {0}" },
            { "Message_PleaseEnterConnName", "연결 이름을 입력하세요" },
            { "Message_PleaseEnterServer", "서버 주소를 입력하세요" },
            { "Message_PleaseEnterDatabase", "데이터베이스 이름을 입력하세요" },
            { "Message_ConnectionSaved", "연결이 저장되었습니다" },
            { "Message_ConfirmDeleteConnection", "이 연결을 삭제하시겠습니까?" },

            // === Messages - Monster Tool ===
            { "Message_PleaseEnterMonsterID", "몬스터 ID를 입력하세요" },
            { "Message_InvalidMonsterID", "잘못된 몬스터 ID" },
            { "Message_MonsterAddedToQueue", "대기열에 추가됨" },
            { "Message_SpawnAdded", "스폰 포인트 추가됨" },
            { "Message_SpawnDeleted", "스폰 포인트 삭제됨" },
            { "Message_NoSpawnSelected", "먼저 스폰 포인트를 선택하세요" },

            // === Messages - MapForm ===
            { "Message_S32Saved", "S32 저장됨" },
            { "Message_S32SaveFailed", "S32 저장 실패: {0}" },
            { "Message_CoordsInvalid", "잘못된 좌표 형식" },
            { "Message_NoS32Selected", "먼저 S32 파일을 선택하세요" },
            { "Message_ClipboardEmpty", "클립보드가 비어 있습니다" },
            { "Message_CopiedToClipboard", "클립보드에 복사됨" },
            { "Message_ExportedTo", "성공적으로 내보내기 완료: {0}" },

            // === Messages - FS32 Import ===
            { "Message_Fs32Info", "fs32 맵 팩 정보:" },
            { "Message_Fs32SourceMap", "소스 맵" },
            { "Message_Fs32BlockCount", "블록 수" },
            { "Message_Fs32TileCount", "타일 수" },
            { "Message_Fs32ImportTo", "현재 맵에 가져오기" },
            { "Message_Fs32SelectMode", "가져오기 모드를 선택하세요:" },
            { "Message_Fs32PartialReplace", "[부분 교체] 동일한 좌표의 블록만 덮어쓰기 (권장)" },
            { "Message_Fs32FullReplace", "[전체 교체] 기존 블록 삭제 후 가져온 맵 사용" },
            { "Message_Fs32PartialButton", "'예' = 부분 교체 (기본값)" },
            { "Message_Fs32FullButton", "'아니오' = 전체 교체" },
            { "Message_Fs32CancelButton", "'취소' = 가져오기 취소" },
            { "Message_Fs32FullReplaceWarning", "⚠️ 경고: 전체 교체 모드 ⚠️\n\n현재 맵의 모든 기존 블록이 삭제됩니다!\n전체 맵이 사라지고 가져온 블록만 남게 됩니다.\n\n이 작업은 취소할 수 없습니다!\n\n계속하시겠습니까?" },
            { "Message_Fs32ImportComplete", "가져오기 완료!" },
            { "Message_Fs32ImportMode", "가져오기 모드" },
            { "Message_Fs32FullReplaceMode", "전체 교체" },
            { "Message_Fs32PartialReplaceMode", "부분 교체" },
            { "Message_Fs32DeletedBlocks", "삭제된 기존 블록" },
            { "Message_Fs32ImportedBlocks", "성공적으로 가져옴" },
            { "Message_Fs32ImportedTiles", "가져온 타일" },
            { "Message_Fs32ReusedTiles", "재사용된 타일" },
            { "Message_Fs32RemappedTiles", "다시 매핑됨" },
            { "Message_Fs32SkippedBlocks", "{0}개 블록 건너뜀" },
            { "Message_Fs32InvalidFile", "잘못된 fs32 파일이거나 블록이 없습니다" },
            { "Message_Fs32SelectFile", "가져올 fs32 맵 팩 선택" },
            { "Message_Fs32Blocks", "개 블록" },
            { "Message_Fs32Tiles", "개 타일" },

            // === Abnormal Check Dialog ===
            { "AbnormalCheck_Title", "비정상 검사 결과" },
            { "AbnormalCheck_FoundIssues", "다음 문제를 발견했습니다:" },
            { "AbnormalCheck_ViewDetails", "상세 정보를 보시겠습니까?" },
            { "AbnormalCheck_Layer5Issues", "• {0}개의 Layer5 항목 비정상" },
            { "AbnormalCheck_InvalidTileIds", "• {0}개의 잘못된 TileId ({1})" },
            { "AbnormalCheck_Layer8Extended", "• {0}개의 S32 파일이 Layer8 확장 형식 사용 (총 {1}개 항목, 충돌 가능성)" },
            { "AbnormalCheck_TileOverLimit", "• {0}개의 타일이 제한 초과 (제한={1}, 최대={2}), 표시 불가 또는 충돌 가능" },
            { "AbnormalCheck_Tab_Layer5", "Layer5 문제 ({0})" },
            { "AbnormalCheck_Tab_InvalidTile", "잘못된 TileId ({0})" },
            { "AbnormalCheck_Tab_Layer8", "L8 확장 ({0})" },
            { "AbnormalCheck_Tab_OverLimit", "타일 제한 초과 ({0})" },
            { "AbnormalCheck_Layer5Summary", "다음 {0}개의 Layer5 항목이 비정상입니다 (GroupId가 존재하지 않거나 1셀 이내에 일치하는 오브젝트 없음):" },
            { "AbnormalCheck_TileSummary", "{0}개의 잘못된 TileId 발견 (L1:{1}, L2:{2}, L4:{3}). 타일 파일이 존재하지 않거나 IndexId가 범위를 벗어남:" },
            { "AbnormalCheck_Layer8Summary", "다음 {0}개의 S32 파일이 Layer8 확장 형식 사용 (총 {1}개 항목). 확장 형식은 게임 충돌을 유발할 수 있음:" },
            { "AbnormalCheck_OverLimitSummary", "Tile.idx에 {0}개의 타일 ID가 list.til 제한({1})을 초과.\n최대 타일 ID: {2}. 이 타일들은 표시 불가 또는 충돌 가능:" },
            { "AbnormalCheck_DeselectAll", "전체 선택 해제" },
            { "AbnormalCheck_ClearSelected", "선택 항목 지우기" },
            { "AbnormalCheck_ClearAll", "전체 지우기" },
            { "AbnormalCheck_SelectL1Only", "L1만 선택" },
            { "AbnormalCheck_SelectL2Only", "L2만 선택" },
            { "AbnormalCheck_SelectL4Only", "L4만 선택" },
            { "AbnormalCheck_ResetSelectedFormat", "선택 항목을 일반 형식으로 재설정" },
            { "AbnormalCheck_ResetAllFormat", "전체를 일반 형식으로 재설정" },
            { "AbnormalCheck_PleaseSelectItems", "먼저 지울 항목을 선택하세요" },
            { "AbnormalCheck_Notice", "알림" },
            { "AbnormalCheck_ConfirmClearSelected", "선택한 {0}개 항목을 지우시겠습니까?" },
            { "AbnormalCheck_ConfirmDelete", "삭제 확인" },
            { "AbnormalCheck_ClearedLayer5", "{0}개의 비정상 Layer5 항목을 지웠습니다" },
            { "AbnormalCheck_ClearComplete", "지우기 완료" },
            { "AbnormalCheck_ConfirmClearAll", "모든 {0}개의 비정상 항목을 지우시겠습니까?" },
            { "AbnormalCheck_ConfirmDeleteAll", "전체 삭제 확인" },
            { "AbnormalCheck_ConfirmClearTiles", "선택한 {0}개의 잘못된 타일을 지우시겠습니까?\n\n• Layer1: TileId를 0으로 설정\n• Layer2: 항목 제거\n• Layer4: 오브젝트 제거" },
            { "AbnormalCheck_ConfirmClearAllTiles", "모든 {0}개의 잘못된 타일을 지우시겠습니까?\n\n• Layer1: TileId를 0으로 설정\n• Layer2: 항목 제거\n• Layer4: 오브젝트 제거" },
            { "AbnormalCheck_ClearedTiles", "{0}개의 잘못된 타일을 지웠습니다" },
            { "AbnormalCheck_PleaseSelectReset", "먼저 재설정할 항목을 선택하세요" },
            { "AbnormalCheck_ConfirmResetSelected", "선택한 {0}개의 S32를 일반 형식으로 재설정하시겠습니까?\n\n이 S32의 모든 Layer8 항목에서 ExtendedData가 지워집니다." },
            { "AbnormalCheck_ConfirmReset", "재설정 확인" },
            { "AbnormalCheck_ResetComplete", "{0}개의 S32 파일을 일반 형식으로 재설정하고, {1}개 항목의 ExtendedData를 지웠습니다.\n\nS32 파일을 저장하는 것을 잊지 마세요." },
            { "AbnormalCheck_ResetDone", "재설정 완료" },
            { "AbnormalCheck_ConfirmResetAll", "모든 {0}개의 S32를 일반 형식으로 재설정하시겠습니까?\n\n모든 Layer8 항목의 ExtendedData가 지워집니다." },
            { "AbnormalCheck_ConfirmResetAll_Title", "전체 재설정 확인" },
            { "AbnormalCheck_Layer8ItemCount", "[{0}] Layer8 항목: {1}" },

            // === Status Bar ===
            { "Status_Ready", "준비" },
            { "Status_Loading", "로딩 중..." },
            { "Status_Collecting", "수집 중" },
            { "Status_Saving", "저장 중..." },
            { "Status_Exporting", "내보내는 중..." },
            { "Status_Importing", "가져오는 중..." },
            { "Status_DeletingBlocks", "기존 블록 삭제 중..." },
            { "Status_ImportingBlocks", "블록 가져오는 중..." },
            { "Status_LoadingFs32", "fs32 로딩 중..." },
            { "Status_ReloadingMap", "맵 새로고침 중..." },
            { "Status_ImportedBlocks", "{0}개 블록 가져옴" },
            { "Status_Coordinates", "좌표: X={0}, Y={1}" },
            { "Status_MapLoaded", "맵 로드됨: {0}" },

            // === Form Titles ===
            { "Form_MapEditor_Title", "맵 에디터" },
            { "Form_MonsterTool_Title", "몬스터 설정 도구" },
            { "Form_DatabaseConnection_Title", "데이터베이스 연결 관리자" },
            { "Form_MonsterSearch_Title", "몬스터 검색" },
            { "Form_ExportOptions_Title", "내보내기 옵션" },
            { "Form_CopySettings_Title", "설정 복사" },
            { "Form_MaterialBrowser_Title", "소재 브라우저" },

            // === Export Options ===
            { "Export_Mode_SelectedArea", "선택 영역" },
            { "Export_Mode_FullMap", "전체 맵" },
            { "Export_SelectLayers", "내보낼 레이어 선택" },
            { "Export_MaterialName", "소재 이름" },

            // === Copy Settings Dialog ===
            { "CopySettings_Layer1_Desc", "레이어 1 (바닥)" },
            { "CopySettings_Layer2_Desc", "레이어 2 (장식)" },
            { "CopySettings_Layer3_Desc", "레이어 3 (속성)" },
            { "CopySettings_Layer4_Desc", "레이어 4 (오브젝트)" },
            { "CopySettings_Layer5_Desc", "레이어 5 (조명)" },
            { "CopySettings_Layer6to8_Desc", "레이어 6-8 (기타)" },
            { "CopySettings_Layer7_Desc", "레이어 7 (포탈)" },
            { "CopySettings_Layer8_Desc", "레이어 8 (이펙트)" },

            // === Material Browser ===
            { "Material_Search", "소재 검색" },
            { "Material_ChangePath", "경로 변경" },
            { "Material_UseThis", "이 소재 사용" },
            { "Material_OpenFolder", "폴더 열기" },
            { "Material_Preview", "미리보기" },
            { "Material_NoPreview", "미리보기 불가" },

            // === File Filters ===
            { "Filter_AllFiles", "모든 파일" },
            { "Filter_S32Files", "S32 파일" },
            { "Filter_Fs32Files", "FS32 맵 팩" },
            { "Filter_ImageFiles", "이미지 파일" },
            { "Filter_JsonFiles", "JSON 파일" },

            // === Additional Dialog Strings ===
            { "Message_SelectAtLeastOneLayer", "최소 하나의 레이어를 선택하세요" },
            { "CopySettings_SelectLayers", "복사/삭제할 레이어 선택:" },

            // === Export Options Dialog ===
            { "Export_SaveAsMaterial", "소재로 저장" },
            { "Export_Mode", "내보내기 모드" },
            { "Export_WholeMap", "전체 맵" },
            { "Export_SelectedBlocks", "선택된 블록" },
            { "Export_SelectedRegion", "선택된 영역 (정확한 범위)" },
            { "Export_IncludeLayers", "포함할 레이어" },
            { "Export_Layer1", "레이어1 바닥" },
            { "Export_Layer2", "레이어2 장식" },
            { "Export_Layer3", "레이어3 속성" },
            { "Export_Layer4", "레이어4 오브젝트" },
            { "Export_IncludeTiles", "타일 데이터 포함" },
            { "Export_IncludeLayer5Events", "Layer5 이벤트 포함 (Layer4 오브젝트 포함)" },
            { "Export_StripLayer8Ext", "Layer8 확장 데이터 제거" },
            { "Export_Export", "내보내기" },

            // === Material Browser Additional ===
            { "Material_OpenFile", "파일 열기..." },
            { "Material_Use", "사용" },
            { "Material_Library", "소재 라이브러리" },
            { "Material_Items", "개 소재" },

            // === Misc ===
            { "Misc_Yes", "예" },
            { "Misc_No", "아니오" },
            { "Misc_Unit_Blocks", "개 블록" },
            { "Misc_Unit_Tiles", "개 타일" },
            { "Misc_Unit_Pixels", "픽셀" },
            { "Misc_Unknown", "알 수 없음" },
            { "Misc_None", "없음" },

            // === About Dialog ===
            { "About_Title", "L1MapViewer 정보" },
            { "About_Version", "버전" },
            { "About_Description", "리니지 맵 에디터 - 리니지 게임 맵 파일 보기 및 편집" },
            { "About_Discord", "Discord 커뮤니티" },
            { "About_GitHub", "GitHub 프로젝트" },
            { "About_DiscordLink", "https://discord.gg/lineage" },
            { "About_GitHubLink", "https://github.com/tony1223/L1MapViewer" },

            // === L8 Dialog ===
            { "L8_Title", "L8 확인, 편집 및 삭제" },
            { "L8_Summary", "선택: {0} S32 / {1} 항목 | 전체: {2} S32 / {3} 항목 | {4} 확장 형식" },
            { "L8_TabAll", "전체 ({0})" },
            { "L8_TabSelected", "선택된 S32 ({0})" },
            { "L8_Preview", "SPR 미리보기" },
            { "L8_SelectToPreview", "미리보려면 항목 선택" },
            { "L8_JumpToLocation", "위치로 이동" },
            { "L8_FilterNoImage", "이미지 없는 항목만 표시" },
            { "L8_ExtendedSettings", "확장 형식 설정" },
            { "L8_ExtendedInfo", "확장 형식은 Layer8 항목에 추가 4바이트 데이터가 포함됨을 의미합니다. S32 파일을 선택한 후 확장 형식 설정을 전환할 수 있습니다:" },
            { "L8_CurrentStatus", "현재: {0}" },
            { "L8_NotSelected", "선택 안 됨" },
            { "L8_ExtendedFormat", "확장 형식" },
            { "L8_NormalFormat", "일반 형식" },
            { "L8_SetExtended", "확장으로 설정" },
            { "L8_SetNormal", "일반으로 설정" },
            { "L8_ResetAll", "모두 일반으로 재설정" },
            { "L8_SetExtendedDone", "{0}을(를) 확장 형식으로 설정했습니다.\nS32 파일을 저장하세요." },
            { "L8_SetNormalDone", "{0}을(를) 일반 형식으로 설정하고 {1}개 항목의 ExtendedData를 지웠습니다.\nS32 파일을 저장하세요." },
            { "L8_NoExtendedFiles", "확장 형식을 사용하는 S32 파일이 없습니다." },
            { "L8_ConfirmResetAll", "모든 {0}개 S32 파일의 Layer8을 일반 형식으로 재설정하시겠습니까?\n\n주의: 모든 ExtendedData 필드가 지워집니다." },
            { "L8_ConfirmResetTitle", "재설정 확인" },
            { "L8_ResetAllDone", "{0}개 S32 파일을 일반 형식으로 재설정하고 {1}개 항목의 ExtendedData를 지웠습니다.\nS32 파일을 저장하세요." },
            { "L8_Column_File", "S32 파일" },
            { "L8_Column_Extended", "확장" },
            { "L8_Column_SprId", "SprId" },
            { "L8_Column_Preview", "미리보기" },
            { "L8_Column_X", "X" },
            { "L8_Column_Y", "Y" },
            { "L8_Column_ExtData", "ExtData" },
            { "L8_Yes", "예" },
            { "L8_JumpedToLocation", "L8 항목 위치로 이동 ({0}, {1}) - SprId: {2}" },
            { "L8_ShowAllL8", "전체 L8 표시" },
            { "L8_EnabledCount", "{0}개의 L8 효과 활성화 (총 {1}개)" },

            // L8 편집 섹션
            { "L8_EditSection", "선택 항목 편집" },
            { "L8_ApplyEdit", "적용" },
            { "L8_AddNew", "추가" },
            { "L8_SelectS32File", "S32 파일 선택" },
            { "L8_SelectS32ForNewItem", "Layer8 항목을 추가할 S32 파일 선택:" },
            { "L8_NoImageCount", "이미지 없음: {0}개 SPR" },

            // L8 일괄 교체
            { "L8_BatchReplace", "SprId 일괄 교체" },
            { "L8_FromSprId", "원본 SprId:" },
            { "L8_ToSprId", "대상:" },
            { "L8_BatchReplaceBtn", "교체" },
            { "L8_AffectsAllS32", "(전체 S32 영향)" },

            // L8 버튼
            { "L8_SelectAll", "전체 선택" },
            { "L8_DeselectAll", "선택 해제" },
            { "L8_DeleteChecked", "선택 항목 삭제" },
            { "L8_DeleteAll", "전체 L8 삭제" },
            { "L8_Close", "닫기" },

            // L8 메시지 대화 상자
            { "L8_SelectOneToEdit", "편집할 항목을 하나 선택하세요" },
            { "L8_InvalidValue", "유효한 값을 입력하세요" },
            { "L8_EditApplied", "변경이 적용되었습니다. S32 파일을 저장하세요." },
            { "L8_ItemAdded", "Layer8 항목이 {0}에 추가되었습니다.\n\nS32 파일을 저장하세요." },
            { "L8_InvalidSprId", "유효한 SprId 값을 입력하세요" },
            { "L8_SameSprId", "원본과 대상 SprId가 동일합니다" },
            { "L8_SprIdNotFound", "SprId = {0} 항목을 찾을 수 없습니다" },
            { "L8_ConfirmBatchReplace", "SprId = {0}인 모든 항목 ({1}개)을 SprId = {2}로 교체하시겠습니까?" },
            { "L8_ConfirmBatchReplaceTitle", "일괄 교체 확인" },
            { "L8_BatchReplaceComplete", "{0}개 항목의 SprId를 {1}에서 {2}로 교체했습니다.\n{3}개의 S32 파일에 영향.\n\nS32 파일을 저장하세요." },
            { "L8_BatchReplaceCompleteTitle", "일괄 교체 완료" },
            { "L8_SelectToDelete", "삭제할 항목을 먼저 선택하세요" },
            { "L8_ConfirmDeleteChecked", "선택한 {0}개의 Layer8 항목을 삭제하시겠습니까?" },
            { "L8_ConfirmDeleteTitle", "삭제 확인" },
            { "L8_DeleteComplete", "{0}개의 Layer8 항목이 삭제되었습니다.\n\nS32 파일을 저장하세요." },
            { "L8_ConfirmDeleteAll", "전체 {0}개의 Layer8 항목을 삭제하시겠습니까?" },
            { "L8_ConfirmDeleteAllTitle", "전체 삭제 확인" },

            // 공통 제목
            { "Title_Done", "완료" },
            { "Common_OK", "확인" },

            // 일괄 타일 삭제
            { "Form_BatchDeleteTile_Title", "일괄 타일 삭제" },
            { "Menu_BatchDeleteTile", "일괄 타일 삭제..." },
            { "BatchDeleteTile_TileIdRange", "TileId 범위" },
            { "BatchDeleteTile_IndexIdRange", "IndexId 범위" },
            { "BatchDeleteTile_Start", "시작" },
            { "BatchDeleteTile_End", "끝" },
            { "BatchDeleteTile_Scope", "처리 범위" },
            { "BatchDeleteTile_CurrentMap", "현재 맵" },
            { "BatchDeleteTile_AllMaps", "모든 맵 (maps 폴더)" },
            { "BatchDeleteTile_Warning", "S32 파일을 직접 수정합니다. 먼저 백업하세요!" },
            { "BatchDeleteTile_InvalidTileIdRange", "TileId 시작 값이 끝 값보다 클 수 없습니다" },
            { "BatchDeleteTile_InvalidIndexIdRange", "IndexId 시작 값이 끝 값보다 클 수 없습니다" },
            { "BatchDeleteTile_ConfirmMessage", "다음 조건과 일치하는 타일을 삭제하시겠습니까?\n\nTileId: {0} ~ {1}\nIndexId: {2} ~ {3}\n범위: {4}\n\n이 작업은 취소할 수 없습니다!" },
            { "BatchDeleteTile_Confirm", "삭제 확인" },
            { "BatchDeleteTile_NoClient", "먼저 리니지 클라이언트를 여세요!" },
            { "BatchDeleteTile_NoMapLoaded", "먼저 맵을 로드하세요!" },
            { "BatchDeleteTile_NoS32Files", "처리할 S32 파일을 찾을 수 없습니다" },
            { "BatchDeleteTile_Processing", "{0} 처리 중 ({1}/{2})..." },
            { "BatchDeleteTile_Result", "삭제 완료!\n\n삭제됨: {0}\n수정된 파일: {1}\n실패한 파일: {2}" },
            { "BatchDeleteTile_Complete", "일괄 삭제 완료" },
        };
    }
}
