using System.Collections.Generic;

namespace L1MapViewer.Localization
{
    /// <summary>
    /// English (en-US) string resources
    /// </summary>
    public static class Strings_enUS
    {
        public static Dictionary<string, string> GetStrings() => new()
        {
            // === Menu Items ===
            { "Menu_File", "File" },
            { "Menu_File_OpenClient", "Open Lineage Client to Read Map" },
            { "Menu_File_Export", "Export Map Passability Data" },
            { "Menu_Import", "Import" },
            { "Menu_Import_Material", "Import Material..." },
            { "Menu_Import_Fs32ToNewMap", "Import Map Package to New Map..." },
            { "Menu_Database", "Database Settings" },
            { "Menu_MapEditor", "Map Editor" },
            { "Menu_Help_Discord", "Discuss on Discord" },
            { "Menu_Language", "Language" },
            { "Menu_Export_ServerPassability", "Export Server Passability" },
            { "Menu_Export_L1JFormat", "L1J Format" },
            { "Menu_Export_DIRFormat", "DIR Format" },

            // === Tab Pages ===
            { "Tab_MapPreview", "Map Preview" },
            { "Tab_S32Editor", "S32 Editor" },
            { "Tab_MapList", "Map List" },
            { "Tab_S32Files", "S32 Files" },
            { "Placeholder_SearchMap", "Search map (ID or name)..." },

            // === Buttons - Common ===
            { "Button_OK", "OK" },
            { "Button_Cancel", "Cancel" },
            { "Button_Save", "Save" },
            { "Button_Close", "Close" },
            { "Button_New", "New" },
            { "Button_Edit", "Edit" },
            { "Button_Delete", "Delete" },
            { "Button_Replace", "Replace" },
            { "Button_ClearL7", "Clear L7" },
            { "Button_Copy", "Copy" },
            { "Button_Paste", "Paste" },
            { "Button_Undo", "Undo" },
            { "Button_Redo", "Redo" },
            { "Button_Search", "Search" },
            { "Button_Refresh", "Refresh" },
            { "Button_Browse", "Browse" },
            { "Button_Apply", "Apply" },
            { "Button_Reset", "Reset" },

            // === Buttons - MapForm ===
            { "Button_JumpToCoord", "Jump" },
            { "Button_ReloadF5", "Reload (F5)" },
            { "Button_SaveS32", "Save S32" },
            { "Button_AnalyzeAttr", "Analyze Attr" },
            { "Button_SelectAll", "Select All" },
            { "Button_SelectNone", "Select None" },
            { "Button_CopySettings", "Copy Settings" },
            { "Button_CopyMapCoords", "Copy Coordinates" },
            { "Button_ImportFs32", "Import Map Pack" },
            { "Button_SetPassable", "Set Passable" },
            { "Button_SetImpassable", "Set Impassable" },
            { "Button_EditLayer5", "Edit Transparency" },
            { "Button_RegionEdit", "Region Edit" },
            { "Button_ExportS32", "Export S32" },
            { "Button_NewS32", "New S32" },
            { "Button_ClearLayer7", "Clear Teleports" },
            { "Button_ReplaceS32", "Replace S32" },
            { "Button_Details", "Details" },
            { "Button_ClearCell", "Clear Cell" },
            { "Button_CheckL1", "Check L1" },
            { "Button_ClearL2", "Clear L2" },
            { "Button_CheckL4", "Check L4" },
            { "Button_CheckL5", "Check L5" },
            { "Button_CheckL6", "Check L6" },
            { "Button_CheckL7", "Check L7" },
            { "Button_CheckL8", "Check L8" },
            { "Button_More", "More..." },
            { "Button_ShowAll", "All" },

            // === Labels - Tile Panel ===
            { "Label_TileList", "Tile List" },
            { "Label_TileListCount", "Tile List ({0})" },
            { "Label_RecentMaterials", "Recent Materials" },
            { "Label_GroupThumbnails", "Group Thumbnails" },
            { "Label_GroupThumbnailsCount", "Group Thumbnails ({0})" },
            { "Label_GroupThumbnailsLoading", "Group Thumbnails (Loading {0}/{1})" },
            { "Label_GroupThumbnailsTime", "Group Thumbnails ({0}) [{1}ms]" },
            { "Label_NearbyGroups", "Nearby Groups" },
            { "Label_NearbyGroupsCount", "Nearby Groups ({0})" },
            { "Label_NearbyGroupsLoading", "Nearby Groups ({0}, L5:{1}) Loading..." },
            { "Label_NearbyGroupsTime", "Nearby Groups ({0}) [{1}ms]" },
            { "Label_SelectedAreaGroups", "Selected Area Groups" },
            { "Label_SelectedAreaGroupsCount", "Selected Area Groups ({0})" },
            { "Placeholder_SearchTileId", "Search TileId..." },
            { "Label_SearchResult", "Search Results" },

            // === Buttons - Form1 (Monster Tool) ===
            { "Button_Connect", "Connect" },
            { "Button_AddToDatabase", "Add to Database" },
            { "Button_ReloadMap", "Reload Current Map" },
            { "Button_ShowAllMonsters", "Show All Monster Positions" },
            { "Button_AddSpawn", "Add" },
            { "Button_CopySpawn", "Copy" },
            { "Button_DeleteSpawn", "Delete" },
            { "Button_TestConnection", "Test Connection" },

            // === Labels - Common ===
            { "Label_Name", "Name" },
            { "Label_ID", "ID" },
            { "Label_Count", "Count" },
            { "Label_Note", "Note" },

            // === Labels - MapForm ===
            { "Label_MapId", "Map ID" },
            { "Label_GameCoord", "Game Coordinates" },
            { "Label_WorldCoord", "World Coordinates" },
            { "Label_Layer1Coord", "Layer1 Coordinates" },
            { "Label_Zoom", "Zoom" },
            { "Label_S32Files", "S32 Files" },

            // === Labels - Form1 (Monster Tool) ===
            { "Label_ExpectedAdd", "Expected Add" },
            { "Label_CenterX", "Center X" },
            { "Label_CenterY", "Center Y" },
            { "Label_Radius", "Radius" },
            { "Label_RespawnMin", "Respawn Time (Min)" },
            { "Label_RespawnMax", "Respawn Time (Max)" },
            { "Label_SpawnInScreen", "Spawn In Screen" },
            { "Label_TeleportDistance", "Teleport Distance" },
            { "Label_MonsterID", "Monster ID" },
            { "Label_MonsterNote", "Monster Note" },
            { "Label_MonsterCount", "Monster Count" },

            // === Labels - Database ===
            { "Label_SavedConnections", "Saved Connections:" },
            { "Label_ConnectionName", "Connection Name:" },
            { "Label_ServerAddress", "Server Address:" },
            { "Label_Port", "Port:" },
            { "Label_Database", "Database:" },
            { "Label_Username", "Username:" },
            { "Label_Password", "Password:" },
            { "Group_ConnectionInfo", "Connection Info" },

            // === Layer Names ===
            { "Layer_1", "Layer 1 (Floor)" },
            { "Layer_2", "Layer 2" },
            { "Layer_3", "Layer 3 (Attributes)" },
            { "Layer_4", "Layer 4 (Objects)" },
            { "Layer_5", "Layer 5 (Lighting)" },
            { "Layer_6", "Layer 6" },
            { "Layer_7", "Layer 7 (Teleports)" },
            { "Layer_8", "Layer 8" },
            { "Layer_Passable", "Passability (Red/Blue)" },
            { "Layer_Grid", "Show Grid" },
            { "Layer_S32Border", "S32 Borders" },
            { "Layer_CombatArea", "Combat Area" },
            { "Layer_Regions", "Show Regions" },

            // === Floating Layer Panel (Short Labels) ===
            { "Label_Layers", "Layers" },
            { "Layer_FloatL1", "L1 Floor" },
            { "Layer_FloatL2", "L2" },
            { "Layer_FloatL4", "L4 Objects" },
            { "Layer_FloatL5", "L5 Transp" },
            { "Layer_FloatPassable", "Pass" },
            { "Layer_FloatGrid", "Grid" },
            { "Layer_FloatS32Border", "S32 Border" },
            { "Layer_FloatRegions", "Combat" },

            // === Hints ===
            { "Hint_MouseControls", "Middle-click to drag | Ctrl+Scroll to zoom | Left-click to select" },

            // === Tooltips ===
            { "Tooltip_Copy", "Copy (Ctrl+C)" },
            { "Tooltip_Paste", "Paste (Ctrl+V)" },
            { "Tooltip_Delete", "Delete (Delete)" },
            { "Tooltip_Undo", "Undo (Ctrl+Z)" },
            { "Tooltip_Redo", "Redo (Ctrl+Y)" },
            { "Tooltip_Save", "Save (Ctrl+S)" },
            { "Tooltip_ZoomIn", "Zoom In" },
            { "Tooltip_ZoomOut", "Zoom Out" },
            { "Tooltip_JumpToCoord", "Jump to Game Coordinates" },
            { "Tooltip_NewS32", "Add New S32 Block" },
            { "Tooltip_ClearLayer7", "Clear All Layer 7 (Teleport) Data" },
            { "Tooltip_ReplaceS32", "Replace Selected S32 Block" },

            // === Message Box Titles ===
            { "Title_Error", "Error" },
            { "Title_Info", "Information" },
            { "Title_Warning", "Warning" },
            { "Title_Confirm", "Confirm" },
            { "Title_Success", "Success" },
            { "Title_SelectMap", "Select Map" },
            { "Title_SelectFile", "Select File" },
            { "Title_SaveFile", "Save File" },
            { "Title_ImportMode", "Select Import Mode" },
            { "Title_DangerConfirm", "Dangerous Operation Confirmation" },

            // === Messages - Common ===
            { "Message_PleaseLoadMap", "Please load a map first" },
            { "Message_PleaseSelectMap", "Please select a map first" },
            { "Message_PleaseSelectItem", "Please select an item first" },
            { "Message_SaveSuccess", "Saved successfully" },
            { "Message_SaveFailed", "Failed to save: {0}" },
            { "Message_LoadFailed", "Failed to load: {0}" },
            { "Message_ExportSuccess", "Exported successfully" },
            { "Message_ExportFailed", "Failed to export: {0}" },
            { "Message_ImportSuccess", "Imported successfully" },
            { "Message_ImportFailed", "Failed to import: {0}" },
            { "Message_ConfirmDelete", "Are you sure you want to delete?" },
            { "Message_OperationCancelled", "Operation cancelled" },
            { "Message_InvalidInput", "Invalid input" },
            { "Message_FileNotFound", "File not found: {0}" },
            { "Message_NoDataToExport", "No data to export" },

            // === Messages - Import Fs32 to New Map ===
            { "ImportNewMap_Title", "Import Map Package to New Map" },
            { "ImportNewMap_SelectFile", "Select fs32 map package to import" },
            { "ImportNewMap_EnterMapId", "Enter new map number:" },
            { "ImportNewMap_InvalidMapId", "Invalid map number. Please enter a number" },
            { "ImportNewMap_MapExists", "Map {0} already exists. Do you want to use the existing import flow?\n\nClick \"Yes\" to open that map and import the package\nClick \"No\" to cancel" },
            { "ImportNewMap_CreatingFolder", "Creating map folder..." },
            { "ImportNewMap_FolderCreated", "Map folder created: {0}" },
            { "ImportNewMap_Importing", "Importing map package..." },
            { "ImportNewMap_Success", "Map package successfully imported to new map {0}" },
            { "ImportNewMap_Failed", "Import failed: {0}" },
            { "ImportNewMap_PleaseOpenClient", "Please open a Lineage client first" },

            // === Messages - Database ===
            { "Message_PleaseConnectDB", "Please connect to the database first" },
            { "Message_ConnectionSuccess", "Connection successful!" },
            { "Message_ConnectionFailed", "Connection failed: {0}" },
            { "Message_PleaseEnterConnName", "Please enter a connection name" },
            { "Message_PleaseEnterServer", "Please enter a server address" },
            { "Message_PleaseEnterDatabase", "Please enter a database name" },
            { "Message_ConnectionSaved", "Connection saved" },
            { "Message_ConfirmDeleteConnection", "Are you sure you want to delete this connection?" },

            // === Messages - Monster Tool ===
            { "Message_PleaseEnterMonsterID", "Please enter a Monster ID" },
            { "Message_InvalidMonsterID", "Invalid Monster ID" },
            { "Message_MonsterAddedToQueue", "Added to pending queue" },
            { "Message_SpawnAdded", "Spawn point added" },
            { "Message_SpawnDeleted", "Spawn point deleted" },
            { "Message_NoSpawnSelected", "Please select a spawn point first" },

            // === Messages - MapForm ===
            { "Message_S32Saved", "S32 saved" },
            { "Message_S32SaveFailed", "Failed to save S32: {0}" },
            { "Message_CoordsInvalid", "Invalid coordinate format" },
            { "Message_NoS32Selected", "Please select an S32 file first" },
            { "Message_ClipboardEmpty", "Clipboard is empty" },
            { "Message_CopiedToClipboard", "Copied to clipboard" },
            { "Message_ExportedTo", "Successfully exported to: {0}" },

            // === Messages - FS32 Import ===
            { "Message_Fs32Info", "fs32 Map Pack Info:" },
            { "Message_Fs32SourceMap", "Source Map" },
            { "Message_Fs32BlockCount", "Block Count" },
            { "Message_Fs32TileCount", "Tile Count" },
            { "Message_Fs32ImportTo", "Will import to current map" },
            { "Message_Fs32SelectMode", "Please select import mode:" },
            { "Message_Fs32PartialReplace", "[Partial Replace] Only overwrite blocks at same coordinates (Recommended)" },
            { "Message_Fs32FullReplace", "[Full Replace] Delete existing blocks, use imported map entirely" },
            { "Message_Fs32PartialButton", "Press 'Yes' = Partial Replace (Default)" },
            { "Message_Fs32FullButton", "Press 'No' = Full Replace" },
            { "Message_Fs32CancelButton", "Press 'Cancel' = Cancel Import" },
            { "Message_Fs32FullReplaceWarning", "⚠️ Warning: Full Replace Mode ⚠️\n\nThis will delete ALL existing blocks in the current map!\nThe entire map may disappear, leaving only the imported blocks.\n\nThis operation cannot be undone!\n\nAre you sure you want to continue?" },
            { "Message_Fs32ImportComplete", "Import Complete!" },
            { "Message_Fs32ImportMode", "Import Mode" },
            { "Message_Fs32FullReplaceMode", "Full Replace" },
            { "Message_Fs32PartialReplaceMode", "Partial Replace" },
            { "Message_Fs32DeletedBlocks", "Deleted Existing Blocks" },
            { "Message_Fs32ImportedBlocks", "Successfully Imported" },
            { "Message_Fs32ImportedTiles", "Imported Tiles" },
            { "Message_Fs32ReusedTiles", "Reused Tiles" },
            { "Message_Fs32RemappedTiles", "Remapped" },
            { "Message_Fs32SkippedBlocks", "Skipped {0} blocks" },
            { "Message_Fs32InvalidFile", "Invalid fs32 file or contains no blocks" },
            { "Message_Fs32SelectFile", "Select fs32 map pack to import" },
            { "Message_Fs32Blocks", "blocks" },
            { "Message_Fs32Tiles", "tiles" },

            // === Abnormal Check Dialog ===
            { "AbnormalCheck_Title", "Abnormal Check Results" },
            { "AbnormalCheck_FoundIssues", "Found the following issues:" },
            { "AbnormalCheck_ViewDetails", "Do you want to view details?" },
            { "AbnormalCheck_Layer5Issues", "• {0} Layer5 items abnormal" },
            { "AbnormalCheck_InvalidTileIds", "• {0} invalid TileIds ({1})" },
            { "AbnormalCheck_Layer8Extended", "• {0} S32 files use Layer8 extended format ({1} items total, may cause crashes)" },
            { "AbnormalCheck_TileOverLimit", "• {0} Tiles over limit (limit={1}, max={2}), cannot display or may crash" },
            { "AbnormalCheck_Tab_Layer5", "Layer5 Issues ({0})" },
            { "AbnormalCheck_Tab_InvalidTile", "Invalid TileId ({0})" },
            { "AbnormalCheck_Tab_Layer8", "L8 Extended ({0})" },
            { "AbnormalCheck_Tab_OverLimit", "Tile Over Limit ({0})" },
            { "AbnormalCheck_Layer5Summary", "The following {0} Layer5 items are abnormal (GroupId doesn't exist or no matching object within 1 cell):" },
            { "AbnormalCheck_TileSummary", "Found {0} invalid TileIds (L1:{1}, L2:{2}, L4:{3}). Tile file doesn't exist or IndexId out of range:" },
            { "AbnormalCheck_Layer8Summary", "The following {0} S32 files use Layer8 extended format ({1} items total). Extended format may cause game crashes:" },
            { "AbnormalCheck_OverLimitSummary", "Tile.idx has {0} Tile IDs exceeding list.til limit ({1}).\nMax Tile ID: {2}. These Tiles cannot display or may cause crashes:" },
            { "AbnormalCheck_DeselectAll", "Deselect All" },
            { "AbnormalCheck_ClearSelected", "Clear Selected" },
            { "AbnormalCheck_ClearAll", "Clear All" },
            { "AbnormalCheck_SelectL1Only", "L1 Only" },
            { "AbnormalCheck_SelectL2Only", "L2 Only" },
            { "AbnormalCheck_SelectL4Only", "L4 Only" },
            { "AbnormalCheck_ResetSelectedFormat", "Reset Selected to Normal" },
            { "AbnormalCheck_ResetAllFormat", "Reset All to Normal" },
            { "AbnormalCheck_PleaseSelectItems", "Please select items to clear first" },
            { "AbnormalCheck_Notice", "Notice" },
            { "AbnormalCheck_ConfirmClearSelected", "Are you sure you want to clear {0} selected items?" },
            { "AbnormalCheck_ConfirmDelete", "Confirm Delete" },
            { "AbnormalCheck_ClearedLayer5", "Cleared {0} abnormal Layer5 items" },
            { "AbnormalCheck_ClearComplete", "Clear Complete" },
            { "AbnormalCheck_ConfirmClearAll", "Are you sure you want to clear all {0} abnormal items?" },
            { "AbnormalCheck_ConfirmDeleteAll", "Confirm Delete All" },
            { "AbnormalCheck_ConfirmClearTiles", "Are you sure you want to clear {0} selected invalid Tiles?\n\n• Layer1: Set TileId to 0\n• Layer2: Remove item\n• Layer4: Remove object" },
            { "AbnormalCheck_ConfirmClearAllTiles", "Are you sure you want to clear all {0} invalid Tiles?\n\n• Layer1: Set TileId to 0\n• Layer2: Remove item\n• Layer4: Remove object" },
            { "AbnormalCheck_ClearedTiles", "Cleared {0} invalid Tiles" },
            { "AbnormalCheck_PleaseSelectReset", "Please select items to reset first" },
            { "AbnormalCheck_ConfirmResetSelected", "Are you sure you want to reset {0} selected S32 to normal format?\n\nThis will clear ExtendedData from all Layer8 items in these S32." },
            { "AbnormalCheck_ConfirmReset", "Confirm Reset" },
            { "AbnormalCheck_ResetComplete", "Reset {0} S32 files to normal format, cleared ExtendedData from {1} items.\n\nPlease remember to save S32 files." },
            { "AbnormalCheck_ResetDone", "Reset Complete" },
            { "AbnormalCheck_ConfirmResetAll", "Are you sure you want to reset all {0} S32 to normal format?\n\nThis will clear ExtendedData from all Layer8 items." },
            { "AbnormalCheck_ConfirmResetAll_Title", "Confirm Reset All" },
            { "AbnormalCheck_Layer8ItemCount", "[{0}] Layer8 items: {1}" },

            // === Status Bar ===
            { "Status_Ready", "Ready" },
            { "Status_Loading", "Loading..." },
            { "Status_Collecting", "Collecting" },
            { "Status_Saving", "Saving..." },
            { "Status_Exporting", "Exporting..." },
            { "Status_Importing", "Importing..." },
            { "Status_DeletingBlocks", "Deleting existing blocks..." },
            { "Status_ImportingBlocks", "Importing blocks..." },
            { "Status_LoadingFs32", "Loading fs32..." },
            { "Status_ReloadingMap", "Reloading map..." },
            { "Status_ImportedBlocks", "Imported {0} blocks" },
            { "Status_Coordinates", "Coordinates: X={0}, Y={1}" },
            { "Status_MapLoaded", "Map loaded: {0}" },

            // === Form Titles ===
            { "Form_MapEditor_Title", "Map Editor" },
            { "Form_MonsterTool_Title", "Monster Configuration Tool" },
            { "Form_DatabaseConnection_Title", "Database Connection Manager" },
            { "Form_MonsterSearch_Title", "Search Monster" },
            { "Form_ExportOptions_Title", "Export Options" },
            { "Form_CopySettings_Title", "Copy Settings" },
            { "Form_MaterialBrowser_Title", "Material Browser" },

            // === Export Options ===
            { "Export_Mode_SelectedArea", "Selected Area" },
            { "Export_Mode_FullMap", "Full Map" },
            { "Export_SelectLayers", "Select Layers to Export" },
            { "Export_MaterialName", "Material Name" },

            // === Copy Settings Dialog ===
            { "CopySettings_Layer1_Desc", "Layer 1 (Floor)" },
            { "CopySettings_Layer2_Desc", "Layer 2 (Decoration)" },
            { "CopySettings_Layer3_Desc", "Layer 3 (Attributes)" },
            { "CopySettings_Layer4_Desc", "Layer 4 (Objects)" },
            { "CopySettings_Layer5_Desc", "Layer 5 (Lighting)" },
            { "CopySettings_Layer6to8_Desc", "Layer 6-8 (Other)" },

            // === Material Browser ===
            { "Material_Search", "Search Material" },
            { "Material_ChangePath", "Change Path" },
            { "Material_UseThis", "Use This Material" },
            { "Material_OpenFolder", "Open Containing Folder" },
            { "Material_Preview", "Preview" },
            { "Material_NoPreview", "Cannot Preview" },

            // === File Filters ===
            { "Filter_AllFiles", "All Files" },
            { "Filter_S32Files", "S32 Files" },
            { "Filter_Fs32Files", "FS32 Map Pack" },
            { "Filter_ImageFiles", "Image Files" },
            { "Filter_JsonFiles", "JSON Files" },

            // === Additional Dialog Strings ===
            { "Message_SelectAtLeastOneLayer", "Please select at least one layer" },
            { "CopySettings_SelectLayers", "Select layers to copy/delete:" },

            // === Export Options Dialog ===
            { "Export_SaveAsMaterial", "Save as Material" },
            { "Export_Mode", "Export Mode" },
            { "Export_WholeMap", "Whole Map" },
            { "Export_SelectedBlocks", "Selected Blocks" },
            { "Export_SelectedRegion", "Selected Region (Exact Range)" },
            { "Export_IncludeLayers", "Include Layers" },
            { "Export_Layer1", "Layer1 Floor" },
            { "Export_Layer2", "Layer2 Decoration" },
            { "Export_Layer3", "Layer3 Attributes" },
            { "Export_Layer4", "Layer4 Objects" },
            { "Export_IncludeTiles", "Include Tile Data" },
            { "Export_IncludeLayer5Events", "Include Layer5 Events (with Layer4 Objects)" },
            { "Export_Export", "Export" },

            // === Material Browser Additional ===
            { "Material_OpenFile", "Open File..." },
            { "Material_Use", "Use" },
            { "Material_Library", "Material Library" },
            { "Material_Items", "materials" },

            // === Misc ===
            { "Misc_Yes", "Yes" },
            { "Misc_No", "No" },
            { "Misc_Unit_Blocks", "blocks" },
            { "Misc_Unit_Tiles", "tiles" },
            { "Misc_Unit_Pixels", "pixels" },
            { "Misc_Unknown", "Unknown" },
            { "Misc_None", "None" },
        };
    }
}
