using System.Collections.Generic;

namespace L1MapViewer.Localization
{
    /// <summary>
    /// Japanese (ja-JP) string resources
    /// </summary>
    public static class Strings_jaJP
    {
        public static Dictionary<string, string> GetStrings() => new()
        {
            // === Menu Items ===
            { "Menu_File", "ファイル" },
            { "Menu_File_OpenClient", "リネージュクライアントを開いてマップを読み込む" },
            { "Menu_File_Export", "マップ通行データをエクスポート" },
            { "Menu_Import", "インポート" },
            { "Menu_Import_Material", "素材をインポート..." },
            { "Menu_Import_Fs32ToNewMap", "マップパッケージを新規マップにインポート..." },
            { "Menu_Database", "データベース設定" },
            { "Menu_MapEditor", "マップエディタ" },
            { "Menu_Help_Discord", "Discordで議論する" },
            { "Menu_Language", "言語" },
            { "Menu_Export_ServerPassability", "サーバー通行データ出力" },
            { "Menu_Export_L1JFormat", "L1J 形式" },
            { "Menu_Export_DIRFormat", "DIR 形式" },

            // === Tab Pages ===
            { "Tab_MapPreview", "マッププレビュー" },
            { "Tab_S32Editor", "S32エディタ" },
            { "Tab_MapList", "マップリスト" },
            { "Tab_S32Files", "S32ファイル" },
            { "Placeholder_SearchMap", "マップを検索 (ID または名前)..." },

            // === Buttons - Common ===
            { "Button_OK", "OK" },
            { "Button_Cancel", "キャンセル" },
            { "Button_Save", "保存" },
            { "Button_Close", "閉じる" },
            { "Button_New", "新規" },
            { "Button_Edit", "編集" },
            { "Button_Delete", "削除" },
            { "Button_Replace", "置換" },
            { "Button_ClearL7", "L7クリア" },
            { "Button_Copy", "コピー" },
            { "Button_Paste", "貼り付け" },
            { "Button_Undo", "元に戻す" },
            { "Button_Redo", "やり直し" },
            { "Button_Search", "検索" },
            { "Button_Refresh", "更新" },
            { "Button_Browse", "参照" },
            { "Button_Apply", "適用" },
            { "Button_Reset", "リセット" },

            // === Buttons - MapForm ===
            { "Button_JumpToCoord", "移動" },
            { "Button_ReloadF5", "再読み込み (F5)" },
            { "Button_SaveS32", "S32保存" },
            { "Button_AnalyzeAttr", "属性分析" },
            { "Button_SelectAll", "全選択" },
            { "Button_SelectNone", "全解除" },
            { "Button_CopySettings", "設定をコピー" },
            { "Button_CopyMapCoords", "座標をコピー" },
            { "Button_ImportFs32", "マップパックをインポート" },
            { "Button_SetPassable", "通行可能" },
            { "Button_SetImpassable", "通行不可" },
            { "Button_EditLayer5", "半透明編集" },
            { "Button_RegionEdit", "領域編集" },
            { "Button_ExportS32", "S32エクスポート" },
            { "Button_NewS32", "S32新規" },
            { "Button_ClearLayer7", "転送ポイントクリア" },
            { "Button_ReplaceS32", "S32置換" },
            { "Button_Details", "詳細" },
            { "Button_ClearCell", "セルクリア" },
            { "Button_CheckL1", "L1確認" },
            { "Button_ClearL2", "L2クリア" },
            { "Button_CheckL4", "L4確認" },
            { "Button_CheckL5", "L5確認" },
            { "Button_CheckL6", "L6確認" },
            { "Button_CheckL7", "L7確認" },
            { "Button_CheckL8", "L8確認" },
            { "Button_More", "もっと..." },
            { "Button_ShowAll", "全て" },

            // === Labels - Tile Panel ===
            { "Label_TileList", "タイルリスト" },
            { "Label_TileListCount", "タイルリスト ({0})" },
            { "Label_RecentMaterials", "最近の素材" },
            { "Label_GroupThumbnails", "グループサムネイル" },
            { "Label_GroupThumbnailsCount", "グループサムネイル ({0})" },
            { "Label_GroupThumbnailsLoading", "グループサムネイル (読込中 {0}/{1})" },
            { "Label_GroupThumbnailsTime", "グループサムネイル ({0}) [{1}ms]" },
            { "Label_NearbyGroups", "近くのグループ" },
            { "Label_NearbyGroupsCount", "近くのグループ ({0})" },
            { "Label_NearbyGroupsLoading", "近くのグループ ({0}, L5:{1}) 読込中..." },
            { "Label_NearbyGroupsTime", "近くのグループ ({0}) [{1}ms]" },
            { "Label_SelectedAreaGroups", "選択エリアグループ" },
            { "Label_SelectedAreaGroupsCount", "選択エリアグループ ({0})" },
            { "Placeholder_SearchTileId", "タイルID検索..." },
            { "Label_SearchResult", "検索結果" },

            // === Buttons - Form1 (Monster Tool) ===
            { "Button_Connect", "接続" },
            { "Button_AddToDatabase", "データベースに追加" },
            { "Button_ReloadMap", "現在のマップを再読み込み" },
            { "Button_ShowAllMonsters", "すべてのモンスター位置を表示" },
            { "Button_AddSpawn", "追加" },
            { "Button_CopySpawn", "コピー" },
            { "Button_DeleteSpawn", "削除" },
            { "Button_TestConnection", "接続テスト" },

            // === Labels - Common ===
            { "Label_Name", "名前" },
            { "Label_ID", "ID" },
            { "Label_Count", "数量" },
            { "Label_Note", "メモ" },

            // === Labels - MapForm ===
            { "Label_MapId", "マップID" },
            { "Label_GameCoord", "ゲーム座標" },
            { "Label_WorldCoord", "ワールド座標" },
            { "Label_Layer1Coord", "Layer1座標" },
            { "Label_Zoom", "ズーム" },
            { "Label_S32Files", "S32ファイル" },

            // === Labels - Form1 (Monster Tool) ===
            { "Label_ExpectedAdd", "追加予定" },
            { "Label_CenterX", "中心X座標" },
            { "Label_CenterY", "中心Y座標" },
            { "Label_Radius", "半径" },
            { "Label_RespawnMin", "リスポーン時間(最小)" },
            { "Label_RespawnMax", "リスポーン時間(最大)" },
            { "Label_SpawnInScreen", "画面内でスポーン" },
            { "Label_TeleportDistance", "テレポート距離" },
            { "Label_MonsterID", "モンスターID" },
            { "Label_MonsterNote", "モンスターメモ" },
            { "Label_MonsterCount", "モンスター数" },

            // === Labels - Database ===
            { "Label_SavedConnections", "保存された接続:" },
            { "Label_ConnectionName", "接続名:" },
            { "Label_ServerAddress", "サーバーアドレス:" },
            { "Label_Port", "ポート:" },
            { "Label_Database", "データベース:" },
            { "Label_Username", "ユーザー名:" },
            { "Label_Password", "パスワード:" },
            { "Group_ConnectionInfo", "接続情報" },

            // === Layer Names ===
            { "Layer_1", "レイヤー1 (床)" },
            { "Layer_2", "レイヤー2" },
            { "Layer_3", "レイヤー3 (属性)" },
            { "Layer_4", "レイヤー4 (オブジェクト)" },
            { "Layer_5", "レイヤー5 (光源)" },
            { "Layer_6", "レイヤー6" },
            { "Layer_7", "レイヤー7 (転送ポイント)" },
            { "Layer_8", "レイヤー8" },
            { "Layer_Passable", "通行性 (赤青)" },
            { "Layer_Grid", "グリッド表示" },
            { "Layer_S32Border", "S32境界" },
            { "Layer_CombatArea", "戦闘エリア" },
            { "Layer_Regions", "領域表示" },

            // === Floating Layer Panel (Short Labels) ===
            { "Label_Layers", "レイヤー" },
            { "Layer_FloatL1", "L1 床" },
            { "Layer_FloatL2", "L2" },
            { "Layer_FloatL4", "L4 物件" },
            { "Layer_FloatL5", "L5 透明" },
            { "Layer_FloatPassable", "通行" },
            { "Layer_FloatGrid", "グリッド" },
            { "Layer_FloatS32Border", "S32境界" },
            { "Layer_FloatRegions", "戦闘エリア" },

            // === Hints ===
            { "Hint_MouseControls", "中クリックでドラッグ | Ctrl+スクロールでズーム | 左クリックで選択" },

            // === Tooltips ===
            { "Tooltip_Copy", "コピー (Ctrl+C)" },
            { "Tooltip_Paste", "貼り付け (Ctrl+V)" },
            { "Tooltip_Delete", "削除 (Delete)" },
            { "Tooltip_Undo", "元に戻す (Ctrl+Z)" },
            { "Tooltip_Redo", "やり直し (Ctrl+Y)" },
            { "Tooltip_Save", "保存 (Ctrl+S)" },
            { "Tooltip_ZoomIn", "拡大" },
            { "Tooltip_ZoomOut", "縮小" },
            { "Tooltip_JumpToCoord", "ゲーム座標に移動" },
            { "Tooltip_NewS32", "新しいS32ブロックを追加" },
            { "Tooltip_ClearLayer7", "すべてのレイヤー7（転送ポイント）データをクリア" },
            { "Tooltip_ReplaceS32", "選択したS32ブロックを置換" },

            // === Message Box Titles ===
            { "Title_Error", "エラー" },
            { "Title_Info", "情報" },
            { "Title_Warning", "警告" },
            { "Title_Confirm", "確認" },
            { "Title_Success", "成功" },
            { "Title_SelectMap", "マップを選択" },
            { "Title_SelectFile", "ファイルを選択" },
            { "Title_SaveFile", "ファイルを保存" },
            { "Title_ImportMode", "インポートモードを選択" },
            { "Title_DangerConfirm", "危険な操作の確認" },

            // === Messages - Common ===
            { "Message_PleaseLoadMap", "先にマップを読み込んでください" },
            { "Message_PleaseSelectMap", "先にマップを選択してください" },
            { "Message_PleaseSelectItem", "先に項目を選択してください" },
            { "Message_SaveSuccess", "保存しました" },
            { "Message_SaveFailed", "保存に失敗しました: {0}" },
            { "Message_LoadFailed", "読み込みに失敗しました: {0}" },
            { "Message_ExportSuccess", "エクスポートしました" },
            { "Message_ExportFailed", "エクスポートに失敗しました: {0}" },
            { "Message_ImportSuccess", "インポートしました" },
            { "Message_ImportFailed", "インポートに失敗しました: {0}" },
            { "Message_ConfirmDelete", "削除してもよろしいですか？" },
            { "Message_OperationCancelled", "操作がキャンセルされました" },
            { "Message_InvalidInput", "無効な入力です" },
            { "Message_FileNotFound", "ファイルが見つかりません: {0}" },
            { "Message_NoDataToExport", "エクスポートするデータがありません" },

            // === Messages - Import Fs32 to New Map ===
            { "ImportNewMap_Title", "マップパッケージを新規マップにインポート" },
            { "ImportNewMap_SelectFile", "インポートする fs32 マップパッケージを選択" },
            { "ImportNewMap_EnterMapId", "新規マップ番号を入力してください:" },
            { "ImportNewMap_InvalidMapId", "無効なマップ番号です。数字を入力してください" },
            { "ImportNewMap_MapExists", "マップ {0} は既に存在します。既存のインポートフローを使用しますか？\n\n「はい」= そのマップを開いてパッケージをインポート\n「いいえ」= 操作をキャンセル" },
            { "ImportNewMap_CreatingFolder", "マップフォルダを作成中..." },
            { "ImportNewMap_FolderCreated", "マップフォルダを作成しました: {0}" },
            { "ImportNewMap_Importing", "マップパッケージをインポート中..." },
            { "ImportNewMap_Success", "マップパッケージを新規マップ {0} に正常にインポートしました" },
            { "ImportNewMap_Failed", "インポートに失敗しました: {0}" },
            { "ImportNewMap_PleaseOpenClient", "先にリネージュクライアントを開いてください" },

            // === Messages - Database ===
            { "Message_PleaseConnectDB", "先にデータベースに接続してください" },
            { "Message_ConnectionSuccess", "接続に成功しました！" },
            { "Message_ConnectionFailed", "接続に失敗しました: {0}" },
            { "Message_PleaseEnterConnName", "接続名を入力してください" },
            { "Message_PleaseEnterServer", "サーバーアドレスを入力してください" },
            { "Message_PleaseEnterDatabase", "データベース名を入力してください" },
            { "Message_ConnectionSaved", "接続を保存しました" },
            { "Message_ConfirmDeleteConnection", "この接続を削除してもよろしいですか？" },

            // === Messages - Monster Tool ===
            { "Message_PleaseEnterMonsterID", "モンスターIDを入力してください" },
            { "Message_InvalidMonsterID", "無効なモンスターIDです" },
            { "Message_MonsterAddedToQueue", "追加キューに追加しました" },
            { "Message_SpawnAdded", "スポーンポイントを追加しました" },
            { "Message_SpawnDeleted", "スポーンポイントを削除しました" },
            { "Message_NoSpawnSelected", "先にスポーンポイントを選択してください" },

            // === Messages - MapForm ===
            { "Message_S32Saved", "S32を保存しました" },
            { "Message_S32SaveFailed", "S32の保存に失敗しました: {0}" },
            { "Message_CoordsInvalid", "座標形式が無効です" },
            { "Message_NoS32Selected", "先にS32ファイルを選択してください" },
            { "Message_ClipboardEmpty", "クリップボードは空です" },
            { "Message_CopiedToClipboard", "クリップボードにコピーしました" },
            { "Message_ExportedTo", "エクスポートしました: {0}" },

            // === Messages - FS32 Import ===
            { "Message_Fs32Info", "fs32マップパック情報：" },
            { "Message_Fs32SourceMap", "元マップ" },
            { "Message_Fs32BlockCount", "ブロック数" },
            { "Message_Fs32TileCount", "タイル数" },
            { "Message_Fs32ImportTo", "現在のマップにインポート" },
            { "Message_Fs32SelectMode", "インポートモードを選択してください：" },
            { "Message_Fs32PartialReplace", "【部分置換】同じ座標のブロックのみ上書き（推奨）" },
            { "Message_Fs32FullReplace", "【完全置換】既存ブロックを削除し、インポートしたマップを使用" },
            { "Message_Fs32PartialButton", "「はい」= 部分置換（デフォルト）" },
            { "Message_Fs32FullButton", "「いいえ」= 完全置換" },
            { "Message_Fs32CancelButton", "「キャンセル」= インポートをキャンセル" },
            { "Message_Fs32FullReplaceWarning", "⚠️ 警告：完全置換モード ⚠️\n\nこれにより現在のマップのすべての既存ブロックが削除されます！\nマップ全体が消える可能性があり、インポートされたブロックのみが残ります。\n\nこの操作は元に戻せません！\n\n続行してもよろしいですか？" },
            { "Message_Fs32ImportComplete", "インポート完了！" },
            { "Message_Fs32ImportMode", "インポートモード" },
            { "Message_Fs32FullReplaceMode", "完全置換" },
            { "Message_Fs32PartialReplaceMode", "部分置換" },
            { "Message_Fs32DeletedBlocks", "削除した既存ブロック" },
            { "Message_Fs32ImportedBlocks", "インポート成功" },
            { "Message_Fs32ImportedTiles", "インポートしたタイル" },
            { "Message_Fs32ReusedTiles", "再利用したタイル" },
            { "Message_Fs32RemappedTiles", "再マッピング" },
            { "Message_Fs32SkippedBlocks", "{0}個のブロックをスキップ" },
            { "Message_Fs32InvalidFile", "無効なfs32ファイル、またはブロックが含まれていません" },
            { "Message_Fs32SelectFile", "インポートするfs32マップパックを選択" },
            { "Message_Fs32Blocks", "個のブロック" },
            { "Message_Fs32Tiles", "個" },

            // === Abnormal Check Dialog ===
            { "AbnormalCheck_Title", "異常チェック結果" },
            { "AbnormalCheck_FoundIssues", "以下の異常が見つかりました：" },
            { "AbnormalCheck_ViewDetails", "詳細を表示しますか？" },
            { "AbnormalCheck_Layer5Issues", "• {0} 個の Layer5 項目に異常" },
            { "AbnormalCheck_InvalidTileIds", "• {0} 個の無効な TileId ({1})" },
            { "AbnormalCheck_Layer8Extended", "• {0} 個の S32 が Layer8 拡張形式を使用（合計 {1} 項目、クラッシュの可能性あり）" },
            { "AbnormalCheck_TileOverLimit", "• {0} 個の Tile が上限超過 (上限={1}, 最大={2})、表示不可またはクラッシュの原因" },
            { "AbnormalCheck_Tab_Layer5", "Layer5 異常 ({0})" },
            { "AbnormalCheck_Tab_InvalidTile", "無効 TileId ({0})" },
            { "AbnormalCheck_Tab_Layer8", "L8 拡張形式 ({0})" },
            { "AbnormalCheck_Tab_OverLimit", "Tile上限超過 ({0})" },
            { "AbnormalCheck_Layer5Summary", "以下 {0} 個の Layer5 項目に異常があります（GroupIdが存在しないか周囲に対応オブジェクトがありません）：" },
            { "AbnormalCheck_TileSummary", "{0} 個の無効な TileId (L1:{1}, L2:{2}, L4:{3})。Tile ファイルが存在しないか IndexId が範囲外です：" },
            { "AbnormalCheck_Layer8Summary", "以下 {0} 個の S32 が Layer8 拡張形式を使用（合計 {1} 項目）。拡張形式はクラッシュの原因となる可能性があります：" },
            { "AbnormalCheck_OverLimitSummary", "Tile.idx に {0} 個の Tile ID が list.til 上限 ({1}) を超過。\n最大 Tile ID: {2}。これらの Tile は表示不可またはクラッシュの原因：" },
            { "AbnormalCheck_DeselectAll", "全解除" },
            { "AbnormalCheck_ClearSelected", "選択をクリア" },
            { "AbnormalCheck_ClearAll", "すべてクリア" },
            { "AbnormalCheck_SelectL1Only", "L1のみ" },
            { "AbnormalCheck_SelectL2Only", "L2のみ" },
            { "AbnormalCheck_SelectL4Only", "L4のみ" },
            { "AbnormalCheck_ResetSelectedFormat", "選択を通常形式にリセット" },
            { "AbnormalCheck_ResetAllFormat", "すべて通常形式にリセット" },
            { "AbnormalCheck_PleaseSelectItems", "クリアする項目を選択してください" },
            { "AbnormalCheck_Notice", "お知らせ" },
            { "AbnormalCheck_ConfirmClearSelected", "選択した {0} 項目をクリアしますか？" },
            { "AbnormalCheck_ConfirmDelete", "削除確認" },
            { "AbnormalCheck_ClearedLayer5", "{0} 個の異常な Layer5 項目をクリアしました" },
            { "AbnormalCheck_ClearComplete", "クリア完了" },
            { "AbnormalCheck_ConfirmClearAll", "すべての {0} 個の異常項目をクリアしますか？" },
            { "AbnormalCheck_ConfirmDeleteAll", "全削除確認" },
            { "AbnormalCheck_ConfirmClearTiles", "選択した {0} 個の無効 Tile をクリアしますか？\n\n• Layer1: TileId を 0 に設定\n• Layer2: 項目を削除\n• Layer4: オブジェクトを削除" },
            { "AbnormalCheck_ConfirmClearAllTiles", "すべての {0} 個の無効 Tile をクリアしますか？\n\n• Layer1: TileId を 0 に設定\n• Layer2: 項目を削除\n• Layer4: オブジェクトを削除" },
            { "AbnormalCheck_ClearedTiles", "{0} 個の無効 Tile をクリアしました" },
            { "AbnormalCheck_PleaseSelectReset", "リセットする項目を選択してください" },
            { "AbnormalCheck_ConfirmResetSelected", "選択した {0} 個の S32 を通常形式にリセットしますか？\n\nこれらの S32 のすべての Layer8 項目の ExtendedData がクリアされます。" },
            { "AbnormalCheck_ConfirmReset", "リセット確認" },
            { "AbnormalCheck_ResetComplete", "{0} 個の S32 を通常形式にリセットし、{1} 項目の ExtendedData をクリアしました。\n\nS32 ファイルを保存してください。" },
            { "AbnormalCheck_ResetDone", "リセット完了" },
            { "AbnormalCheck_ConfirmResetAll", "すべての {0} 個の S32 を通常形式にリセットしますか？\n\nすべての Layer8 項目の ExtendedData がクリアされます。" },
            { "AbnormalCheck_ConfirmResetAll_Title", "全リセット確認" },
            { "AbnormalCheck_Layer8ItemCount", "[{0}] Layer8 項目数: {1}" },

            // === Status Bar ===
            { "Status_Ready", "準備完了" },
            { "Status_Loading", "読み込み中..." },
            { "Status_Collecting", "収集中" },
            { "Status_Saving", "保存中..." },
            { "Status_Exporting", "エクスポート中..." },
            { "Status_Importing", "インポート中..." },
            { "Status_DeletingBlocks", "既存ブロックを削除中..." },
            { "Status_ImportingBlocks", "ブロックをインポート中..." },
            { "Status_LoadingFs32", "fs32を読み込み中..." },
            { "Status_ReloadingMap", "マップを再読み込み中..." },
            { "Status_ImportedBlocks", "{0}個のブロックをインポートしました" },
            { "Status_Coordinates", "座標: X={0}, Y={1}" },
            { "Status_MapLoaded", "マップを読み込みました: {0}" },

            // === Form Titles ===
            { "Form_MapEditor_Title", "マップエディタ" },
            { "Form_MonsterTool_Title", "モンスター設定ツール" },
            { "Form_DatabaseConnection_Title", "データベース接続管理" },
            { "Form_MonsterSearch_Title", "モンスター検索" },
            { "Form_ExportOptions_Title", "エクスポートオプション" },
            { "Form_CopySettings_Title", "設定をコピー" },
            { "Form_MaterialBrowser_Title", "素材ブラウザ" },

            // === Export Options ===
            { "Export_Mode_SelectedArea", "選択領域" },
            { "Export_Mode_FullMap", "マップ全体" },
            { "Export_SelectLayers", "エクスポートするレイヤーを選択" },
            { "Export_MaterialName", "素材名" },

            // === Copy Settings Dialog ===
            { "CopySettings_Layer1_Desc", "レイヤー1 (床)" },
            { "CopySettings_Layer2_Desc", "レイヤー2 (装飾)" },
            { "CopySettings_Layer3_Desc", "レイヤー3 (属性)" },
            { "CopySettings_Layer4_Desc", "レイヤー4 (オブジェクト)" },
            { "CopySettings_Layer5_Desc", "レイヤー5 (光源)" },
            { "CopySettings_Layer6to8_Desc", "レイヤー6-8 (その他)" },

            // === Material Browser ===
            { "Material_Search", "素材を検索" },
            { "Material_ChangePath", "パスを変更" },
            { "Material_UseThis", "この素材を使用" },
            { "Material_OpenFolder", "フォルダを開く" },
            { "Material_Preview", "プレビュー" },
            { "Material_NoPreview", "プレビューできません" },

            // === File Filters ===
            { "Filter_AllFiles", "すべてのファイル" },
            { "Filter_S32Files", "S32ファイル" },
            { "Filter_Fs32Files", "FS32マップパック" },
            { "Filter_ImageFiles", "画像ファイル" },
            { "Filter_JsonFiles", "JSONファイル" },

            // === Additional Dialog Strings ===
            { "Message_SelectAtLeastOneLayer", "少なくとも1つのレイヤーを選択してください" },
            { "CopySettings_SelectLayers", "コピー/削除するレイヤーを選択：" },

            // === Export Options Dialog ===
            { "Export_SaveAsMaterial", "素材として保存" },
            { "Export_Mode", "エクスポートモード" },
            { "Export_WholeMap", "マップ全体" },
            { "Export_SelectedBlocks", "選択されたブロック" },
            { "Export_SelectedRegion", "選択された領域（正確な範囲）" },
            { "Export_IncludeLayers", "含めるレイヤー" },
            { "Export_Layer1", "Layer1 床" },
            { "Export_Layer2", "Layer2 装飾" },
            { "Export_Layer3", "Layer3 属性" },
            { "Export_Layer4", "Layer4 オブジェクト" },
            { "Export_IncludeTiles", "タイルデータを含む" },
            { "Export_IncludeLayer5Events", "Layer5イベントを含む（Layer4オブジェクトと共に）" },
            { "Export_Export", "エクスポート" },

            // === Material Browser Additional ===
            { "Material_OpenFile", "ファイルを開く..." },
            { "Material_Use", "使用" },
            { "Material_Library", "素材ライブラリ" },
            { "Material_Items", "個の素材" },

            // === Misc ===
            { "Misc_Yes", "はい" },
            { "Misc_No", "いいえ" },
            { "Misc_Unit_Blocks", "個のブロック" },
            { "Misc_Unit_Tiles", "個のタイル" },
            { "Misc_Unit_Pixels", "ピクセル" },
            { "Misc_Unknown", "不明" },
            { "Misc_None", "なし" },
        };
    }
}
