using System.Collections.Generic;

namespace L1MapViewer.Localization
{
    /// <summary>
    /// Traditional Chinese (zh-TW) string resources
    /// </summary>
    public static class Strings_zhTW
    {
        public static Dictionary<string, string> GetStrings() => new()
        {
            // === Menu Items ===
            { "Menu_File", "檔案(&F)" },
            { "Menu_File_OpenClient", "開啟天堂客戶端讀取地圖" },
            { "Menu_File_Export", "匯出地圖通行資料" },
            { "Menu_File_Save", "儲存 S32" },
            { "Menu_File_ExportFs32", "匯出 FS32 地圖包..." },
            { "Menu_File_Exit", "結束" },
            { "Menu_Import", "匯入" },
            { "Menu_Import_Material", "匯入素材..." },
            { "Menu_Import_Fs32ToNewMap", "匯入地圖包到新地圖..." },
            { "Menu_Edit", "編輯(&E)" },
            { "Menu_Edit_Undo", "復原" },
            { "Menu_Edit_Redo", "重做" },
            { "Menu_Edit_Copy", "複製" },
            { "Menu_Edit_Paste", "貼上" },
            { "Menu_Edit_Delete", "刪除" },
            { "Menu_Edit_BatchDeleteTile", "批次刪除 Tile..." },
            { "Menu_Edit_BatchReplaceTile", "批次取代 Tile..." },
            { "Menu_View", "檢視(&V)" },
            { "Menu_View_Reload", "重新載入地圖" },
            { "Menu_View_Layers", "圖層" },
            { "Menu_View_Layer1", "Layer 1 地板" },
            { "Menu_View_Layer2", "Layer 2 裝飾" },
            { "Menu_View_Layer4", "Layer 4 物件" },
            { "Menu_View_Layer5", "Layer 5 事件" },
            { "Menu_View_Layer8", "Layer 8 SPR" },
            { "Menu_View_Passable", "通行性" },
            { "Menu_View_SafeZone", "安全區域" },
            { "Menu_View_CombatZone", "戰鬥區域" },
            { "Menu_View_Grid", "格線" },
            { "Menu_View_S32Border", "S32 邊界" },
            { "Menu_View_Zoom", "縮放" },
            { "Menu_View_ZoomIn", "放大" },
            { "Menu_View_ZoomOut", "縮小" },
            { "Menu_View_Zoom100", "100%" },
            { "Menu_Tools", "工具(&T)" },
            { "Menu_Tools_PassableEdit", "通行編輯模式" },
            { "Menu_Tools_RegionEdit", "區域編輯模式" },
            { "Menu_Tools_Layer5Edit", "透明編輯模式" },
            { "Menu_Tools_ValidateMap", "驗證地圖完整性" },
            { "Menu_Tools_AnalyzeAttr", "分析屬性分布" },
            { "Menu_MapEditor", "地圖編輯器" },
            { "Menu_Help", "說明(&H)" },
            { "Menu_Help_Discord", "到 Discord 討論" },
            { "Menu_Help_About", "關於..." },
            { "Menu_Language", "語言" },
            { "Menu_Export_ServerPassability", "輸出伺服器通行txt" },
            { "Menu_Export_L1JFormat", "L1J 格式" },
            { "Menu_Export_DIRFormat", "DIR 格式" },
            { "Menu_Export_AllMapsL1J", "輸出所有地圖 (L1J)" },
            { "Menu_Export_AllMapsDIR", "輸出所有地圖 (DIR)" },

            // === Tab Pages ===
            { "Tab_MapPreview", "地圖預覽" },
            { "Tab_S32Editor", "S32 編輯器" },
            { "Tab_MapList", "地圖列表" },
            { "Tab_S32Files", "S32 檔案" },
            { "Placeholder_SearchMap", "搜尋地圖 (ID 或名稱)..." },

            // === Buttons - Common ===
            { "Button_OK", "確定" },
            { "Button_Cancel", "取消" },
            { "Button_Preview", "預覽" },
            { "Button_Save", "儲存" },
            { "Button_Close", "關閉" },
            { "Button_New", "新增" },
            { "Button_Edit", "編輯" },
            { "Button_Delete", "刪除" },
            { "Button_Replace", "替換" },
            { "Button_ClearL7", "清L7" },
            { "Button_Copy", "複製" },
            { "Button_Paste", "貼上" },
            { "Button_Undo", "復原" },
            { "Button_Redo", "重做" },
            { "Button_Search", "搜尋" },
            { "Button_Refresh", "重新整理" },
            { "Button_Browse", "瀏覽" },
            { "Button_Apply", "套用" },
            { "Button_Reset", "重設" },

            // === Buttons - MapForm ===
            { "Button_JumpToCoord", "跳轉" },
            { "Button_ReloadF5", "重新載入 (F5)" },
            { "Button_SaveS32", "保存 S32" },
            { "Button_AnalyzeAttr", "分析屬性" },
            { "Button_SelectAll", "全選" },
            { "Button_SelectNone", "全不選" },
            { "Button_CopySettings", "複製設定" },
            { "Button_CopyMapCoords", "複製座標" },
            { "Button_ImportFs32", "匯入地圖包" },
            { "Label_RegionEdit", "區域編輯:" },
            { "Button_EditPassable", "通行" },
            { "Button_EditLayer5", "半透明" },
            { "Button_RegionEdit", "安全/戰鬥區" },
            { "Button_MarketRegionEdit", "可開店區" },
            { "Button_MergeL2ToL1", "L2合併L1" },

            // === Market Region Edit ===
            { "Status_MarketRegionCancelled", "已取消可開店區設置模式" },
            { "Status_MarketRegionMode", "可開店區設置模式：左鍵選取區域，右鍵設定/清除可開店區" },
            { "Menu_SetMarketRegion", "設為可開店區 ({0} 格)" },
            { "Menu_ClearMarketRegion", "清除可開店區 ({0} 格)" },
            { "Action_SetMarketRegion", "設為可開店區" },
            { "Action_ClearMarketRegion", "清除可開店區" },
            { "Button_ExportS32", "匯出 S32" },
            { "Button_NewS32", "新增 S32" },
            { "Button_ClearLayer7", "清除傳送點" },
            { "Button_ReplaceS32", "替換 S32" },
            { "Button_Details", "詳細" },
            { "Button_ClearCell", "清格" },
            { "Button_CheckL1", "查L1" },
            { "Button_CheckL2", "查L2" },
            { "Button_CheckL3", "查L3" },
            { "Button_CheckL4", "查L4" },
            { "Button_CheckL5", "查L5" },
            { "Button_CheckL6", "查L6" },
            { "Button_CheckL7", "查L7" },
            { "Button_CheckL8", "查L8" },
            { "Button_ViewClipboard", "剪貼" },
            { "Button_TestTile", "測til" },
            { "Button_ClearTestTile", "清til" },
            { "Button_More", "更多..." },
            { "Button_ShowAll", "全部" },

            // === Labels - Tile Panel ===
            { "Label_TileList", "Tile 列表" },
            { "Label_TileListCount", "Tile 列表 ({0})" },
            { "Label_RecentMaterials", "最近的素材" },
            { "Label_GroupThumbnails", "群組縮圖列表" },
            { "Label_GroupThumbnailsCount", "群組縮圖列表 ({0})" },
            { "Label_GroupThumbnailsLoading", "群組縮圖列表 (載入中 {0}/{1})" },
            { "Label_GroupThumbnailsTime", "群組縮圖列表 ({0}) [{1}ms]" },
            { "Label_NearbyGroups", "附近群組" },
            { "Label_NearbyGroupsCount", "附近群組 ({0})" },
            { "Label_NearbyGroupsLoading", "附近群組 ({0}, L5:{1}) 載入中..." },
            { "Label_NearbyGroupsTime", "附近群組 ({0}) [{1}ms]" },
            { "Label_SelectedAreaGroups", "選取區域群組" },
            { "Label_SelectedAreaGroupsCount", "選取區域群組 ({0})" },
            { "Label_SelectedAreaAllGroups", "區域-全部" },
            { "Placeholder_SearchTileId", "搜尋 TileId..." },
            { "Placeholder_SearchGroup", "搜尋..." },
            { "GroupMode_SelectedArea", "選取區域" },
            { "GroupMode_SelectedAreaAll", "區域-全部" },
            { "GroupMode_All", "全部" },
            { "Label_SearchResult", "搜尋結果" },

            // === Labels - Common ===
            { "Label_Name", "名稱" },
            { "Label_ID", "ID" },
            { "Label_Count", "數量" },
            { "Label_Note", "備註" },

            // === Labels - MapForm ===
            { "Label_MapId", "地圖 ID" },
            { "Label_GameCoord", "遊戲座標" },
            { "Label_WorldCoord", "世界座標" },
            { "Label_Layer1Coord", "Layer1 座標" },
            { "Label_Zoom", "縮放" },
            { "Label_S32Files", "S32 檔案" },
            { "Label_S32FileList", "S32 檔案清單" },
            { "Label_S32FileListCount", "S32 檔案清單 ({0})" },

            // === Layer Names ===
            { "Layer_1", "第1層 (地板)" },
            { "Layer_2", "第2層" },
            { "Layer_3", "第3層 (多色屬性)" },
            { "Layer_4", "第4層 (物件)" },
            { "Layer_5", "第5層 (光源)" },
            { "Layer_6", "第6層" },
            { "Layer_7", "第7層 (傳送點)" },
            { "Layer_8", "第8層" },
            { "Layer_Passable", "通行性 (紅藍)" },
            { "Layer_Grid", "顯示格線" },
            { "Layer_S32Border", "S32邊界" },
            { "Layer_SafeZones", "安全區域" },
            { "Layer_CombatZones", "戰鬥區域" },
            { "Layer_MarketZones", "可開店區" },
            { "Layer_CombatArea", "戰鬥區域" },
            { "Layer_Regions", "顯示區域" },

            // === Floating Layer Panel (Short Labels) ===
            { "Label_Layers", "圖層" },
            { "Layer_FloatL1", "L1 地板" },
            { "Layer_FloatL2", "L2" },
            { "Layer_FloatL4", "L4 物件" },
            { "Layer_FloatL5", "L5 透明" },
            { "Layer_FloatPassable", "通行" },
            { "Layer_FloatGrid", "格線" },
            { "Layer_FloatS32Border", "S32邊界" },
            { "Layer_FloatSafeZones", "安全區" },
            { "Layer_FloatCombatZones", "戰鬥區" },
            { "Layer_FloatMarketZones", "可開店區" },
            { "Layer_L8Spr", "L8 圖片" },
            { "Layer_L8Marker", "L8 輔助" },

            // === Hints ===
            { "Hint_MouseControls", "滑鼠中鍵拖移 | 左鍵選取格子" },

            // === Tooltips ===
            { "Tooltip_Copy", "複製 (Ctrl+C)" },
            { "Tooltip_Paste", "貼上 (Ctrl+V)" },
            { "Tooltip_Delete", "刪除 (Delete)" },
            { "Tooltip_Undo", "復原 (Ctrl+Z)" },
            { "Tooltip_Redo", "重做 (Ctrl+Y)" },
            { "Tooltip_Save", "儲存 (Ctrl+S)" },
            { "Tooltip_ZoomIn", "放大" },
            { "Tooltip_ZoomOut", "縮小" },
            { "Tooltip_JumpToCoord", "跳轉至遊戲座標" },
            { "Tooltip_NewS32", "新增 S32 區塊" },
            { "Tooltip_ClearLayer7", "清除所有第七層（傳送點）資料" },
            { "Tooltip_ReplaceS32", "替換選取的 S32 區塊" },

            // === Message Box Titles ===
            { "Title_Error", "錯誤" },
            { "Title_Info", "提示" },
            { "Title_Warning", "警告" },
            { "Title_Confirm", "確認" },
            { "Title_Success", "成功" },
            { "Title_SelectMap", "選擇地圖" },
            { "Title_SelectFile", "選擇檔案" },
            { "Title_SaveFile", "儲存檔案" },
            { "Title_ImportMode", "選擇匯入模式" },
            { "Title_DangerConfirm", "危險操作確認" },

            // === Messages - Common ===
            { "Message_PleaseLoadMap", "請先載入地圖" },
            { "Message_PleaseSelectMap", "請先選擇地圖" },
            { "Message_PleaseSelectItem", "請先選擇項目" },
            { "Message_SaveSuccess", "儲存成功" },
            { "Message_SaveFailed", "儲存失敗: {0}" },
            { "Message_LoadFailed", "載入失敗: {0}" },
            { "Message_ExportSuccess", "匯出成功" },
            { "Message_ExportFailed", "匯出失敗: {0}" },
            { "Message_ImportSuccess", "匯入成功" },
            { "Message_ImportFailed", "匯入失敗: {0}" },
            { "Message_ConfirmDelete", "確定要刪除嗎？" },
            { "Message_OperationCancelled", "操作已取消" },
            { "Message_InvalidInput", "輸入無效" },
            { "Message_FileNotFound", "找不到檔案: {0}" },
            { "Message_NoDataToExport", "沒有資料可匯出" },

            // === Messages - Import Fs32 to New Map ===
            { "ImportNewMap_Title", "匯入地圖包到新地圖" },
            { "ImportNewMap_SelectFile", "選擇要匯入的 fs32 地圖包" },
            { "ImportNewMap_EnterMapId", "請輸入新地圖編號:" },
            { "ImportNewMap_InvalidMapId", "無效的地圖編號，請輸入數字" },
            { "ImportNewMap_MapExists", "地圖 {0} 已經存在，是否要使用既有的匯入流程？\n\n按「是」將開啟該地圖並匯入地圖包\n按「否」取消操作" },
            { "ImportNewMap_CreatingFolder", "正在建立地圖資料夾..." },
            { "ImportNewMap_FolderCreated", "已建立地圖資料夾: {0}" },
            { "ImportNewMap_Importing", "正在匯入地圖包..." },
            { "ImportNewMap_Success", "地圖包已成功匯入到新地圖 {0}" },
            { "ImportNewMap_Failed", "匯入失敗: {0}" },
            { "ImportNewMap_PleaseOpenClient", "請先開啟天堂客戶端" },

            // === Messages - MapForm ===
            { "Message_S32Saved", "S32 已儲存" },
            { "Message_S32SaveFailed", "S32 儲存失敗: {0}" },
            { "Message_CoordsInvalid", "座標格式無效" },
            { "Message_NoS32Selected", "請先選擇 S32 檔案" },
            { "Message_ClipboardEmpty", "剪貼簿是空的" },
            { "Message_CopiedToClipboard", "已複製到剪貼簿" },
            { "Message_ExportedTo", "已成功匯出至: {0}" },

            // === Messages - FS32 Import ===
            { "Message_Fs32Info", "fs32 地圖包資訊：" },
            { "Message_Fs32SourceMap", "來源地圖" },
            { "Message_Fs32BlockCount", "區塊數量" },
            { "Message_Fs32TileCount", "圖塊數量" },
            { "Message_Fs32ImportTo", "將匯入至當前地圖" },
            { "Message_Fs32SelectMode", "請選擇匯入模式：" },
            { "Message_Fs32PartialReplace", "【部份取代】只覆蓋相同座標的區塊（推薦）" },
            { "Message_Fs32FullReplace", "【全部取代】刪除既有區塊，完全使用匯入的地圖" },
            { "Message_Fs32PartialButton", "按「是」= 部份取代（預設）" },
            { "Message_Fs32FullButton", "按「否」= 全部取代" },
            { "Message_Fs32CancelButton", "按「取消」= 取消匯入" },
            { "Message_Fs32FullReplaceWarning", "⚠️ 警告：全部取代模式 ⚠️\n\n這將會刪除當前地圖的所有既有區塊！\n整張地圖可能會消失，只剩下匯入的區塊。\n\n此操作無法復原！\n\n確定要繼續嗎？" },
            { "Message_Fs32ImportComplete", "匯入完成！" },
            { "Message_Fs32ImportMode", "匯入模式" },
            { "Message_Fs32FullReplaceMode", "全部取代" },
            { "Message_Fs32PartialReplaceMode", "部份取代" },
            { "Message_Fs32DeletedBlocks", "已刪除既有區塊" },
            { "Message_Fs32ImportedBlocks", "成功匯入" },
            { "Message_Fs32ImportedTiles", "匯入圖塊" },
            { "Message_Fs32ReusedTiles", "重用圖塊" },
            { "Message_Fs32RemappedTiles", "重新編號" },
            { "Message_Fs32SkippedBlocks", "跳過 {0} 個區塊" },
            { "Message_Fs32InvalidFile", "無效的 fs32 檔案或不包含任何區塊" },
            { "Message_Fs32SelectFile", "選擇要匯入的 fs32 地圖包" },
            { "Message_Fs32Blocks", "個區塊" },
            { "Message_Fs32Tiles", "個" },

            // === Abnormal Check Dialog ===
            { "AbnormalCheck_Title", "異常檢查結果" },
            { "AbnormalCheck_FoundIssues", "發現以下異常：" },
            { "AbnormalCheck_ViewDetails", "是否要查看詳細資訊？" },
            { "AbnormalCheck_Layer5Issues", "• {0} 個 Layer5 項目異常" },
            { "AbnormalCheck_InvalidTileIds", "• {0} 個無效的 TileId ({1})" },
            { "AbnormalCheck_Layer8Extended", "• {0} 個 S32 使用 Layer8 擴展格式（共 {1} 個項目，可能導致閃退）" },
            { "AbnormalCheck_TileOverLimit", "• {0} 個 Tile 超過上限 (上限={1}, 最大={2})，將無法顯示或導致閃退" },
            { "AbnormalCheck_Tab_Layer5", "Layer5 異常 ({0})" },
            { "AbnormalCheck_Tab_InvalidTile", "無效 TileId ({0})" },
            { "AbnormalCheck_Tab_Layer8", "L8 擴展格式 ({0})" },
            { "AbnormalCheck_Tab_OverLimit", "Tile超上限 ({0})" },
            { "AbnormalCheck_Layer5Summary", "以下 {0} 個 Layer5 項目異常（GroupId不存在或周圍一格內無對應物件）：" },
            { "AbnormalCheck_TileSummary", "發現 {0} 個無效 TileId (L1:{1}, L2:{2}, L4:{3})。這些 Tile 檔案不存在或 IndexId 超出範圍：" },
            { "AbnormalCheck_Layer8Summary", "以下 {0} 個 S32 使用 Layer8 擴展格式（共 {1} 個項目）。擴展格式可能導致遊戲閃退：" },
            { "AbnormalCheck_OverLimitSummary", "Tile.idx 中有 {0} 個 Tile ID 超過 list.til 上限 ({1})。\n最大 Tile ID: {2}。這些 Tile 將無法顯示或導致閃退：" },
            { "AbnormalCheck_DeselectAll", "取消全選" },
            { "AbnormalCheck_ClearSelected", "清除勾選" },
            { "AbnormalCheck_ClearAll", "清除全部" },
            { "AbnormalCheck_SelectL1Only", "只選L1" },
            { "AbnormalCheck_SelectL2Only", "只選L2" },
            { "AbnormalCheck_SelectL4Only", "只選L4" },
            { "AbnormalCheck_ResetSelectedFormat", "重設勾選為一般格式" },
            { "AbnormalCheck_ResetAllFormat", "全部重設為一般格式" },
            { "AbnormalCheck_PleaseSelectItems", "請先勾選要清除的項目" },
            { "AbnormalCheck_Notice", "提示" },
            { "AbnormalCheck_ConfirmClearSelected", "確定要清除勾選的 {0} 個項目嗎？" },
            { "AbnormalCheck_ConfirmDelete", "確認刪除" },
            { "AbnormalCheck_ClearedLayer5", "已清除 {0} 個異常的 Layer5 項目" },
            { "AbnormalCheck_ClearComplete", "清除完成" },
            { "AbnormalCheck_ConfirmClearAll", "確定要清除所有 {0} 個異常項目嗎？" },
            { "AbnormalCheck_ConfirmDeleteAll", "確認刪除全部" },
            { "AbnormalCheck_ConfirmClearTiles", "確定要清除勾選的 {0} 個無效 Tile 嗎？\n\n• Layer1: 將 TileId 設為 0\n• Layer2: 移除該項目\n• Layer4: 移除該物件" },
            { "AbnormalCheck_ConfirmClearAllTiles", "確定要清除所有 {0} 個無效 Tile 嗎？\n\n• Layer1: 將 TileId 設為 0\n• Layer2: 移除該項目\n• Layer4: 移除該物件" },
            { "AbnormalCheck_ClearedTiles", "已清除 {0} 個無效 Tile" },
            { "AbnormalCheck_PleaseSelectReset", "請先勾選要重設的項目" },
            { "AbnormalCheck_ConfirmResetSelected", "確定要將勾選的 {0} 個 S32 重設為一般格式嗎？\n\n這會清除這些 S32 所有 Layer8 項目的 ExtendedData。" },
            { "AbnormalCheck_ConfirmReset", "確認重設" },
            { "AbnormalCheck_ResetComplete", "已重設 {0} 個 S32 為一般格式，清除了 {1} 個項目的 ExtendedData。\n\n請記得儲存 S32 檔案。" },
            { "AbnormalCheck_ResetDone", "重設完成" },
            { "AbnormalCheck_ConfirmResetAll", "確定要將所有 {0} 個 S32 重設為一般格式嗎？\n\n這會清除所有 Layer8 項目的 ExtendedData。" },
            { "AbnormalCheck_ConfirmResetAll_Title", "確認重設全部" },
            { "AbnormalCheck_Layer8ItemCount", "[{0}] Layer8 項目數: {1}" },

            // === Status Bar ===
            { "Status_Ready", "就緒" },
            { "Status_Loading", "載入中" },
            { "Status_Collecting", "收集中" },
            { "Status_Saving", "儲存中..." },
            { "Status_Exporting", "匯出中..." },
            { "Status_Importing", "匯入中..." },
            { "Status_DeletingBlocks", "正在刪除既有區塊..." },
            { "Status_ImportingBlocks", "正在匯入區塊..." },
            { "Status_LoadingFs32", "正在載入 fs32..." },
            { "Status_ReloadingMap", "正在重新載入地圖..." },
            { "Status_ImportedBlocks", "已匯入 {0} 個區塊" },
            { "Status_Coordinates", "座標: X={0}, Y={1}" },
            { "Status_MapLoaded", "地圖已載入: {0}" },

            // === Form Titles ===
            { "Form_MapEditor_Title", "地圖編輯器" },
            { "Form_ExportOptions_Title", "匯出選項" },
            { "Form_ExportFs32_Title", "匯出 FS32 地圖包" },
            { "Form_CopySettings_Title", "複製設定" },
            { "Form_MaterialBrowser_Title", "素材庫瀏覽器" },

            // === Export Options ===
            { "Export_Mode_SelectedArea", "選取區域" },
            { "Export_Mode_FullMap", "整張地圖" },
            { "Export_SelectLayers", "選擇要匯出的圖層" },
            { "Export_MaterialName", "素材名稱" },

            // === Copy Settings Dialog ===
            { "CopySettings_Layer1_Desc", "Layer 1 (地板)" },
            { "CopySettings_Layer2_Desc", "Layer 2 (裝飾)" },
            { "CopySettings_Layer3_Desc", "Layer 3 (屬性)" },
            { "CopySettings_Layer4_Desc", "Layer 4 (物件)" },
            { "CopySettings_Layer5_Desc", "Layer 5 (光源)" },
            { "CopySettings_Layer6to8_Desc", "Layer 6-8 (其他)" },
            { "CopySettings_Layer7_Desc", "Layer 7 (傳送點)" },
            { "CopySettings_Layer8_Desc", "Layer 8 (特效)" },

            // === Material Browser ===
            { "Material_Search", "搜尋素材" },
            { "Material_ChangePath", "變更路徑" },
            { "Material_UseThis", "使用此素材" },
            { "Material_OpenFolder", "開啟所在資料夾" },
            { "Material_Preview", "預覽" },
            { "Material_NoPreview", "無法預覽" },

            // === File Filters ===
            { "Filter_AllFiles", "所有檔案" },
            { "Filter_S32Files", "S32 檔案" },
            { "Filter_Fs32Files", "FS32 地圖包" },
            { "Filter_ImageFiles", "圖片檔案" },
            { "Filter_JsonFiles", "JSON 檔案" },

            // === Additional Dialog Strings ===
            { "Message_SelectAtLeastOneLayer", "請至少選擇一個圖層" },
            { "CopySettings_SelectLayers", "選擇要複製/刪除的圖層：" },

            // === Export Options Dialog ===
            { "Export_SaveAsMaterial", "儲存為素材" },
            { "Export_Mode", "匯出模式" },
            { "Export_WholeMap", "整張地圖" },
            { "Export_SelectedBlocks", "選取的區塊" },
            { "Export_SelectedRegion", "選取的區域 (精確範圍)" },
            { "Export_IncludeLayers", "包含圖層" },
            { "Export_Layer1", "Layer1 地板" },
            { "Export_Layer2", "Layer2 裝飾" },
            { "Export_Layer3", "Layer3 屬性" },
            { "Export_Layer4", "Layer4 物件" },
            { "Export_IncludeTiles", "包含 Tile 資料" },
            { "Export_IncludeLayer5Events", "包含 Layer5 事件 (隨 Layer4 物件)" },
            { "Export_StripLayer8Ext", "移除 Layer8 擴展資料" },
            { "Export_Export", "匯出" },

            // === Material Browser Additional ===
            { "Material_OpenFile", "開啟檔案..." },
            { "Material_Use", "使用" },
            { "Material_Library", "素材庫" },
            { "Material_Items", "個素材" },

            // === Misc ===
            { "Misc_Yes", "是" },
            { "Misc_No", "否" },
            { "Misc_Unit_Blocks", "個區塊" },
            { "Misc_Unit_Tiles", "個圖塊" },
            { "Misc_Unit_Pixels", "像素" },
            { "Misc_Unknown", "未知" },
            { "Misc_None", "無" },

            // === About Dialog ===
            { "About_Title", "關於 L1MapViewer" },
            { "About_Version", "版本" },
            { "About_Description", "天堂地圖編輯器 - 用於檢視與編輯天堂遊戲地圖檔案" },
            { "About_Discord", "Discord 社群" },
            { "About_GitHub", "GitHub 專案" },
            { "About_DiscordLink", "https://discord.gg/lineage" },
            { "About_GitHubLink", "https://github.com/tony1223/L1MapViewer" },

            // === L8 Dialog ===
            { "L8_Title", "L8 檢查、編輯與清除" },
            { "L8_Summary", "選取: {0} 個 S32 / {1} 項 | 全部: {2} 個 S32 / {3} 項 | {4} 個擴展格式" },
            { "L8_TabAll", "全部 ({0})" },
            { "L8_TabSelected", "選取的 S32 ({0})" },
            { "L8_Preview", "SPR 預覽" },
            { "L8_SelectToPreview", "選取項目以預覽" },
            { "L8_JumpToLocation", "跳轉到位置" },
            { "L8_FilterNoImage", "只顯示無圖項目" },
            { "L8_ExtendedSettings", "擴展格式設定" },
            { "L8_ExtendedInfo", "擴展格式 (Extended) 表示 Layer8 項目包含額外 4 bytes 資料。選擇 S32 檔案後可切換其擴展格式設定：" },
            { "L8_CurrentStatus", "目前：{0}" },
            { "L8_NotSelected", "未選擇" },
            { "L8_ExtendedFormat", "擴展格式" },
            { "L8_NormalFormat", "一般格式" },
            { "L8_SetExtended", "設為擴展" },
            { "L8_SetNormal", "設為一般" },
            { "L8_ResetAll", "全部重設為一般" },
            { "L8_SetExtendedDone", "已將 {0} 設為擴展格式。\n請記得儲存 S32 檔案。" },
            { "L8_SetNormalDone", "已將 {0} 設為一般格式，並清除 {1} 個項目的 ExtendedData。\n請記得儲存 S32 檔案。" },
            { "L8_NoExtendedFiles", "沒有使用擴展格式的 S32 檔案。" },
            { "L8_ConfirmResetAll", "確定要將所有 {0} 個 S32 檔案的 Layer8 重設為一般格式嗎？\n\n注意：這會清除所有 ExtendedData 欄位的資料。" },
            { "L8_ConfirmResetTitle", "確認重設" },
            { "L8_ResetAllDone", "已將 {0} 個 S32 檔案重設為一般格式，並清除 {1} 個項目的 ExtendedData。\n請記得儲存 S32 檔案。" },
            { "L8_Column_File", "S32檔案" },
            { "L8_Column_Extended", "擴展" },
            { "L8_Column_SprId", "SprId" },
            { "L8_Column_Preview", "預覽" },
            { "L8_Column_X", "X" },
            { "L8_Column_Y", "Y" },
            { "L8_Column_ExtData", "ExtData" },
            { "L8_Yes", "是" },
            { "L8_JumpedToLocation", "已跳轉到 L8 項目位置 ({0}, {1}) - SprId: {2}" },
            { "L8_ShowAllL8", "顯示全部L8" },
            { "L8_EnabledCount", "已啟用 {0} 個 L8 特效（總共 {1} 個）" },

            // L8 編輯區域
            { "L8_EditSection", "編輯選取的項目" },
            { "L8_ApplyEdit", "套用修改" },
            { "L8_AddNew", "新增" },
            { "L8_SelectS32File", "選擇 S32 檔案" },
            { "L8_SelectS32ForNewItem", "選擇要新增 Layer8 項目的 S32 檔案:" },
            { "L8_NoImageCount", "無圖項目: {0} 個 SPR" },

            // L8 批次取代
            { "L8_BatchReplace", "批次取代 SprId" },
            { "L8_FromSprId", "將 SprId:" },
            { "L8_ToSprId", "改為:" },
            { "L8_BatchReplaceBtn", "批次取代" },
            { "L8_AffectsAllS32", "(影響全部 S32)" },

            // L8 按鈕
            { "L8_SelectAll", "全選" },
            { "L8_DeselectAll", "取消全選" },
            { "L8_DeleteChecked", "刪除勾選項目" },
            { "L8_DeleteAll", "刪除全部 L8" },
            { "L8_Close", "關閉" },

            // L8 訊息對話框
            { "L8_SelectOneToEdit", "請選取一個項目進行編輯" },
            { "L8_InvalidValue", "請輸入有效的數值" },
            { "L8_EditApplied", "已套用修改。請記得儲存 S32 檔案。" },
            { "L8_ItemAdded", "已新增 Layer8 項目到 {0}。\n\n請記得儲存 S32 檔案。" },
            { "L8_InvalidSprId", "請輸入有效的 SprId 數值" },
            { "L8_SameSprId", "來源和目標 SprId 相同" },
            { "L8_SprIdNotFound", "找不到 SprId = {0} 的項目" },
            { "L8_ConfirmBatchReplace", "確定要將所有 SprId = {0} 的項目 ({1} 個) 改為 SprId = {2} 嗎？" },
            { "L8_ConfirmBatchReplaceTitle", "確認批次取代" },
            { "L8_BatchReplaceComplete", "已將 {0} 個項目的 SprId 從 {1} 改為 {2}。\n影響 {3} 個 S32 檔案。\n\n請記得儲存 S32 檔案。" },
            { "L8_BatchReplaceCompleteTitle", "批次取代完成" },
            { "L8_SelectToDelete", "請先勾選要刪除的項目" },
            { "L8_ConfirmDeleteChecked", "確定要刪除勾選的 {0} 個 Layer8 項目嗎？" },
            { "L8_ConfirmDeleteTitle", "確認刪除" },
            { "L8_DeleteComplete", "已刪除 {0} 個 Layer8 項目。\n\n請記得儲存 S32 檔案。" },
            { "L8_ConfirmDeleteAll", "確定要刪除所有 {0} 個 Layer8 項目嗎？" },
            { "L8_ConfirmDeleteAllTitle", "確認刪除全部" },

            // 共用標題
            { "Title_Done", "完成" },
            { "Common_OK", "確定" },

            // 批次刪除 Tile
            { "Form_BatchDeleteTile_Title", "批次刪除 Tile" },
            { "Menu_BatchDeleteTile", "批次刪除 Tile..." },
            { "BatchDeleteTile_TileIdRange", "TileId 範圍" },
            { "BatchDeleteTile_IndexIdRange", "IndexId 範圍" },
            { "BatchDeleteTile_Start", "起始" },
            { "BatchDeleteTile_End", "結束" },
            { "BatchDeleteTile_Scope", "處理範圍" },
            { "BatchDeleteTile_CurrentMap", "當前地圖" },
            { "BatchDeleteTile_AllMaps", "所有地圖 (maps 資料夾)" },
            { "BatchDeleteTile_Warning", "此操作會直接修改 S32 檔案，請先備份！" },
            { "BatchDeleteTile_InvalidTileIdRange", "TileId 起始值不能大於結束值" },
            { "BatchDeleteTile_InvalidIndexIdRange", "IndexId 起始值不能大於結束值" },
            { "BatchDeleteTile_ConfirmMessage", "確定要刪除符合以下條件的 Tile 嗎？\n\nTileId: {0} ~ {1}\nIndexId: {2} ~ {3}\n範圍: {4}\n\n此操作無法復原！" },
            { "BatchDeleteTile_Confirm", "確認刪除" },
            { "BatchDeleteTile_NoClient", "請先開啟天堂客戶端！" },
            { "BatchDeleteTile_NoMapLoaded", "請先載入地圖！" },
            { "BatchDeleteTile_NoS32Files", "找不到可處理的 S32 檔案" },
            { "BatchDeleteTile_Processing", "正在處理 {0} ({1}/{2})..." },
            { "BatchDeleteTile_Result", "刪除完成！\n\n刪除數量: {0}\n修改檔案: {1}\n失敗檔案: {2}" },
            { "BatchDeleteTile_Complete", "批次刪除完成" },

            // === Batch Replace Tile Dialog ===
            { "Form_BatchReplaceTile_Title", "批次替換 TileId" },
            { "BatchReplaceTile_SelectLayer", "選擇圖層" },
            { "BatchReplaceTile_Layer1", "Layer1 (地板)" },
            { "BatchReplaceTile_Layer2", "Layer2 (索引)" },
            { "BatchReplaceTile_Layer4", "Layer4 (物件)" },
            { "BatchReplaceTile_Source", "來源" },
            { "BatchReplaceTile_Target", "替換為" },
            { "BatchReplaceTile_MatchIndexId", "比對 IndexId" },
            { "BatchReplaceTile_ReplaceIndexId", "替換 IndexId" },
            { "BatchReplaceTile_Execute", "執行替換" },
            { "BatchReplaceTile_PreviewResult", "[{0}] 找到 {1} 個匹配項目，分布在 {2} 個 S32 檔案" },
            { "BatchReplaceTile_ConfirmMessage", "確定要在 [{0}] 將所有 {1}\n替換為 {2} 嗎？\n\n此操作會影響所有已載入的 S32 檔案。" },
            { "BatchReplaceTile_Confirm", "確認替換" },
            { "BatchReplaceTile_Complete", "替換完成！\n共替換 {0} 個項目\n影響 {1} 個 S32 檔案\n\n請記得儲存修改。" },
            { "BatchReplaceTile_StatusComplete", "[{0}] 已替換 {1} 個項目，影響 {2} 個 S32 檔案" },
            { "BatchReplaceTile_NoMap", "請先載入地圖" },

            // === Map List Context Menu ===
            { "MapList_ExportAsFs32", "匯出為地圖包 (fs32)..." },
            { "MapList_MapNotExist", "地圖 {0} 不存在" },
            { "MapList_LoadingMap", "正在載入地圖 {0}..." },
            { "MapList_LoadingFiles", "正在載入地圖檔案... ({0})" },
            { "MapList_NoMapFiles", "地圖 {0} 沒有可用的地圖檔案 (.s32 或 .seg)" },
            { "MapList_CreatingFs32", "正在建立 fs32 檔案..." },
            { "MapList_ExportResult", "已匯出至 {0}\n({1} 區塊, {2} 圖塊, {3} SPR)" },
            { "MapList_ExportComplete", "匯出完成" },
            { "MapList_ExportFailed", "匯出失敗: {0}" },

            // === S32 List Context Menu ===
            { "S32Menu_JumpToBlock", "跳轉至此區塊" },
            { "S32Menu_ViewDetails", "查看詳細資料" },
            { "S32Menu_ExportMapAsFs32", "匯出整張地圖為 fs32 地圖包..." },
            { "S32Menu_ExportCheckedAsFs32", "匯出已勾選的 {0} 個區塊為 fs32 地圖包..." },
            { "S32Menu_ImportFs32", "匯入 fs32 地圖包..." },
            { "S32Menu_ClearBlockData", "⚠ 清空此區塊資料..." },
            { "S32Menu_DeleteBlock", "⚠ 刪除此區塊..." },
            { "S32Menu_DeleteCheckedBlocks", "⚠ 刪除已勾選的 {0} 個區塊..." },

            // === MiniMap Context Menu ===
            { "MiniMap_AddS32Block", "➕ 在此位置新增 S32 區塊 ({0})..." },
            { "MiniMap_ImportFs32Here", "📦 在此位置匯入 fs32..." },
            { "MiniMap_EstimatedPosition", "預估位置: {0} ({1},{2})" },
            { "MiniMap_CurrentBlock", "當前區塊: {0}" },
            { "MiniMap_TargetPosition", "目標位置: {0} ({1},{2})" },
            { "MiniMap_AddS32Title", "新增 S32" },
            { "MiniMap_AddS32Confirm", "要在此位置新增 S32 區塊嗎？\n\n檔案名稱: {0}\nBlock座標: ({1}, {2})\n遊戲座標: ({3},{4}) ~ ({5},{6})\n路徑: {7}" },

            // === Selection Context Menu ===
            { "Selection_ViewDetails", "查看詳細資料..." },
            { "Selection_ExportAsFs32", "匯出為 fs32 地圖包..." },
            { "Selection_SaveAsFs3p", "儲存為素材 (fs3p)..." },
            { "Selection_Copy", "複製 (Ctrl+C)" },
            { "Selection_FillWithFloor", "用複製中的地板填滿選取區" },
            { "Selection_ClearData", "清除選取區域資料..." },
            { "Selection_ShowGroupArea", "顯示區域群組所在位置" },

            // === L5 Editor Context Menu ===
            { "L5Menu_EditItem", "編輯此 L5 項目" },
            { "L5Menu_DeleteItem", "刪除此 L5 項目" },

            // === Tile List Context Menu ===
            { "TileList_CopyRow", "複製整行" },
            { "TileList_ViewDetails", "查看詳細資訊" },
            { "TileList_ExportSelectedTile", "匯出選中的 Tile 圖片" },

            // === Material Context Menu ===
            { "Material_ViewDetails", "查看詳情..." },
            { "Material_UseMaterial", "使用素材" },
            { "Material_Rename", "重新命名..." },
            { "Material_CopyPath", "複製檔案路徑" },
            { "Material_Export", "匯出素材..." },
            { "Material_Delete", "刪除素材" },

            // === Group Thumbnail Context Menu ===
            { "GroupThumbnail_GotoLocation", "跳轉到位置" },
            { "GroupThumbnail_ShowCells", "顯示群組所在格子" },
            { "GroupThumbnail_CopyGroup", "複製群組 {0}" },
            { "GroupThumbnail_DetailL4", "列出 L4 明細 ({0} 個物件)" },
            { "GroupThumbnail_DeleteGroup", "刪除群組 {0} ({1} 個物件)" },
            { "GroupThumbnail_SaveAsMaterial", "儲存群組 {0} 為素材..." },
            { "GroupThumbnail_ChangeId", "變更群組 {0} 的 ID..." },
            { "GroupThumbnail_AutoNewId", "自動指定新群組 ID" },
            { "GroupThumbnail_AutoNewIdSeparate", "自動指定新群組 ID（各自獨立）" },
            { "GroupThumbnail_CopyMultiple", "複製 {0} 個群組 ({1} 個物件)" },
            { "GroupThumbnail_DeleteMultiple", "刪除 {0} 個群組 ({1} 個物件)" },
            { "GroupThumbnail_SaveMultipleAsMaterial", "儲存 {0} 個群組為素材..." },
            { "GroupThumbnail_ChangeIdMultiple", "變更 {0} 個群組的 ID..." },
            { "GroupThumbnail_ConfirmDelete", "確認刪除群組" },
            { "GroupThumbnail_ConfirmDeleteMessage", "確定要刪除群組 {0} 嗎？\n將移除 {1} 個物件。" },
            { "GroupThumbnail_SetTransparent", "設定群組 {0} 為透明 (Type=0)" },
            { "GroupThumbnail_SetOpaque", "設定群組 {0} 為不透明 (Type=1)" },
            { "GroupThumbnail_ClearLayer5", "清除群組 {0} 的 Layer5 設定" },

            // === Tile Cleanup Dialog ===
            { "Menu_Tools_CleanupTiles", "清理未使用的 Tiles..." },
            { "Dialog_TileCleanup_Title", "清理未使用的 Tiles" },
            { "Dialog_TileCleanup_Warning", "警告：此為危險操作！將從 tile.idx 中移除未使用的高編號 Tiles。\n建議在執行前備份整個客戶端資料夾。" },
            { "Dialog_TileCleanup_Scanning", "正在掃描所有地圖檔案，分析 Tile 使用情況..." },
            { "Dialog_TileCleanup_ScanFailed", "掃描失敗" },
            { "Dialog_TileCleanup_Summary", "掃描完成：\n• 地圖資料夾: {0} 個\n• S32/Seg 檔案: {1} 個\n• 使用中的 Tile: {2} 個\n• tile.idx 總計: {3} 個\n• 可清理項目: {4} 個 (ID > {5} 且未使用)" },
            { "Dialog_TileCleanup_ScanErrors", "掃描過程發生錯誤" },
            { "Dialog_TileCleanup_NoUnusedTiles", "(沒有符合條件的未使用 Tiles)" },
            { "Dialog_TileCleanup_CreateBackup", "建立備份檔案 (tile.idx.backup_日期時間)" },
            { "Dialog_TileCleanup_Confirm", "確認刪除" },
            { "Dialog_TileCleanup_NoSelection", "請至少選擇一個要刪除的項目" },
            { "Dialog_TileCleanup_FinalConfirm", "即將從 tile.idx 移除 {0} 個 Tile 檔案。\n\n此操作無法復原（除非有備份）！\n\n確定要繼續嗎？" },
            { "Dialog_TileCleanup_Success", "清理完成！已移除 {0} 個 Tile。\n\n備份檔案: {1}" },
            { "Dialog_TileCleanup_Failed", "清理失敗: {0}" },
            { "Dialog_TileCleanup_NoClient", "請先開啟天堂客戶端" },
        };
    }
}
