using System.Collections.Generic;

namespace L1MapViewer.Localization
{
    /// <summary>
    /// Japanese (ja-JP) string resources
    /// </summary>
    public static class Strings_jaJP
    {
        public static Dictionary<string, string> GetStrings() => new()
        {
            // === Menu Items ===
            { "Menu_File", "ファイル(&F)" },
            { "Menu_File_OpenClient", "リネージュクライアントを開いてマップを読み込む" },
            { "Menu_File_Export", "マップ通行データをエクスポート" },
            { "Menu_File_Save", "S32を保存" },
            { "Menu_File_ExportFs32", "FS32パッケージをエクスポート..." },
            { "Menu_File_Exit", "終了" },
            { "Menu_Import", "インポート" },
            { "Menu_Import_Material", "素材をインポート..." },
            { "Menu_Import_Fs32ToNewMap", "マップパッケージを新規マップにインポート..." },
            { "Menu_Edit", "編集(&E)" },
            { "Menu_Edit_Undo", "元に戻す" },
            { "Menu_Edit_Redo", "やり直し" },
            { "Menu_Edit_Copy", "コピー" },
            { "Menu_Edit_Paste", "貼り付け" },
            { "Menu_Edit_Delete", "削除" },
            { "Menu_Edit_BatchDeleteTile", "タイル一括削除..." },
            { "Menu_Edit_BatchReplaceTile", "タイル一括置換..." },
            { "Menu_View", "表示(&V)" },
            { "Menu_View_Reload", "マップを再読み込み" },
            { "Menu_View_Layers", "レイヤー" },
            { "Menu_View_Layer1", "Layer 1 地面" },
            { "Menu_View_Layer2", "Layer 2 装飾" },
            { "Menu_View_Layer4", "Layer 4 オブジェクト" },
            { "Menu_View_Layer5", "Layer 5 イベント" },
            { "Menu_View_Layer8", "Layer 8 SPR" },
            { "Menu_View_Passable", "通行性" },
            { "Menu_View_SafeZone", "安全区域" },
            { "Menu_View_CombatZone", "戦闘区域" },
            { "Menu_View_Grid", "グリッド" },
            { "Menu_View_S32Border", "S32境界" },
            { "Menu_View_Zoom", "ズーム" },
            { "Menu_View_ZoomIn", "拡大" },
            { "Menu_View_ZoomOut", "縮小" },
            { "Menu_View_Zoom100", "100%" },
            { "Menu_Tools", "ツール(&T)" },
            { "Menu_Tools_PassableEdit", "通行編集モード" },
            { "Menu_Tools_RegionEdit", "区域編集モード" },
            { "Menu_Tools_Layer5Edit", "透明編集モード" },
            { "Menu_Tools_ValidateMap", "マップの整合性を検証" },
            { "Menu_Tools_AnalyzeAttr", "属性を分析" },
            { "Menu_MapEditor", "マップエディタ" },
            { "Menu_Help", "ヘルプ(&H)" },
            { "Menu_Help_Discord", "Discordで議論する" },
            { "Menu_Help_SourceCode", "ソースコード (GitHub)" },
            { "Menu_Help_PakViewer", "PakViewer (PAKエディタ)" },
            { "Menu_Help_About", "バージョン情報..." },
            { "Menu_Language", "言語" },
            { "Menu_Export_ServerPassability", "サーバー通行データ出力" },
            { "Menu_Export_L1JFormat", "L1J 形式" },
            { "Menu_Export_DIRFormat", "DIR 形式" },
            { "Menu_Export_AllMapsL1J", "全マップ出力 (L1J)" },
            { "Menu_Export_AllMapsDIR", "全マップ出力 (DIR)" },

            // === Tab Pages ===
            { "Tab_MapPreview", "マッププレビュー" },
            { "Tab_S32Editor", "S32エディタ" },
            { "Tab_MapList", "マップリスト" },
            { "Tab_S32Files", "S32ファイル" },
            { "Placeholder_SearchMap", "マップを検索 (ID または名前)..." },

            // === Buttons - Common ===
            { "Button_OK", "OK" },
            { "Button_Cancel", "キャンセル" },
            { "Button_Preview", "プレビュー" },
            { "Button_Save", "保存" },
            { "Button_Close", "閉じる" },
            { "Button_New", "新規" },
            { "Button_Edit", "編集" },
            { "Button_Delete", "削除" },
            { "Button_Replace", "置換" },
            { "Button_ClearL7", "L7クリア" },
            { "Button_Copy", "コピー" },
            { "Button_Paste", "貼り付け" },
            { "Button_Undo", "元に戻す" },
            { "Button_Redo", "やり直し" },
            { "Button_Search", "検索" },
            { "Button_Refresh", "更新" },
            { "Button_Browse", "参照" },
            { "Button_Apply", "適用" },
            { "Button_Reset", "リセット" },

            // === Buttons - MapForm ===
            { "Button_JumpToCoord", "移動" },
            { "Button_ReloadF5", "再読み込み (F5)" },
            { "Button_SaveS32", "S32保存" },
            { "Button_AnalyzeAttr", "属性分析" },
            { "Button_SelectAll", "全選択" },
            { "Button_SelectNone", "全解除" },
            { "Button_CopySettings", "設定をコピー" },
            { "Button_CopyMapCoords", "座標をコピー" },
            { "Button_ImportFs32", "マップパックをインポート" },
            { "Label_RegionEdit", "領域編集:" },
            { "Button_EditPassable", "通行" },
            { "Button_EditLayer5", "半透明" },
            { "Button_RegionEdit", "安全/戦闘" },
            { "Button_MarketRegionEdit", "露店" },
            { "Button_MergeL2ToL1", "L2をL1に統合" },

            // === Market Region Edit ===
            { "Status_MarketRegionCancelled", "露店エリア設定モードをキャンセルしました" },
            { "Status_MarketRegionMode", "露店エリア設定モード：左クリックで選択、右クリックで露店エリアの設定/解除" },
            { "Menu_SetMarketRegion", "露店エリアに設定 ({0} セル)" },
            { "Menu_ClearMarketRegion", "露店エリアを解除 ({0} セル)" },
            { "Action_SetMarketRegion", "露店エリアに設定" },
            { "Action_ClearMarketRegion", "露店エリアを解除" },
            { "Button_ExportS32", "S32エクスポート" },
            { "Button_NewS32", "S32新規" },
            { "Button_ClearLayer7", "転送ポイントクリア" },
            { "Button_ReplaceS32", "S32置換" },
            { "Button_Details", "詳細" },
            { "Button_ClearCell", "セルクリア" },
            { "Button_CheckL1", "L1確認" },
            { "Button_CheckL2", "L2確認" },
            { "Button_CheckL3", "L3確認" },
            { "Button_CheckL4", "L4確認" },
            { "Button_CheckL5", "L5確認" },
            { "Button_CheckL6", "L6確認" },
            { "Button_CheckL7", "L7確認" },
            { "Button_CheckL8", "L8確認" },
            { "Button_ViewClipboard", "貼付" },
            { "Button_TestTile", "テスト" },
            { "Button_ClearTestTile", "クリア" },
            { "Button_More", "もっと..." },
            { "Button_ShowAll", "全て" },

            // === Labels - Tile Panel ===
            { "Label_TileList", "タイルリスト" },
            { "Label_TileListCount", "タイルリスト ({0})" },
            { "Label_RecentMaterials", "最近の素材" },
            { "Label_GroupThumbnails", "グループサムネイル" },
            { "Label_GroupThumbnailsCount", "グループサムネイル ({0})" },
            { "Label_GroupThumbnailsLoading", "グループサムネイル (読込中 {0}/{1})" },
            { "Label_GroupThumbnailsTime", "グループサムネイル ({0}) [{1}ms]" },
            { "Label_NearbyGroups", "近くのグループ" },
            { "Label_NearbyGroupsCount", "近くのグループ ({0})" },
            { "Label_NearbyGroupsLoading", "近くのグループ ({0}, L5:{1}) 読込中..." },
            { "Label_NearbyGroupsTime", "近くのグループ ({0}) [{1}ms]" },
            { "Label_SelectedAreaGroups", "選択エリアグループ" },
            { "Label_SelectedAreaGroupsCount", "選択エリアグループ ({0})" },
            { "Label_SelectedAreaAllGroups", "エリア-全て" },
            { "Placeholder_SearchTileId", "タイルID検索..." },
            { "Placeholder_SearchGroup", "検索..." },
            { "GroupMode_SelectedArea", "選択エリア" },
            { "GroupMode_SelectedAreaAll", "エリア-全て" },
            { "GroupMode_All", "全て" },
            { "Label_SearchResult", "検索結果" },

            // === Labels - Common ===
            { "Label_Name", "名前" },
            { "Label_ID", "ID" },
            { "Label_Count", "数量" },
            { "Label_Note", "メモ" },

            // === Labels - MapForm ===
            { "Label_MapId", "マップID" },
            { "Label_GameCoord", "ゲーム座標" },
            { "Label_WorldCoord", "ワールド座標" },
            { "Label_Layer1Coord", "Layer1座標" },
            { "Label_Zoom", "ズーム" },
            { "Label_S32Files", "S32ファイル" },

            // === Layer Names ===
            { "Layer_1", "レイヤー1 (床)" },
            { "Layer_2", "レイヤー2" },
            { "Layer_3", "レイヤー3 (属性)" },
            { "Layer_4", "レイヤー4 (オブジェクト)" },
            { "Layer_5", "レイヤー5 (光源)" },
            { "Layer_6", "レイヤー6" },
            { "Layer_7", "レイヤー7 (転送ポイント)" },
            { "Layer_8", "レイヤー8" },
            { "Layer_Passable", "通行性 (赤青)" },
            { "Layer_Grid", "グリッド表示" },
            { "Layer_S32Border", "S32境界" },
            { "Layer_SafeZones", "安全エリア" },
            { "Layer_CombatZones", "戦闘エリア" },
            { "Layer_MarketZones", "商店エリア" },
            { "Layer_CombatArea", "戦闘エリア" },
            { "Layer_Regions", "領域表示" },

            // === Floating Layer Panel (Short Labels) ===
            { "Label_Layers", "レイヤー" },
            { "Layer_FloatL1", "L1 床" },
            { "Layer_FloatL2", "L2" },
            { "Layer_FloatL4", "L4 物件" },
            { "Layer_FloatL5", "L5 透明" },
            { "Layer_FloatPassable", "通行" },
            { "Layer_FloatGrid", "グリッド" },
            { "Layer_FloatS32Border", "S32境界" },
            { "Layer_FloatSafeZones", "安全地帯" },
            { "Layer_FloatCombatZones", "戦闘地帯" },
            { "Layer_FloatMarketZones", "店舗地帯" },
            { "Layer_L8Spr", "L8 画像" },
            { "Layer_L8Marker", "L8 補助" },

            // === Hints ===
            { "Hint_MouseControls", "中クリックでドラッグ | 左クリックで選択" },

            // === Tooltips ===
            { "Tooltip_Copy", "コピー (Ctrl+C)" },
            { "Tooltip_Paste", "貼り付け (Ctrl+V)" },
            { "Tooltip_Delete", "削除 (Delete)" },
            { "Tooltip_Undo", "元に戻す (Ctrl+Z)" },
            { "Tooltip_Redo", "やり直し (Ctrl+Y)" },
            { "Tooltip_Save", "保存 (Ctrl+S)" },
            { "Tooltip_ZoomIn", "拡大" },
            { "Tooltip_ZoomOut", "縮小" },
            { "Tooltip_JumpToCoord", "ゲーム座標に移動" },
            { "Tooltip_NewS32", "新しいS32ブロックを追加" },
            { "Tooltip_ClearLayer7", "すべてのレイヤー7（転送ポイント）データをクリア" },
            { "Tooltip_ReplaceS32", "選択したS32ブロックを置換" },

            // === Message Box Titles ===
            { "Title_Error", "エラー" },
            { "Title_Info", "情報" },
            { "Title_Warning", "警告" },
            { "Title_Confirm", "確認" },
            { "Title_Success", "成功" },
            { "Title_SelectMap", "マップを選択" },
            { "Title_SelectFile", "ファイルを選択" },
            { "Title_SaveFile", "ファイルを保存" },
            { "Title_ImportMode", "インポートモードを選択" },
            { "Title_DangerConfirm", "危険な操作の確認" },

            // === Messages - Common ===
            { "Message_PleaseLoadMap", "先にマップを読み込んでください" },
            { "Message_PleaseSelectMap", "先にマップを選択してください" },
            { "Message_PleaseSelectItem", "先に項目を選択してください" },
            { "Message_SaveSuccess", "保存しました" },
            { "Message_SaveFailed", "保存に失敗しました: {0}" },
            { "Message_LoadFailed", "読み込みに失敗しました: {0}" },
            { "Message_ExportSuccess", "エクスポートしました" },
            { "Message_ExportFailed", "エクスポートに失敗しました: {0}" },
            { "Message_ImportSuccess", "インポートしました" },
            { "Message_ImportFailed", "インポートに失敗しました: {0}" },
            { "Message_ConfirmDelete", "削除してもよろしいですか？" },
            { "Message_OperationCancelled", "操作がキャンセルされました" },
            { "Message_InvalidInput", "無効な入力です" },
            { "Message_FileNotFound", "ファイルが見つかりません: {0}" },
            { "Message_NoDataToExport", "エクスポートするデータがありません" },

            // === Messages - Import Fs32 to New Map ===
            { "ImportNewMap_Title", "マップパッケージを新規マップにインポート" },
            { "ImportNewMap_SelectFile", "インポートする fs32 マップパッケージを選択" },
            { "ImportNewMap_EnterMapId", "新規マップ番号を入力してください:" },
            { "ImportNewMap_InvalidMapId", "無効なマップ番号です。数字を入力してください" },
            { "ImportNewMap_MapExists", "マップ {0} は既に存在します。既存のインポートフローを使用しますか？\n\n「はい」= そのマップを開いてパッケージをインポート\n「いいえ」= 操作をキャンセル" },
            { "ImportNewMap_CreatingFolder", "マップフォルダを作成中..." },
            { "ImportNewMap_FolderCreated", "マップフォルダを作成しました: {0}" },
            { "ImportNewMap_Importing", "マップパッケージをインポート中..." },
            { "ImportNewMap_Success", "マップパッケージを新規マップ {0} に正常にインポートしました" },
            { "ImportNewMap_Failed", "インポートに失敗しました: {0}" },
            { "ImportNewMap_PleaseOpenClient", "先にリネージュクライアントを開いてください" },

            // === Messages - MapForm ===
            { "Message_S32Saved", "S32を保存しました" },
            { "Message_S32SaveFailed", "S32の保存に失敗しました: {0}" },
            { "Message_CoordsInvalid", "座標形式が無効です" },
            { "Message_NoS32Selected", "先にS32ファイルを選択してください" },
            { "Message_ClipboardEmpty", "クリップボードは空です" },
            { "Message_CopiedToClipboard", "クリップボードにコピーしました" },
            { "Message_ExportedTo", "エクスポートしました: {0}" },

            // === Messages - FS32 Import ===
            { "Message_Fs32Info", "fs32マップパック情報：" },
            { "Message_Fs32SourceMap", "元マップ" },
            { "Message_Fs32BlockCount", "ブロック数" },
            { "Message_Fs32TileCount", "タイル数" },
            { "Message_Fs32ImportTo", "現在のマップにインポート" },
            { "Message_Fs32SelectMode", "インポートモードを選択してください：" },
            { "Message_Fs32PartialReplace", "【部分置換】同じ座標のブロックのみ上書き（推奨）" },
            { "Message_Fs32FullReplace", "【完全置換】既存ブロックを削除し、インポートしたマップを使用" },
            { "Message_Fs32PartialButton", "「はい」= 部分置換（デフォルト）" },
            { "Message_Fs32FullButton", "「いいえ」= 完全置換" },
            { "Message_Fs32CancelButton", "「キャンセル」= インポートをキャンセル" },
            { "Message_Fs32FullReplaceWarning", "⚠️ 警告：完全置換モード ⚠️\n\nこれにより現在のマップのすべての既存ブロックが削除されます！\nマップ全体が消える可能性があり、インポートされたブロックのみが残ります。\n\nこの操作は元に戻せません！\n\n続行してもよろしいですか？" },
            { "Message_Fs32ImportComplete", "インポート完了！" },
            { "Message_Fs32ImportMode", "インポートモード" },
            { "Message_Fs32FullReplaceMode", "完全置換" },
            { "Message_Fs32PartialReplaceMode", "部分置換" },
            { "Message_Fs32DeletedBlocks", "削除した既存ブロック" },
            { "Message_Fs32ImportedBlocks", "インポート成功" },
            { "Message_Fs32ImportedTiles", "インポートしたタイル" },
            { "Message_Fs32ReusedTiles", "再利用したタイル" },
            { "Message_Fs32RemappedTiles", "再マッピング" },
            { "Message_Fs32SkippedBlocks", "{0}個のブロックをスキップ" },
            { "Message_Fs32InvalidFile", "無効なfs32ファイル、またはブロックが含まれていません" },
            { "Message_Fs32SelectFile", "インポートするfs32マップパックを選択" },
            { "Message_Fs32Blocks", "個のブロック" },
            { "Message_Fs32Tiles", "個" },

            // === Abnormal Check Dialog ===
            { "AbnormalCheck_Title", "異常チェック結果" },
            { "AbnormalCheck_FoundIssues", "以下の異常が見つかりました：" },
            { "AbnormalCheck_ViewDetails", "詳細を表示しますか？" },
            { "AbnormalCheck_Layer5Issues", "• {0} 個の Layer5 項目に異常" },
            { "AbnormalCheck_InvalidTileIds", "• {0} 個の無効な TileId ({1})" },
            { "AbnormalCheck_Layer8Extended", "• {0} 個の S32 が Layer8 拡張形式を使用（合計 {1} 項目、クラッシュの可能性あり）" },
            { "AbnormalCheck_TileOverLimit", "• {0} 個の Tile が上限超過 (上限={1}, 最大={2})、表示不可またはクラッシュの原因" },
            { "AbnormalCheck_Tab_Layer5", "Layer5 異常 ({0})" },
            { "AbnormalCheck_Tab_InvalidTile", "無効 TileId ({0})" },
            { "AbnormalCheck_Tab_Layer8", "L8 拡張形式 ({0})" },
            { "AbnormalCheck_Tab_OverLimit", "Tile上限超過 ({0})" },
            { "AbnormalCheck_Layer5Summary", "以下 {0} 個の Layer5 項目に異常があります（GroupIdが存在しないか周囲に対応オブジェクトがありません）：" },
            { "AbnormalCheck_TileSummary", "{0} 個の無効な TileId (L1:{1}, L2:{2}, L4:{3})。Tile ファイルが存在しないか IndexId が範囲外です：" },
            { "AbnormalCheck_Layer8Summary", "以下 {0} 個の S32 が Layer8 拡張形式を使用（合計 {1} 項目）。拡張形式はクラッシュの原因となる可能性があります：" },
            { "AbnormalCheck_OverLimitSummary", "Tile.idx に {0} 個の Tile ID が list.til 上限 ({1}) を超過。\n最大 Tile ID: {2}。これらの Tile は表示不可またはクラッシュの原因：" },
            { "AbnormalCheck_DeselectAll", "全解除" },
            { "AbnormalCheck_ClearSelected", "選択をクリア" },
            { "AbnormalCheck_ClearAll", "すべてクリア" },
            { "AbnormalCheck_SelectL1Only", "L1のみ" },
            { "AbnormalCheck_SelectL2Only", "L2のみ" },
            { "AbnormalCheck_SelectL4Only", "L4のみ" },
            { "AbnormalCheck_ResetSelectedFormat", "選択を通常形式にリセット" },
            { "AbnormalCheck_ResetAllFormat", "すべて通常形式にリセット" },
            { "AbnormalCheck_PleaseSelectItems", "クリアする項目を選択してください" },
            { "AbnormalCheck_Notice", "お知らせ" },
            { "AbnormalCheck_ConfirmClearSelected", "選択した {0} 項目をクリアしますか？" },
            { "AbnormalCheck_ConfirmDelete", "削除確認" },
            { "AbnormalCheck_ClearedLayer5", "{0} 個の異常な Layer5 項目をクリアしました" },
            { "AbnormalCheck_ClearComplete", "クリア完了" },
            { "AbnormalCheck_ConfirmClearAll", "すべての {0} 個の異常項目をクリアしますか？" },
            { "AbnormalCheck_ConfirmDeleteAll", "全削除確認" },
            { "AbnormalCheck_ConfirmClearTiles", "選択した {0} 個の無効 Tile をクリアしますか？\n\n• Layer1: TileId を 0 に設定\n• Layer2: 項目を削除\n• Layer4: オブジェクトを削除" },
            { "AbnormalCheck_ConfirmClearAllTiles", "すべての {0} 個の無効 Tile をクリアしますか？\n\n• Layer1: TileId を 0 に設定\n• Layer2: 項目を削除\n• Layer4: オブジェクトを削除" },
            { "AbnormalCheck_ClearedTiles", "{0} 個の無効 Tile をクリアしました" },
            { "AbnormalCheck_PleaseSelectReset", "リセットする項目を選択してください" },
            { "AbnormalCheck_ConfirmResetSelected", "選択した {0} 個の S32 を通常形式にリセットしますか？\n\nこれらの S32 のすべての Layer8 項目の ExtendedData がクリアされます。" },
            { "AbnormalCheck_ConfirmReset", "リセット確認" },
            { "AbnormalCheck_ResetComplete", "{0} 個の S32 を通常形式にリセットし、{1} 項目の ExtendedData をクリアしました。\n\nS32 ファイルを保存してください。" },
            { "AbnormalCheck_ResetDone", "リセット完了" },
            { "AbnormalCheck_ConfirmResetAll", "すべての {0} 個の S32 を通常形式にリセットしますか？\n\nすべての Layer8 項目の ExtendedData がクリアされます。" },
            { "AbnormalCheck_ConfirmResetAll_Title", "全リセット確認" },
            { "AbnormalCheck_Layer8ItemCount", "[{0}] Layer8 項目数: {1}" },

            // === Status Bar ===
            { "Status_Ready", "準備完了" },
            { "Status_Loading", "読み込み中..." },
            { "Status_Collecting", "収集中" },
            { "Status_Saving", "保存中..." },
            { "Status_Exporting", "エクスポート中..." },
            { "Status_Importing", "インポート中..." },
            { "Status_DeletingBlocks", "既存ブロックを削除中..." },
            { "Status_ImportingBlocks", "ブロックをインポート中..." },
            { "Status_LoadingFs32", "fs32を読み込み中..." },
            { "Status_ReloadingMap", "マップを再読み込み中..." },
            { "Status_ImportedBlocks", "{0}個のブロックをインポートしました" },
            { "Status_Coordinates", "座標: X={0}, Y={1}" },
            { "Status_MapLoaded", "マップを読み込みました: {0}" },

            // === Form Titles ===
            { "Form_MapEditor_Title", "マップエディタ" },
            { "Form_ExportOptions_Title", "エクスポートオプション" },
            { "Form_ExportFs32_Title", "FS32マップパッケージをエクスポート" },
            { "Form_CopySettings_Title", "設定をコピー" },
            { "Form_MaterialBrowser_Title", "素材ブラウザ" },

            // === Export Options ===
            { "Export_Mode_SelectedArea", "選択領域" },
            { "Export_Mode_FullMap", "マップ全体" },
            { "Export_SelectLayers", "エクスポートするレイヤーを選択" },
            { "Export_MaterialName", "素材名" },

            // === Copy Settings Dialog ===
            { "CopySettings_Layer1_Desc", "レイヤー1 (床)" },
            { "CopySettings_Layer2_Desc", "レイヤー2 (装飾)" },
            { "CopySettings_Layer3_Desc", "レイヤー3 (属性)" },
            { "CopySettings_Layer4_Desc", "レイヤー4 (オブジェクト)" },
            { "CopySettings_Layer5_Desc", "レイヤー5 (光源)" },
            { "CopySettings_Layer6to8_Desc", "レイヤー6-8 (その他)" },
            { "CopySettings_Layer7_Desc", "レイヤー7 (ポータル)" },
            { "CopySettings_Layer8_Desc", "レイヤー8 (エフェクト)" },

            // === Material Browser ===
            { "Material_Search", "素材を検索" },
            { "Material_ChangePath", "パスを変更" },
            { "Material_UseThis", "この素材を使用" },
            { "Material_OpenFolder", "フォルダを開く" },
            { "Material_Preview", "プレビュー" },
            { "Material_NoPreview", "プレビューできません" },

            // === File Filters ===
            { "Filter_AllFiles", "すべてのファイル" },
            { "Filter_S32Files", "S32ファイル" },
            { "Filter_Fs32Files", "FS32マップパック" },
            { "Filter_ImageFiles", "画像ファイル" },
            { "Filter_JsonFiles", "JSONファイル" },

            // === Additional Dialog Strings ===
            { "Message_SelectAtLeastOneLayer", "少なくとも1つのレイヤーを選択してください" },
            { "CopySettings_SelectLayers", "コピー/削除するレイヤーを選択：" },

            // === Export Options Dialog ===
            { "Export_SaveAsMaterial", "素材として保存" },
            { "Export_Mode", "エクスポートモード" },
            { "Export_WholeMap", "マップ全体" },
            { "Export_SelectedBlocks", "選択されたブロック" },
            { "Export_SelectedRegion", "選択された領域（正確な範囲）" },
            { "Export_IncludeLayers", "含めるレイヤー" },
            { "Export_Layer1", "Layer1 床" },
            { "Export_Layer2", "Layer2 装飾" },
            { "Export_Layer3", "Layer3 属性" },
            { "Export_Layer4", "Layer4 オブジェクト" },
            { "Export_IncludeTiles", "タイルデータを含む" },
            { "Export_IncludeLayer5Events", "Layer5イベントを含む（Layer4オブジェクトと共に）" },
            { "Export_StripLayer8Ext", "Layer8拡張データを削除" },
            { "Export_Export", "エクスポート" },

            // === Material Browser Additional ===
            { "Material_OpenFile", "ファイルを開く..." },
            { "Material_Use", "使用" },
            { "Material_Library", "素材ライブラリ" },
            { "Material_Items", "個の素材" },

            // === Misc ===
            { "Misc_Yes", "はい" },
            { "Misc_No", "いいえ" },
            { "Misc_Unit_Blocks", "個のブロック" },
            { "Misc_Unit_Tiles", "個のタイル" },
            { "Misc_Unit_Pixels", "ピクセル" },
            { "Misc_Unknown", "不明" },
            { "Misc_None", "なし" },

            // === About Dialog ===
            { "About_Title", "L1MapViewer について" },
            { "About_Version", "バージョン" },
            { "About_Description", "リネージュマップエディタ - リネージュゲームマップファイルの閲覧と編集" },
            { "About_Discord", "Discord コミュニティ" },
            { "About_GitHub", "GitHub プロジェクト" },
            { "About_DiscordLink", "https://discord.gg/lineage" },
            { "About_GitHubLink", "https://github.com/tony1223/L1MapViewer" },

            // === L8 Dialog ===
            { "L8_Title", "L8 確認、編集、クリア" },
            { "L8_Summary", "選択: {0} S32 / {1} 項目 | 全体: {2} S32 / {3} 項目 | {4} 拡張形式" },
            { "L8_TabAll", "全て ({0})" },
            { "L8_TabSelected", "選択された S32 ({0})" },
            { "L8_Preview", "SPR プレビュー" },
            { "L8_SelectToPreview", "項目を選択してプレビュー" },
            { "L8_JumpToLocation", "位置に移動" },
            { "L8_FilterNoImage", "画像なし項目のみ表示" },
            { "L8_ExtendedSettings", "拡張形式設定" },
            { "L8_ExtendedInfo", "拡張形式とは、Layer8 項目に追加の 4 バイトデータが含まれることを意味します。S32 ファイルを選択後、拡張形式設定を切り替えできます：" },
            { "L8_CurrentStatus", "現在: {0}" },
            { "L8_NotSelected", "未選択" },
            { "L8_ExtendedFormat", "拡張形式" },
            { "L8_NormalFormat", "通常形式" },
            { "L8_SetExtended", "拡張に設定" },
            { "L8_SetNormal", "通常に設定" },
            { "L8_ResetAll", "すべて通常にリセット" },
            { "L8_SetExtendedDone", "{0} を拡張形式に設定しました。\nS32 ファイルを保存してください。" },
            { "L8_SetNormalDone", "{0} を通常形式に設定し、{1} 項目の ExtendedData をクリアしました。\nS32 ファイルを保存してください。" },
            { "L8_NoExtendedFiles", "拡張形式を使用する S32 ファイルがありません。" },
            { "L8_ConfirmResetAll", "すべての {0} S32 ファイルの Layer8 を通常形式にリセットしますか？\n\n注意：すべての ExtendedData フィールドがクリアされます。" },
            { "L8_ConfirmResetTitle", "リセット確認" },
            { "L8_ResetAllDone", "{0} S32 ファイルを通常形式にリセットし、{1} 項目の ExtendedData をクリアしました。\nS32 ファイルを保存してください。" },
            { "L8_Column_File", "S32ファイル" },
            { "L8_Column_Extended", "拡張" },
            { "L8_Column_SprId", "SprId" },
            { "L8_Column_Preview", "プレビュー" },
            { "L8_Column_X", "X" },
            { "L8_Column_Y", "Y" },
            { "L8_Column_ExtData", "ExtData" },
            { "L8_Yes", "はい" },
            { "L8_JumpedToLocation", "L8 項目位置に移動 ({0}, {1}) - SprId: {2}" },
            { "L8_ShowAllL8", "全L8表示" },
            { "L8_EnabledCount", "{0} 個の L8 エフェクトを有効化（合計 {1} 個）" },

            // L8 編集セクション
            { "L8_EditSection", "選択項目の編集" },
            { "L8_ApplyEdit", "適用" },
            { "L8_AddNew", "追加" },
            { "L8_SelectS32File", "S32 ファイルを選択" },
            { "L8_SelectS32ForNewItem", "Layer8 項目を追加する S32 ファイルを選択:" },
            { "L8_NoImageCount", "画像なし: {0} SPR" },

            // L8 一括置換
            { "L8_BatchReplace", "SprId 一括置換" },
            { "L8_FromSprId", "置換元 SprId:" },
            { "L8_ToSprId", "置換先:" },
            { "L8_BatchReplaceBtn", "置換" },
            { "L8_AffectsAllS32", "(全 S32 に影響)" },

            // L8 ボタン
            { "L8_SelectAll", "全選択" },
            { "L8_DeselectAll", "選択解除" },
            { "L8_DeleteChecked", "チェック項目を削除" },
            { "L8_DeleteAll", "全 L8 削除" },
            { "L8_Close", "閉じる" },

            // L8 メッセージダイアログ
            { "L8_SelectOneToEdit", "編集する項目を1つ選択してください" },
            { "L8_InvalidValue", "有効な値を入力してください" },
            { "L8_EditApplied", "変更を適用しました。S32 ファイルを保存してください。" },
            { "L8_ItemAdded", "Layer8 項目を {0} に追加しました。\n\nS32 ファイルを保存してください。" },
            { "L8_InvalidSprId", "有効な SprId を入力してください" },
            { "L8_SameSprId", "置換元と置換先の SprId が同じです" },
            { "L8_SprIdNotFound", "SprId = {0} の項目が見つかりません" },
            { "L8_ConfirmBatchReplace", "SprId = {0} の全項目 ({1} 個) を SprId = {2} に置換しますか？" },
            { "L8_ConfirmBatchReplaceTitle", "一括置換の確認" },
            { "L8_BatchReplaceComplete", "{0} 個の項目の SprId を {1} から {2} に置換しました。\n{3} 個の S32 ファイルに影響。\n\nS32 ファイルを保存してください。" },
            { "L8_BatchReplaceCompleteTitle", "一括置換完了" },
            { "L8_SelectToDelete", "削除する項目をチェックしてください" },
            { "L8_ConfirmDeleteChecked", "チェックした {0} 個の Layer8 項目を削除しますか？" },
            { "L8_ConfirmDeleteTitle", "削除の確認" },
            { "L8_DeleteComplete", "{0} 個の Layer8 項目を削除しました。\n\nS32 ファイルを保存してください。" },
            { "L8_ConfirmDeleteAll", "全 {0} 個の Layer8 項目を削除しますか？" },
            { "L8_ConfirmDeleteAllTitle", "全削除の確認" },

            // 共通タイトル
            { "Title_Done", "完了" },
            { "Common_OK", "OK" },

            // 一括タイル削除
            { "Form_BatchDeleteTile_Title", "一括タイル削除" },
            { "Menu_BatchDeleteTile", "一括タイル削除..." },
            { "BatchDeleteTile_TileIdRange", "TileId 範囲" },
            { "BatchDeleteTile_IndexIdRange", "IndexId 範囲" },
            { "BatchDeleteTile_Start", "開始" },
            { "BatchDeleteTile_End", "終了" },
            { "BatchDeleteTile_Scope", "処理範囲" },
            { "BatchDeleteTile_CurrentMap", "現在のマップ" },
            { "BatchDeleteTile_AllMaps", "全マップ (maps フォルダ)" },
            { "BatchDeleteTile_Warning", "S32 ファイルを直接変更します。先にバックアップしてください！" },
            { "BatchDeleteTile_InvalidTileIdRange", "TileId の開始値は終了値より大きくできません" },
            { "BatchDeleteTile_InvalidIndexIdRange", "IndexId の開始値は終了値より大きくできません" },
            { "BatchDeleteTile_ConfirmMessage", "以下の条件に一致するタイルを削除しますか？\n\nTileId: {0} ~ {1}\nIndexId: {2} ~ {3}\n範囲: {4}\n\nこの操作は元に戻せません！" },
            { "BatchDeleteTile_Confirm", "削除の確認" },
            { "BatchDeleteTile_NoClient", "先にリネージュクライアントを開いてください！" },
            { "BatchDeleteTile_NoMapLoaded", "先にマップを読み込んでください！" },
            { "BatchDeleteTile_NoS32Files", "処理できる S32 ファイルが見つかりません" },
            { "BatchDeleteTile_Processing", "{0} を処理中 ({1}/{2})..." },
            { "BatchDeleteTile_Result", "削除完了！\n\n削除数: {0}\n変更ファイル: {1}\n失敗ファイル: {2}" },
            { "BatchDeleteTile_Complete", "一括削除完了" },

            // === Batch Replace Tile Dialog ===
            { "Form_BatchReplaceTile_Title", "一括置換 TileId" },
            { "BatchReplaceTile_SelectLayer", "レイヤー選択" },
            { "BatchReplaceTile_Layer1", "Layer1 (床)" },
            { "BatchReplaceTile_Layer2", "Layer2 (インデックス)" },
            { "BatchReplaceTile_Layer4", "Layer4 (オブジェクト)" },
            { "BatchReplaceTile_Source", "ソース" },
            { "BatchReplaceTile_Target", "置換先" },
            { "BatchReplaceTile_MatchIndexId", "IndexId を照合" },
            { "BatchReplaceTile_ReplaceIndexId", "IndexId を置換" },
            { "BatchReplaceTile_Execute", "置換実行" },
            { "BatchReplaceTile_PreviewResult", "[{0}] {2} 個の S32 ファイルで {1} 件一致" },
            { "BatchReplaceTile_ConfirmMessage", "[{0}] で {1} を\n{2} に置換しますか？\n\n読み込み済みの全 S32 ファイルに影響します。" },
            { "BatchReplaceTile_Confirm", "置換確認" },
            { "BatchReplaceTile_Complete", "置換完了！\n{0} 件置換\n{1} 個の S32 ファイルに影響\n\n変更を保存してください。" },
            { "BatchReplaceTile_StatusComplete", "[{0}] {1} 件置換、{2} 個の S32 ファイルに影響" },
            { "BatchReplaceTile_NoMap", "先にマップを読み込んでください" },

            // === Map List Context Menu ===
            { "MapList_ExportAsFs32", "マップパッケージとしてエクスポート (fs32)..." },
            { "MapList_MapNotExist", "マップ {0} は存在しません" },
            { "MapList_LoadingMap", "マップ {0} を読み込み中..." },
            { "MapList_LoadingFiles", "マップファイルを読み込み中... ({0})" },
            { "MapList_NoMapFiles", "マップ {0} には利用可能なマップファイル (.s32 または .seg) がありません" },
            { "MapList_CreatingFs32", "fs32 ファイルを作成中..." },
            { "MapList_ExportResult", "{0} にエクスポートしました\n({1} ブロック, {2} タイル, {3} SPR)" },
            { "MapList_ExportComplete", "エクスポート完了" },
            { "MapList_ExportFailed", "エクスポート失敗: {0}" },

            // === S32 List Context Menu ===
            { "S32Menu_JumpToBlock", "このブロックへジャンプ" },
            { "S32Menu_ViewDetails", "詳細を表示" },
            { "S32Menu_ExportMapAsFs32", "マップ全体を fs32 パッケージとしてエクスポート..." },
            { "S32Menu_ExportCheckedAsFs32", "チェックした {0} ブロックを fs32 パッケージとしてエクスポート..." },
            { "S32Menu_ImportFs32", "fs32 パッケージをインポート..." },
            { "S32Menu_ClearBlockData", "⚠ ブロックデータをクリア..." },
            { "S32Menu_DeleteBlock", "⚠ このブロックを削除..." },
            { "S32Menu_DeleteCheckedBlocks", "⚠ チェックした {0} ブロックを削除..." },

            // === MiniMap Context Menu ===
            { "MiniMap_AddS32Block", "➕ ここに S32 ブロックを追加 ({0})..." },
            { "MiniMap_ImportFs32Here", "📦 ここに fs32 をインポート..." },
            { "MiniMap_EstimatedPosition", "推定位置: {0} ({1},{2})" },
            { "MiniMap_CurrentBlock", "現在のブロック: {0}" },
            { "MiniMap_TargetPosition", "ターゲット位置: {0} ({1},{2})" },
            { "MiniMap_AddS32Title", "S32 追加" },
            { "MiniMap_AddS32Confirm", "この位置に S32 ブロックを追加しますか？\n\nファイル名: {0}\nブロック座標: ({1}, {2})\nゲーム座標: ({3},{4}) ~ ({5},{6})\nパス: {7}" },

            // === Selection Context Menu ===
            { "Selection_ViewDetails", "詳細を表示..." },
            { "Selection_ExportAsFs32", "fs32 パッケージとしてエクスポート..." },
            { "Selection_SaveAsFs3p", "素材として保存 (fs3p)..." },
            { "Selection_Copy", "コピー (Ctrl+C)" },
            { "Selection_FillWithFloor", "コピーした床で選択範囲を塗りつぶす" },
            { "Selection_ClearData", "選択範囲のデータをクリア..." },
            { "Selection_ShowGroupArea", "グループエリアの位置を表示" },

            // === L5 Editor Context Menu ===
            { "L5Menu_EditItem", "この L5 項目を編集" },
            { "L5Menu_DeleteItem", "この L5 項目を削除" },

            // === Tile List Context Menu ===
            { "TileList_CopyRow", "行全体をコピー" },
            { "TileList_ViewDetails", "詳細を表示" },
            { "TileList_ExportSelectedTile", "選択したタイル画像をエクスポート" },

            // === Material Context Menu ===
            { "Material_ViewDetails", "詳細を表示..." },
            { "Material_UseMaterial", "素材を使用" },
            { "Material_Rename", "名前を変更..." },
            { "Material_CopyPath", "ファイルパスをコピー" },
            { "Material_Export", "素材をエクスポート..." },
            { "Material_Delete", "素材を削除" },

            // === Group Thumbnail Context Menu ===
            { "GroupThumbnail_GotoLocation", "位置へ移動" },
            { "GroupThumbnail_ShowCells", "グループのセルを表示" },
            { "GroupThumbnail_CopyGroup", "グループ {0} をコピー" },
            { "GroupThumbnail_DetailL4", "L4 詳細を表示 ({0} オブジェクト)" },
            { "GroupThumbnail_DeleteGroup", "グループ {0} を削除 ({1} オブジェクト)" },
            { "GroupThumbnail_SaveAsMaterial", "グループ {0} を素材として保存..." },
            { "GroupThumbnail_ChangeId", "グループ {0} の ID を変更..." },
            { "GroupThumbnail_AutoNewId", "新しいグループ ID を自動割り当て" },
            { "GroupThumbnail_AutoNewIdSeparate", "新しいグループ ID を自動割り当て（個別）" },
            { "GroupThumbnail_CopyMultiple", "{0} グループをコピー ({1} オブジェクト)" },
            { "GroupThumbnail_DeleteMultiple", "{0} グループを削除 ({1} オブジェクト)" },
            { "GroupThumbnail_SaveMultipleAsMaterial", "{0} グループを素材として保存..." },
            { "GroupThumbnail_ChangeIdMultiple", "{0} グループの ID を変更..." },
            { "GroupThumbnail_ConfirmDelete", "グループ削除の確認" },
            { "GroupThumbnail_ConfirmDeleteMessage", "グループ {0} を削除しますか？\n{1} オブジェクトが削除されます。" },
            { "GroupThumbnail_SetTransparent", "グループ {0} を透明に設定 (Type=0)" },
            { "GroupThumbnail_SetOpaque", "グループ {0} を不透明に設定 (Type=1)" },
            { "GroupThumbnail_ClearLayer5", "グループ {0} の Layer5 設定をクリア" },

            // === Map Export Dialog ===
            { "Menu_File_ExportMapImage", "マップ画像をエクスポート..." },
            { "Dialog_MapExport_Title", "マップ画像をエクスポート" },
            { "Dialog_MapExport_Layers", "レイヤーオプション" },
            { "Dialog_MapExport_Mode", "エクスポートモード" },
            { "Dialog_MapExport_SingleMap", "現在のマップ" },
            { "Dialog_MapExport_BatchAll", "すべてのマップ" },
            { "Dialog_MapExport_Scale", "画像サイズ" },
            { "Dialog_MapExport_ScaleHint", "縮小するとファイルサイズが減少、品質は無劣化" },
            { "Dialog_MapExport_Scale100", "(元のサイズ)" },
            { "Dialog_MapExport_OutputPath", "出力パス" },
            { "Dialog_MapExport_CustomMarkers", "カスタムマーカー" },
            { "Dialog_MapExport_MarkersHint", "座標リストを入力 (X, Y, 名前 - タブまたはカンマ区切り)" },
            { "Dialog_MapExport_MarkerSize", "マーカーサイズ (1=大マップ用, 10=サムネイル用)" },
            { "Dialog_MapExport_Export", "エクスポート" },
            { "Dialog_MapExport_Exporting", "エクスポート中...しばらくお待ちください" },
            { "Dialog_MapExport_Success", "エクスポート完了" },
            { "Dialog_MapExport_MaxSizeFormat", "100% = {0} x {1} (最大出力サイズ)" },
            { "Dialog_MapExport_BatchSizeHint", "一括出力時は各マップの最大サイズを自動計算" },
            { "Layer1_Name", "床" },
            { "Layer2_Name", "装飾" },
            { "Layer4_Name", "オブジェクト" },
            { "Layer8_Name", "SPR" },

            // === Tile Cleanup Dialog ===
            { "Menu_Tools_CleanupTiles", "未使用タイルをクリーンアップ..." },
            { "Dialog_TileCleanup_Title", "未使用タイルのクリーンアップ" },
            { "Dialog_TileCleanup_Warning", "警告：これは危険な操作です！tile.idx から未使用の高番号タイルを削除します。\n実行前にクライアントフォルダ全体をバックアップしてください。" },
            { "Dialog_TileCleanup_Scanning", "すべてのマップファイルをスキャンしてタイル使用状況を分析中..." },
            { "Dialog_TileCleanup_ScanFailed", "スキャン失敗" },
            { "Dialog_TileCleanup_Summary", "スキャン完了：\n• マップフォルダ: {0} 個\n• S32/Seg ファイル: {1} 個\n• 使用中のタイル: {2} 個\n• tile.idx 合計: {3} 個\n• クリーンアップ可能: {4} 個 (ID > {5} かつ未使用)" },
            { "Dialog_TileCleanup_ScanErrors", "スキャン中にエラーが発生しました" },
            { "Dialog_TileCleanup_NoUnusedTiles", "(条件に一致する未使用タイルはありません)" },
            { "Dialog_TileCleanup_CreateBackup", "バックアップファイルを作成 (tile.idx.backup_日時)" },
            { "Dialog_TileCleanup_Confirm", "削除を確認" },
            { "Dialog_TileCleanup_NoSelection", "削除する項目を少なくとも1つ選択してください" },
            { "Dialog_TileCleanup_FinalConfirm", "tile.idx から {0} 個のタイルファイルを削除しようとしています。\n\nこの操作は元に戻せません（バックアップがない限り）！\n\n続行しますか？" },
            { "Dialog_TileCleanup_Success", "クリーンアップ完了！{0} 個のタイルを削除しました。\n\nバックアップファイル: {1}" },
            { "Dialog_TileCleanup_Failed", "クリーンアップ失敗: {0}" },
            { "Dialog_TileCleanup_NoClient", "先にリネージュクライアントを開いてください" },
        };
    }
}
