using System.Collections.Generic;

namespace L1MapViewer.Localization
{
    /// <summary>
    /// English (en-US) string resources
    /// </summary>
    public static class Strings_enUS
    {
        public static Dictionary<string, string> GetStrings() => new()
        {
            // === Menu Items ===
            { "Menu_File", "File(&F)" },
            { "Menu_File_OpenClient", "Open Lineage Client to Read Map" },
            { "Menu_File_Export", "Export Map Passability Data" },
            { "Menu_File_Save", "Save S32" },
            { "Menu_File_ExportFs32", "Export FS32 Package..." },
            { "Menu_File_Exit", "Exit" },
            { "Menu_Import", "Import" },
            { "Menu_Import_Material", "Import Material..." },
            { "Menu_Import_Fs32ToNewMap", "Import Map Package to New Map..." },
            { "Menu_Edit", "Edit(&E)" },
            { "Menu_Edit_Undo", "Undo" },
            { "Menu_Edit_Redo", "Redo" },
            { "Menu_Edit_Copy", "Copy" },
            { "Menu_Edit_Paste", "Paste" },
            { "Menu_Edit_Delete", "Delete" },
            { "Menu_Edit_BatchDeleteTile", "Batch Delete Tile..." },
            { "Menu_Edit_BatchReplaceTile", "Batch Replace Tile..." },
            { "Menu_View", "View(&V)" },
            { "Menu_View_Reload", "Reload Map" },
            { "Menu_View_Layers", "Layers" },
            { "Menu_View_Layer1", "Layer 1 Floor" },
            { "Menu_View_Layer2", "Layer 2 Decoration" },
            { "Menu_View_Layer4", "Layer 4 Objects" },
            { "Menu_View_Layer5", "Layer 5 Events" },
            { "Menu_View_Layer8", "Layer 8 SPR" },
            { "Menu_View_Passable", "Passability" },
            { "Menu_View_SafeZone", "Safe Zones" },
            { "Menu_View_CombatZone", "Combat Zones" },
            { "Menu_View_Grid", "Grid" },
            { "Menu_View_S32Border", "S32 Border" },
            { "Menu_View_Zoom", "Zoom" },
            { "Menu_View_ZoomIn", "Zoom In" },
            { "Menu_View_ZoomOut", "Zoom Out" },
            { "Menu_View_Zoom100", "100%" },
            { "Menu_Tools", "Tools(&T)" },
            { "Menu_Tools_PassableEdit", "Passability Edit Mode" },
            { "Menu_Tools_RegionEdit", "Region Edit Mode" },
            { "Menu_Tools_Layer5Edit", "Transparency Edit Mode" },
            { "Menu_Tools_ValidateMap", "Validate Map Integrity" },
            { "Menu_Tools_AnalyzeAttr", "Analyze Attributes" },
            { "Menu_MapEditor", "Map Editor" },
            { "Menu_Help", "Help(&H)" },
            { "Menu_Help_Discord", "Discuss on Discord" },
            { "Menu_Help_About", "About..." },
            { "Menu_Language", "Language" },
            { "Menu_Export_ServerPassability", "Export Server Passability" },
            { "Menu_Export_L1JFormat", "L1J Format" },
            { "Menu_Export_DIRFormat", "DIR Format" },
            { "Menu_Export_AllMapsL1J", "Export All Maps (L1J)" },
            { "Menu_Export_AllMapsDIR", "Export All Maps (DIR)" },

            // === Tab Pages ===
            { "Tab_MapPreview", "Map Preview" },
            { "Tab_S32Editor", "S32 Editor" },
            { "Tab_MapList", "Map List" },
            { "Tab_S32Files", "S32 Files" },
            { "Placeholder_SearchMap", "Search map (ID or name)..." },

            // === Buttons - Common ===
            { "Button_OK", "OK" },
            { "Button_Cancel", "Cancel" },
            { "Button_Save", "Save" },
            { "Button_Close", "Close" },
            { "Button_New", "New" },
            { "Button_Edit", "Edit" },
            { "Button_Delete", "Delete" },
            { "Button_Replace", "Replace" },
            { "Button_ClearL7", "Clear L7" },
            { "Button_Copy", "Copy" },
            { "Button_Paste", "Paste" },
            { "Button_Undo", "Undo" },
            { "Button_Redo", "Redo" },
            { "Button_Search", "Search" },
            { "Button_Refresh", "Refresh" },
            { "Button_Browse", "Browse" },
            { "Button_Apply", "Apply" },
            { "Button_Reset", "Reset" },

            // === Buttons - MapForm ===
            { "Button_JumpToCoord", "Jump" },
            { "Button_ReloadF5", "Reload (F5)" },
            { "Button_SaveS32", "Save S32" },
            { "Button_AnalyzeAttr", "Analyze Attr" },
            { "Button_SelectAll", "Select All" },
            { "Button_SelectNone", "Select None" },
            { "Button_CopySettings", "Copy Settings" },
            { "Button_CopyMapCoords", "Copy Coordinates" },
            { "Button_ImportFs32", "Import Map Pack" },
            { "Button_EditPassable", "Edit Passable" },
            { "Button_EditLayer5", "Edit Transparency" },
            { "Button_RegionEdit", "Region Edit" },
            { "Button_ExportS32", "Export S32" },
            { "Button_NewS32", "New S32" },
            { "Button_ClearLayer7", "Clear Teleports" },
            { "Button_ReplaceS32", "Replace S32" },
            { "Button_Details", "Details" },
            { "Button_ClearCell", "Clear Cell" },
            { "Button_CheckL1", "Check L1" },
            { "Button_CheckL2", "Check L2" },
            { "Button_CheckL3", "Check L3" },
            { "Button_CheckL4", "Check L4" },
            { "Button_CheckL5", "Check L5" },
            { "Button_CheckL6", "Check L6" },
            { "Button_CheckL7", "Check L7" },
            { "Button_CheckL8", "Check L8" },
            { "Button_ViewClipboard", "Clip" },
            { "Button_TestTile", "Test" },
            { "Button_ClearTestTile", "Clear" },
            { "Button_More", "More..." },
            { "Button_ShowAll", "All" },

            // === Labels - Tile Panel ===
            { "Label_TileList", "Tile List" },
            { "Label_TileListCount", "Tile List ({0})" },
            { "Label_RecentMaterials", "Recent Materials" },
            { "Label_GroupThumbnails", "Group Thumbnails" },
            { "Label_GroupThumbnailsCount", "Group Thumbnails ({0})" },
            { "Label_GroupThumbnailsLoading", "Group Thumbnails (Loading {0}/{1})" },
            { "Label_GroupThumbnailsTime", "Group Thumbnails ({0}) [{1}ms]" },
            { "Label_NearbyGroups", "Nearby Groups" },
            { "Label_NearbyGroupsCount", "Nearby Groups ({0})" },
            { "Label_NearbyGroupsLoading", "Nearby Groups ({0}, L5:{1}) Loading..." },
            { "Label_NearbyGroupsTime", "Nearby Groups ({0}) [{1}ms]" },
            { "Label_SelectedAreaGroups", "Selected Area Groups" },
            { "Label_SelectedAreaGroupsCount", "Selected Area Groups ({0})" },
            { "Label_SelectedAreaAllGroups", "Area-All" },
            { "Placeholder_SearchTileId", "Search TileId..." },
            { "Placeholder_SearchGroup", "Search..." },
            { "GroupMode_SelectedArea", "Selected" },
            { "GroupMode_SelectedAreaAll", "Area-All" },
            { "GroupMode_All", "All" },
            { "Label_SearchResult", "Search Results" },

            // === Labels - Common ===
            { "Label_Name", "Name" },
            { "Label_ID", "ID" },
            { "Label_Count", "Count" },
            { "Label_Note", "Note" },

            // === Labels - MapForm ===
            { "Label_MapId", "Map ID" },
            { "Label_GameCoord", "Game Coordinates" },
            { "Label_WorldCoord", "World Coordinates" },
            { "Label_Layer1Coord", "Layer1 Coordinates" },
            { "Label_Zoom", "Zoom" },
            { "Label_S32Files", "S32 Files" },

            // === Layer Names ===
            { "Layer_1", "Layer 1 (Floor)" },
            { "Layer_2", "Layer 2" },
            { "Layer_3", "Layer 3 (Attributes)" },
            { "Layer_4", "Layer 4 (Objects)" },
            { "Layer_5", "Layer 5 (Lighting)" },
            { "Layer_6", "Layer 6" },
            { "Layer_7", "Layer 7 (Teleports)" },
            { "Layer_8", "Layer 8" },
            { "Layer_Passable", "Passability (Red/Blue)" },
            { "Layer_Grid", "Show Grid" },
            { "Layer_S32Border", "S32 Borders" },
            { "Layer_CombatArea", "Combat Area" },
            { "Layer_Regions", "Show Regions" },

            // === Floating Layer Panel (Short Labels) ===
            { "Label_Layers", "Layers" },
            { "Layer_FloatL1", "L1 Floor" },
            { "Layer_FloatL2", "L2" },
            { "Layer_FloatL4", "L4 Objects" },
            { "Layer_FloatL5", "L5 Transp" },
            { "Layer_FloatPassable", "Pass" },
            { "Layer_FloatGrid", "Grid" },
            { "Layer_FloatS32Border", "S32 Border" },
            { "Layer_FloatSafeZones", "Safe Zone" },
            { "Layer_FloatCombatZones", "Combat" },
            { "Layer_L8Spr", "L8 SPR" },
            { "Layer_L8Marker", "L8 Marker" },

            // === Hints ===
            { "Hint_MouseControls", "Middle-click to drag | Left-click to select" },

            // === Tooltips ===
            { "Tooltip_Copy", "Copy (Ctrl+C)" },
            { "Tooltip_Paste", "Paste (Ctrl+V)" },
            { "Tooltip_Delete", "Delete (Delete)" },
            { "Tooltip_Undo", "Undo (Ctrl+Z)" },
            { "Tooltip_Redo", "Redo (Ctrl+Y)" },
            { "Tooltip_Save", "Save (Ctrl+S)" },
            { "Tooltip_ZoomIn", "Zoom In" },
            { "Tooltip_ZoomOut", "Zoom Out" },
            { "Tooltip_JumpToCoord", "Jump to Game Coordinates" },
            { "Tooltip_NewS32", "Add New S32 Block" },
            { "Tooltip_ClearLayer7", "Clear All Layer 7 (Teleport) Data" },
            { "Tooltip_ReplaceS32", "Replace Selected S32 Block" },

            // === Message Box Titles ===
            { "Title_Error", "Error" },
            { "Title_Info", "Information" },
            { "Title_Warning", "Warning" },
            { "Title_Confirm", "Confirm" },
            { "Title_Success", "Success" },
            { "Title_SelectMap", "Select Map" },
            { "Title_SelectFile", "Select File" },
            { "Title_SaveFile", "Save File" },
            { "Title_ImportMode", "Select Import Mode" },
            { "Title_DangerConfirm", "Dangerous Operation Confirmation" },

            // === Messages - Common ===
            { "Message_PleaseLoadMap", "Please load a map first" },
            { "Message_PleaseSelectMap", "Please select a map first" },
            { "Message_PleaseSelectItem", "Please select an item first" },
            { "Message_SaveSuccess", "Saved successfully" },
            { "Message_SaveFailed", "Failed to save: {0}" },
            { "Message_LoadFailed", "Failed to load: {0}" },
            { "Message_ExportSuccess", "Exported successfully" },
            { "Message_ExportFailed", "Failed to export: {0}" },
            { "Message_ImportSuccess", "Imported successfully" },
            { "Message_ImportFailed", "Failed to import: {0}" },
            { "Message_ConfirmDelete", "Are you sure you want to delete?" },
            { "Message_OperationCancelled", "Operation cancelled" },
            { "Message_InvalidInput", "Invalid input" },
            { "Message_FileNotFound", "File not found: {0}" },
            { "Message_NoDataToExport", "No data to export" },

            // === Messages - Import Fs32 to New Map ===
            { "ImportNewMap_Title", "Import Map Package to New Map" },
            { "ImportNewMap_SelectFile", "Select fs32 map package to import" },
            { "ImportNewMap_EnterMapId", "Enter new map number:" },
            { "ImportNewMap_InvalidMapId", "Invalid map number. Please enter a number" },
            { "ImportNewMap_MapExists", "Map {0} already exists. Do you want to use the existing import flow?\n\nClick \"Yes\" to open that map and import the package\nClick \"No\" to cancel" },
            { "ImportNewMap_CreatingFolder", "Creating map folder..." },
            { "ImportNewMap_FolderCreated", "Map folder created: {0}" },
            { "ImportNewMap_Importing", "Importing map package..." },
            { "ImportNewMap_Success", "Map package successfully imported to new map {0}" },
            { "ImportNewMap_Failed", "Import failed: {0}" },
            { "ImportNewMap_PleaseOpenClient", "Please open a Lineage client first" },

            // === Messages - MapForm ===
            { "Message_S32Saved", "S32 saved" },
            { "Message_S32SaveFailed", "Failed to save S32: {0}" },
            { "Message_CoordsInvalid", "Invalid coordinate format" },
            { "Message_NoS32Selected", "Please select an S32 file first" },
            { "Message_ClipboardEmpty", "Clipboard is empty" },
            { "Message_CopiedToClipboard", "Copied to clipboard" },
            { "Message_ExportedTo", "Successfully exported to: {0}" },

            // === Messages - FS32 Import ===
            { "Message_Fs32Info", "fs32 Map Pack Info:" },
            { "Message_Fs32SourceMap", "Source Map" },
            { "Message_Fs32BlockCount", "Block Count" },
            { "Message_Fs32TileCount", "Tile Count" },
            { "Message_Fs32ImportTo", "Will import to current map" },
            { "Message_Fs32SelectMode", "Please select import mode:" },
            { "Message_Fs32PartialReplace", "[Partial Replace] Only overwrite blocks at same coordinates (Recommended)" },
            { "Message_Fs32FullReplace", "[Full Replace] Delete existing blocks, use imported map entirely" },
            { "Message_Fs32PartialButton", "Press 'Yes' = Partial Replace (Default)" },
            { "Message_Fs32FullButton", "Press 'No' = Full Replace" },
            { "Message_Fs32CancelButton", "Press 'Cancel' = Cancel Import" },
            { "Message_Fs32FullReplaceWarning", "⚠️ Warning: Full Replace Mode ⚠️\n\nThis will delete ALL existing blocks in the current map!\nThe entire map may disappear, leaving only the imported blocks.\n\nThis operation cannot be undone!\n\nAre you sure you want to continue?" },
            { "Message_Fs32ImportComplete", "Import Complete!" },
            { "Message_Fs32ImportMode", "Import Mode" },
            { "Message_Fs32FullReplaceMode", "Full Replace" },
            { "Message_Fs32PartialReplaceMode", "Partial Replace" },
            { "Message_Fs32DeletedBlocks", "Deleted Existing Blocks" },
            { "Message_Fs32ImportedBlocks", "Successfully Imported" },
            { "Message_Fs32ImportedTiles", "Imported Tiles" },
            { "Message_Fs32ReusedTiles", "Reused Tiles" },
            { "Message_Fs32RemappedTiles", "Remapped" },
            { "Message_Fs32SkippedBlocks", "Skipped {0} blocks" },
            { "Message_Fs32InvalidFile", "Invalid fs32 file or contains no blocks" },
            { "Message_Fs32SelectFile", "Select fs32 map pack to import" },
            { "Message_Fs32Blocks", "blocks" },
            { "Message_Fs32Tiles", "tiles" },

            // === Abnormal Check Dialog ===
            { "AbnormalCheck_Title", "Abnormal Check Results" },
            { "AbnormalCheck_FoundIssues", "Found the following issues:" },
            { "AbnormalCheck_ViewDetails", "Do you want to view details?" },
            { "AbnormalCheck_Layer5Issues", "• {0} Layer5 items abnormal" },
            { "AbnormalCheck_InvalidTileIds", "• {0} invalid TileIds ({1})" },
            { "AbnormalCheck_Layer8Extended", "• {0} S32 files use Layer8 extended format ({1} items total, may cause crashes)" },
            { "AbnormalCheck_TileOverLimit", "• {0} Tiles over limit (limit={1}, max={2}), cannot display or may crash" },
            { "AbnormalCheck_Tab_Layer5", "Layer5 Issues ({0})" },
            { "AbnormalCheck_Tab_InvalidTile", "Invalid TileId ({0})" },
            { "AbnormalCheck_Tab_Layer8", "L8 Extended ({0})" },
            { "AbnormalCheck_Tab_OverLimit", "Tile Over Limit ({0})" },
            { "AbnormalCheck_Layer5Summary", "The following {0} Layer5 items are abnormal (GroupId doesn't exist or no matching object within 1 cell):" },
            { "AbnormalCheck_TileSummary", "Found {0} invalid TileIds (L1:{1}, L2:{2}, L4:{3}). Tile file doesn't exist or IndexId out of range:" },
            { "AbnormalCheck_Layer8Summary", "The following {0} S32 files use Layer8 extended format ({1} items total). Extended format may cause game crashes:" },
            { "AbnormalCheck_OverLimitSummary", "Tile.idx has {0} Tile IDs exceeding list.til limit ({1}).\nMax Tile ID: {2}. These Tiles cannot display or may cause crashes:" },
            { "AbnormalCheck_DeselectAll", "Deselect All" },
            { "AbnormalCheck_ClearSelected", "Clear Selected" },
            { "AbnormalCheck_ClearAll", "Clear All" },
            { "AbnormalCheck_SelectL1Only", "L1 Only" },
            { "AbnormalCheck_SelectL2Only", "L2 Only" },
            { "AbnormalCheck_SelectL4Only", "L4 Only" },
            { "AbnormalCheck_ResetSelectedFormat", "Reset Selected to Normal" },
            { "AbnormalCheck_ResetAllFormat", "Reset All to Normal" },
            { "AbnormalCheck_PleaseSelectItems", "Please select items to clear first" },
            { "AbnormalCheck_Notice", "Notice" },
            { "AbnormalCheck_ConfirmClearSelected", "Are you sure you want to clear {0} selected items?" },
            { "AbnormalCheck_ConfirmDelete", "Confirm Delete" },
            { "AbnormalCheck_ClearedLayer5", "Cleared {0} abnormal Layer5 items" },
            { "AbnormalCheck_ClearComplete", "Clear Complete" },
            { "AbnormalCheck_ConfirmClearAll", "Are you sure you want to clear all {0} abnormal items?" },
            { "AbnormalCheck_ConfirmDeleteAll", "Confirm Delete All" },
            { "AbnormalCheck_ConfirmClearTiles", "Are you sure you want to clear {0} selected invalid Tiles?\n\n• Layer1: Set TileId to 0\n• Layer2: Remove item\n• Layer4: Remove object" },
            { "AbnormalCheck_ConfirmClearAllTiles", "Are you sure you want to clear all {0} invalid Tiles?\n\n• Layer1: Set TileId to 0\n• Layer2: Remove item\n• Layer4: Remove object" },
            { "AbnormalCheck_ClearedTiles", "Cleared {0} invalid Tiles" },
            { "AbnormalCheck_PleaseSelectReset", "Please select items to reset first" },
            { "AbnormalCheck_ConfirmResetSelected", "Are you sure you want to reset {0} selected S32 to normal format?\n\nThis will clear ExtendedData from all Layer8 items in these S32." },
            { "AbnormalCheck_ConfirmReset", "Confirm Reset" },
            { "AbnormalCheck_ResetComplete", "Reset {0} S32 files to normal format, cleared ExtendedData from {1} items.\n\nPlease remember to save S32 files." },
            { "AbnormalCheck_ResetDone", "Reset Complete" },
            { "AbnormalCheck_ConfirmResetAll", "Are you sure you want to reset all {0} S32 to normal format?\n\nThis will clear ExtendedData from all Layer8 items." },
            { "AbnormalCheck_ConfirmResetAll_Title", "Confirm Reset All" },
            { "AbnormalCheck_Layer8ItemCount", "[{0}] Layer8 items: {1}" },

            // === Status Bar ===
            { "Status_Ready", "Ready" },
            { "Status_Loading", "Loading..." },
            { "Status_Collecting", "Collecting" },
            { "Status_Saving", "Saving..." },
            { "Status_Exporting", "Exporting..." },
            { "Status_Importing", "Importing..." },
            { "Status_DeletingBlocks", "Deleting existing blocks..." },
            { "Status_ImportingBlocks", "Importing blocks..." },
            { "Status_LoadingFs32", "Loading fs32..." },
            { "Status_ReloadingMap", "Reloading map..." },
            { "Status_ImportedBlocks", "Imported {0} blocks" },
            { "Status_Coordinates", "Coordinates: X={0}, Y={1}" },
            { "Status_MapLoaded", "Map loaded: {0}" },

            // === Form Titles ===
            { "Form_MapEditor_Title", "Map Editor" },
            { "Form_ExportOptions_Title", "Export Options" },
            { "Form_ExportFs32_Title", "Export FS32 Map Package" },
            { "Form_CopySettings_Title", "Copy Settings" },
            { "Form_MaterialBrowser_Title", "Material Browser" },

            // === Export Options ===
            { "Export_Mode_SelectedArea", "Selected Area" },
            { "Export_Mode_FullMap", "Full Map" },
            { "Export_SelectLayers", "Select Layers to Export" },
            { "Export_MaterialName", "Material Name" },

            // === Copy Settings Dialog ===
            { "CopySettings_Layer1_Desc", "Layer 1 (Floor)" },
            { "CopySettings_Layer2_Desc", "Layer 2 (Decoration)" },
            { "CopySettings_Layer3_Desc", "Layer 3 (Attributes)" },
            { "CopySettings_Layer4_Desc", "Layer 4 (Objects)" },
            { "CopySettings_Layer5_Desc", "Layer 5 (Lighting)" },
            { "CopySettings_Layer6to8_Desc", "Layer 6-8 (Other)" },
            { "CopySettings_Layer7_Desc", "Layer 7 (Portals)" },
            { "CopySettings_Layer8_Desc", "Layer 8 (Effects)" },

            // === Material Browser ===
            { "Material_Search", "Search Material" },
            { "Material_ChangePath", "Change Path" },
            { "Material_UseThis", "Use This Material" },
            { "Material_OpenFolder", "Open Containing Folder" },
            { "Material_Preview", "Preview" },
            { "Material_NoPreview", "Cannot Preview" },

            // === File Filters ===
            { "Filter_AllFiles", "All Files" },
            { "Filter_S32Files", "S32 Files" },
            { "Filter_Fs32Files", "FS32 Map Pack" },
            { "Filter_ImageFiles", "Image Files" },
            { "Filter_JsonFiles", "JSON Files" },

            // === Additional Dialog Strings ===
            { "Message_SelectAtLeastOneLayer", "Please select at least one layer" },
            { "CopySettings_SelectLayers", "Select layers to copy/delete:" },

            // === Export Options Dialog ===
            { "Export_SaveAsMaterial", "Save as Material" },
            { "Export_Mode", "Export Mode" },
            { "Export_WholeMap", "Whole Map" },
            { "Export_SelectedBlocks", "Selected Blocks" },
            { "Export_SelectedRegion", "Selected Region (Exact Range)" },
            { "Export_IncludeLayers", "Include Layers" },
            { "Export_Layer1", "Layer1 Floor" },
            { "Export_Layer2", "Layer2 Decoration" },
            { "Export_Layer3", "Layer3 Attributes" },
            { "Export_Layer4", "Layer4 Objects" },
            { "Export_IncludeTiles", "Include Tile Data" },
            { "Export_IncludeLayer5Events", "Include Layer5 Events (with Layer4 Objects)" },
            { "Export_StripLayer8Ext", "Remove Layer8 Extended Data" },
            { "Export_Export", "Export" },

            // === Material Browser Additional ===
            { "Material_OpenFile", "Open File..." },
            { "Material_Use", "Use" },
            { "Material_Library", "Material Library" },
            { "Material_Items", "materials" },

            // === Misc ===
            { "Misc_Yes", "Yes" },
            { "Misc_No", "No" },
            { "Misc_Unit_Blocks", "blocks" },
            { "Misc_Unit_Tiles", "tiles" },
            { "Misc_Unit_Pixels", "pixels" },
            { "Misc_Unknown", "Unknown" },
            { "Misc_None", "None" },

            // === About Dialog ===
            { "About_Title", "About L1MapViewer" },
            { "About_Version", "Version" },
            { "About_Description", "Lineage Map Editor - View and edit Lineage game map files" },
            { "About_Discord", "Discord Community" },
            { "About_GitHub", "GitHub Project" },
            { "About_DiscordLink", "https://discord.gg/lineage" },
            { "About_GitHubLink", "https://github.com/tony1223/L1MapViewer" },

            // === L8 Dialog ===
            { "L8_Title", "L8 Check, Edit & Clear" },
            { "L8_Summary", "Selected: {0} S32 / {1} items | All: {2} S32 / {3} items | {4} extended format" },
            { "L8_TabAll", "All ({0})" },
            { "L8_TabSelected", "Selected S32 ({0})" },
            { "L8_Preview", "SPR Preview" },
            { "L8_SelectToPreview", "Select item to preview" },
            { "L8_JumpToLocation", "Jump to Location" },
            { "L8_FilterNoImage", "Show only items without image" },
            { "L8_ExtendedSettings", "Extended Format Settings" },
            { "L8_ExtendedInfo", "Extended format means Layer8 items contain additional 4 bytes of data. After selecting an S32 file, you can toggle its extended format setting:" },
            { "L8_CurrentStatus", "Current: {0}" },
            { "L8_NotSelected", "Not Selected" },
            { "L8_ExtendedFormat", "Extended Format" },
            { "L8_NormalFormat", "Normal Format" },
            { "L8_SetExtended", "Set Extended" },
            { "L8_SetNormal", "Set Normal" },
            { "L8_ResetAll", "Reset All to Normal" },
            { "L8_SetExtendedDone", "Set {0} to extended format.\nPlease remember to save S32 file." },
            { "L8_SetNormalDone", "Set {0} to normal format and cleared ExtendedData from {1} items.\nPlease remember to save S32 file." },
            { "L8_NoExtendedFiles", "No S32 files using extended format." },
            { "L8_ConfirmResetAll", "Are you sure you want to reset all {0} S32 files' Layer8 to normal format?\n\nNote: This will clear all ExtendedData fields." },
            { "L8_ConfirmResetTitle", "Confirm Reset" },
            { "L8_ResetAllDone", "Reset {0} S32 files to normal format and cleared ExtendedData from {1} items.\nPlease remember to save S32 files." },
            { "L8_Column_File", "S32 File" },
            { "L8_Column_Extended", "Extended" },
            { "L8_Column_SprId", "SprId" },
            { "L8_Column_Preview", "Preview" },
            { "L8_Column_X", "X" },
            { "L8_Column_Y", "Y" },
            { "L8_Column_ExtData", "ExtData" },
            { "L8_Yes", "Yes" },
            { "L8_JumpedToLocation", "Jumped to L8 item location ({0}, {1}) - SprId: {2}" },
            { "L8_ShowAllL8", "Show All L8" },
            { "L8_EnabledCount", "Enabled {0} L8 effects (total {1})" },

            // L8 Edit Section
            { "L8_EditSection", "Edit Selected Item" },
            { "L8_ApplyEdit", "Apply" },
            { "L8_AddNew", "Add" },
            { "L8_SelectS32File", "Select S32 File" },
            { "L8_SelectS32ForNewItem", "Select S32 file to add Layer8 item:" },
            { "L8_NoImageCount", "Items without image: {0} SPR" },

            // L8 Batch Replace
            { "L8_BatchReplace", "Batch Replace SprId" },
            { "L8_FromSprId", "From SprId:" },
            { "L8_ToSprId", "To:" },
            { "L8_BatchReplaceBtn", "Replace" },
            { "L8_AffectsAllS32", "(Affects all S32)" },

            // L8 Buttons
            { "L8_SelectAll", "Select All" },
            { "L8_DeselectAll", "Deselect All" },
            { "L8_DeleteChecked", "Delete Checked" },
            { "L8_DeleteAll", "Delete All L8" },
            { "L8_Close", "Close" },

            // L8 Message Dialogs
            { "L8_SelectOneToEdit", "Please select one item to edit" },
            { "L8_InvalidValue", "Please enter valid values" },
            { "L8_EditApplied", "Changes applied. Please remember to save S32 file." },
            { "L8_ItemAdded", "Layer8 item added to {0}.\n\nPlease remember to save S32 file." },
            { "L8_InvalidSprId", "Please enter a valid SprId value" },
            { "L8_SameSprId", "Source and target SprId are the same" },
            { "L8_SprIdNotFound", "No items found with SprId = {0}" },
            { "L8_ConfirmBatchReplace", "Replace all items with SprId = {0} ({1} items) to SprId = {2}?" },
            { "L8_ConfirmBatchReplaceTitle", "Confirm Batch Replace" },
            { "L8_BatchReplaceComplete", "Replaced {0} items' SprId from {1} to {2}.\nAffected {3} S32 files.\n\nPlease remember to save S32 files." },
            { "L8_BatchReplaceCompleteTitle", "Batch Replace Complete" },
            { "L8_SelectToDelete", "Please check items to delete first" },
            { "L8_ConfirmDeleteChecked", "Delete {0} checked Layer8 items?" },
            { "L8_ConfirmDeleteTitle", "Confirm Delete" },
            { "L8_DeleteComplete", "Deleted {0} Layer8 items.\n\nPlease remember to save S32 files." },
            { "L8_ConfirmDeleteAll", "Delete all {0} Layer8 items?" },
            { "L8_ConfirmDeleteAllTitle", "Confirm Delete All" },

            // Common Titles
            { "Title_Done", "Done" },
            { "Common_OK", "OK" },

            // Batch Delete Tile
            { "Form_BatchDeleteTile_Title", "Batch Delete Tiles" },
            { "Menu_BatchDeleteTile", "Batch Delete Tiles..." },
            { "BatchDeleteTile_TileIdRange", "TileId Range" },
            { "BatchDeleteTile_IndexIdRange", "IndexId Range" },
            { "BatchDeleteTile_Start", "Start" },
            { "BatchDeleteTile_End", "End" },
            { "BatchDeleteTile_Scope", "Scope" },
            { "BatchDeleteTile_CurrentMap", "Current Map" },
            { "BatchDeleteTile_AllMaps", "All Maps (maps folder)" },
            { "BatchDeleteTile_Warning", "This will modify S32 files directly. Please backup first!" },
            { "BatchDeleteTile_InvalidTileIdRange", "TileId start cannot be greater than end" },
            { "BatchDeleteTile_InvalidIndexIdRange", "IndexId start cannot be greater than end" },
            { "BatchDeleteTile_ConfirmMessage", "Delete tiles matching the following criteria?\n\nTileId: {0} ~ {1}\nIndexId: {2} ~ {3}\nScope: {4}\n\nThis cannot be undone!" },
            { "BatchDeleteTile_Confirm", "Confirm Delete" },
            { "BatchDeleteTile_NoClient", "Please open Lineage client first!" },
            { "BatchDeleteTile_NoMapLoaded", "Please load a map first!" },
            { "BatchDeleteTile_NoS32Files", "No S32 files found to process" },
            { "BatchDeleteTile_Processing", "Processing {0} ({1}/{2})..." },
            { "BatchDeleteTile_Result", "Delete complete!\n\nDeleted: {0}\nModified files: {1}\nFailed files: {2}" },
            { "BatchDeleteTile_Complete", "Batch Delete Complete" },

            // === Batch Replace Tile Dialog ===
            { "Form_BatchReplaceTile_Title", "Batch Replace TileId" },
            { "BatchReplaceTile_SelectLayer", "Select Layer" },
            { "BatchReplaceTile_Layer1", "Layer1 (Floor)" },
            { "BatchReplaceTile_Layer2", "Layer2 (Index)" },
            { "BatchReplaceTile_Layer4", "Layer4 (Object)" },
            { "BatchReplaceTile_Source", "Source" },
            { "BatchReplaceTile_Target", "Replace With" },
            { "BatchReplaceTile_MatchIndexId", "Match IndexId" },
            { "BatchReplaceTile_ReplaceIndexId", "Replace IndexId" },
            { "BatchReplaceTile_Execute", "Execute" },
            { "BatchReplaceTile_PreviewResult", "[{0}] Found {1} matches in {2} S32 files" },
            { "BatchReplaceTile_ConfirmMessage", "Are you sure you want to replace all {1}\nwith {2} in [{0}]?\n\nThis will affect all loaded S32 files." },
            { "BatchReplaceTile_Confirm", "Confirm Replace" },
            { "BatchReplaceTile_Complete", "Replace complete!\nReplaced {0} items\nAffected {1} S32 files\n\nPlease remember to save changes." },
            { "BatchReplaceTile_StatusComplete", "[{0}] Replaced {1} items, affected {2} S32 files" },
            { "BatchReplaceTile_NoMap", "Please load a map first" },

            // === Map List Context Menu ===
            { "MapList_ExportAsFs32", "Export as Map Package (fs32)..." },
            { "MapList_MapNotExist", "Map {0} does not exist" },
            { "MapList_LoadingMap", "Loading map {0}..." },
            { "MapList_LoadingFiles", "Loading map files... ({0})" },
            { "MapList_NoMapFiles", "Map {0} has no available map files (.s32 or .seg)" },
            { "MapList_CreatingFs32", "Creating fs32 file..." },
            { "MapList_ExportResult", "Exported to {0}\n({1} blocks, {2} tiles, {3} SPR)" },
            { "MapList_ExportComplete", "Export Complete" },
            { "MapList_ExportFailed", "Export failed: {0}" },

            // === S32 List Context Menu ===
            { "S32Menu_JumpToBlock", "Jump to this block" },
            { "S32Menu_ViewDetails", "View details" },
            { "S32Menu_ExportMapAsFs32", "Export entire map as fs32 package..." },
            { "S32Menu_ExportCheckedAsFs32", "Export {0} checked blocks as fs32 package..." },
            { "S32Menu_ImportFs32", "Import fs32 package..." },
            { "S32Menu_ClearBlockData", "⚠ Clear block data..." },
            { "S32Menu_DeleteBlock", "⚠ Delete this block..." },
            { "S32Menu_DeleteCheckedBlocks", "⚠ Delete {0} checked blocks..." },

            // === MiniMap Context Menu ===
            { "MiniMap_AddS32Block", "➕ Add S32 block here ({0})..." },
            { "MiniMap_ImportFs32Here", "📦 Import fs32 here..." },
            { "MiniMap_EstimatedPosition", "Estimated position: {0} ({1},{2})" },
            { "MiniMap_CurrentBlock", "Current block: {0}" },
            { "MiniMap_TargetPosition", "Target position: {0} ({1},{2})" },
            { "MiniMap_AddS32Title", "Add S32" },
            { "MiniMap_AddS32Confirm", "Add S32 block at this position?\n\nFilename: {0}\nBlock coordinates: ({1}, {2})\nGame coordinates: ({3},{4}) ~ ({5},{6})\nPath: {7}" },

            // === Selection Context Menu ===
            { "Selection_ViewDetails", "View details..." },
            { "Selection_ExportAsFs32", "Export as fs32 package..." },
            { "Selection_SaveAsFs3p", "Save as material (fs3p)..." },
            { "Selection_Copy", "Copy (Ctrl+C)" },
            { "Selection_FillWithFloor", "Fill selection with copied floor" },
            { "Selection_ClearData", "Clear selection data..." },
            { "Selection_ShowGroupArea", "Show group area location" },

            // === L5 Editor Context Menu ===
            { "L5Menu_EditItem", "Edit this L5 item" },
            { "L5Menu_DeleteItem", "Delete this L5 item" },

            // === Tile List Context Menu ===
            { "TileList_CopyRow", "Copy entire row" },
            { "TileList_ViewDetails", "View details" },
            { "TileList_ExportSelectedTile", "Export selected tile image" },

            // === Material Context Menu ===
            { "Material_ViewDetails", "View details..." },
            { "Material_UseMaterial", "Use material" },
            { "Material_Rename", "Rename..." },
            { "Material_CopyPath", "Copy file path" },
            { "Material_Export", "Export material..." },
            { "Material_Delete", "Delete material" },

            // === Group Thumbnail Context Menu ===
            { "GroupThumbnail_GotoLocation", "Go to location" },
            { "GroupThumbnail_ShowCells", "Show group cells" },

            // === Tile Cleanup Dialog ===
            { "Menu_Tools_CleanupTiles", "Cleanup Unused Tiles..." },
            { "Dialog_TileCleanup_Title", "Cleanup Unused Tiles" },
            { "Dialog_TileCleanup_Warning", "WARNING: This is a dangerous operation! It will remove unused high-ID tiles from tile.idx.\nPlease backup your entire client folder before proceeding." },
            { "Dialog_TileCleanup_Scanning", "Scanning all map files to analyze tile usage..." },
            { "Dialog_TileCleanup_ScanFailed", "Scan failed" },
            { "Dialog_TileCleanup_Summary", "Scan complete:\n• Map folders: {0}\n• S32/Seg files: {1}\n• Tiles in use: {2}\n• Total in tile.idx: {3}\n• Can be cleaned: {4} (ID > {5} and unused)" },
            { "Dialog_TileCleanup_ScanErrors", "Errors occurred during scan" },
            { "Dialog_TileCleanup_NoUnusedTiles", "(No unused tiles matching criteria)" },
            { "Dialog_TileCleanup_CreateBackup", "Create backup file (tile.idx.backup_timestamp)" },
            { "Dialog_TileCleanup_Confirm", "Confirm Delete" },
            { "Dialog_TileCleanup_NoSelection", "Please select at least one item to delete" },
            { "Dialog_TileCleanup_FinalConfirm", "About to remove {0} tile files from tile.idx.\n\nThis operation cannot be undone (unless you have a backup)!\n\nAre you sure you want to continue?" },
            { "Dialog_TileCleanup_Success", "Cleanup complete! Removed {0} tiles.\n\nBackup file: {1}" },
            { "Dialog_TileCleanup_Failed", "Cleanup failed: {0}" },
            { "Dialog_TileCleanup_NoClient", "Please open a Lineage client first" },
        };
    }
}
